import { ToolConfig } from "@/types/tool";

export const developerTools: ToolConfig[] = [
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Format and beautify JSON data instantly",
    longDescription: "Format, beautify, and validate JSON data with syntax highlighting. Paste your JSON and get a properly formatted, readable output instantly.",
    instructions: ["Paste your JSON data", "Click Format", "Copy formatted JSON"],
    processingType: "browser",
    seoTitle: "JSON Formatter – Free Online JSON Beautifier | ToolPilot",
    seoDescription: "Format JSON online for free. Beautify and validate JSON data with syntax highlighting. Instant results.",
    keywords: ["json formatter", "json beautifier", "format json", "json validator"],
    icon: "Code2",
    featured: true,
    popular: true,
    faqs: [
      { question: "What is JSON?", answer: "JSON (JavaScript Object Notation) is a lightweight data interchange format commonly used in web APIs." },
      { question: "Is my JSON data sent to a server?", answer: "No, all formatting happens locally in your browser. Your data never leaves your device." },
    ],
    relatedTools: ["json-validator", "json-minifier", "base64-encoder"],
  },
  {
    name: "JSON Validator",
    slug: "json-validator",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Validate JSON data and find errors",
    longDescription: "Check if your JSON data is valid and find syntax errors. Highlights the exact location of errors for quick debugging.",
    instructions: ["Paste your JSON data", "Click Validate", "View validation results"],
    processingType: "browser",
    seoTitle: "JSON Validator – Free Online Validate JSON | ToolPilot",
    seoDescription: "Validate JSON data online for free. Find syntax errors instantly. Developer-friendly tool.",
    keywords: ["json validator", "validate json", "json checker", "json lint"],
    icon: "Code2",
    faqs: [
      { question: "What errors can it find?", answer: "Missing commas, unclosed brackets, trailing commas, incorrect quotes, and other syntax issues." },
    ],
    relatedTools: ["json-formatter", "json-minifier", "regex-tester"],
  },
  {
    name: "JSON Minifier",
    slug: "json-minifier",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Minify JSON to reduce file size",
    longDescription: "Remove whitespace and unnecessary characters from JSON data to reduce its size. Perfect for optimizing API payloads.",
    instructions: ["Paste your JSON data", "Click Minify", "Copy minified JSON"],
    processingType: "browser",
    seoTitle: "JSON Minifier – Free Online Minify JSON | ToolPilot",
    seoDescription: "Minify JSON online for free. Remove whitespace and reduce file size. Instant results.",
    keywords: ["json minifier", "minify json", "compress json", "json optimizer"],
    icon: "Code2",
    faqs: [
      { question: "Will minification change the data?", answer: "No, minification only removes whitespace and formatting. The data structure and values remain identical." },
    ],
    relatedTools: ["json-formatter", "json-validator", "url-encoder"],
  },
  {
    name: "Base64 Encoder",
    slug: "base64-encoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Encode text or files to Base64",
    longDescription: "Encode any text or file to Base64 string. Useful for embedding data in URLs, emails, and web pages.",
    instructions: ["Enter text or upload file", "Click Encode", "Copy Base64 string"],
    processingType: "browser",
    seoTitle: "Base64 Encoder – Free Online Encode to Base64 | ToolPilot",
    seoDescription: "Encode text to Base64 online for free. Fast Base64 encoding for text and files.",
    keywords: ["base64 encoder", "encode base64", "base64 encode text", "base64 convert"],
    icon: "Code2",
    popular: true,
    faqs: [
      { question: "What is Base64?", answer: "Base64 is an encoding scheme that represents binary data as ASCII text, commonly used for transmitting data over text-based protocols." },
    ],
    relatedTools: ["base64-decoder", "url-encoder", "uuid-generator"],
  },
  {
    name: "Base64 Decoder",
    slug: "base64-decoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Decode Base64 encoded strings back to text",
    longDescription: "Decode any Base64 encoded string back to its original text or data. Quick and reliable decoding.",
    instructions: ["Paste Base64 string", "Click Decode", "View decoded text"],
    processingType: "browser",
    seoTitle: "Base64 Decoder – Free Online Decode Base64 | ToolPilot",
    seoDescription: "Decode Base64 strings online for free. Convert Base64 back to text instantly.",
    keywords: ["base64 decoder", "decode base64", "base64 to text", "base64 decode"],
    icon: "Code2",
    popular: true,
    faqs: [
      { question: "What if the input is not valid Base64?", answer: "The tool will show an error message if the input is not valid Base64 encoded data." },
    ],
    relatedTools: ["base64-encoder", "url-decoder", "json-formatter"],
  },
  {
    name: "URL Encoder",
    slug: "url-encoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Encode URLs and query parameters",
    longDescription: "Encode special characters in URLs and query strings to make them safe for web transmission.",
    instructions: ["Enter URL or text", "Click Encode", "Copy encoded URL"],
    processingType: "browser",
    seoTitle: "URL Encoder – Free Online Encode URLs | ToolPilot",
    seoDescription: "Encode URLs online for free. URL encode special characters and query parameters instantly.",
    keywords: ["url encoder", "percent encoding", "encode url", "url encode"],
    icon: "Code2",
    faqs: [
      { question: "When do I need URL encoding?", answer: "URL encoding is needed when URLs contain special characters like spaces, ampersands, or non-ASCII characters." },
    ],
    relatedTools: ["url-decoder", "base64-encoder", "json-formatter"],
  },
  {
    name: "URL Decoder",
    slug: "url-decoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Decode URL-encoded strings",
    longDescription: "Decode percent-encoded URLs and query strings back to their readable form.",
    instructions: ["Paste encoded URL", "Click Decode", "View decoded URL"],
    processingType: "browser",
    seoTitle: "URL Decoder – Free Online Decode URLs | ToolPilot",
    seoDescription: "Decode URL-encoded strings online for free. Convert percent-encoded text instantly.",
    keywords: ["url decoder", "decode url", "percent decode", "url decode"],
    icon: "Code2",
    faqs: [
      { question: "What is percent encoding?", answer: "Percent encoding replaces special characters with a percent sign followed by two hex digits (e.g., space becomes %20)." },
    ],
    relatedTools: ["url-encoder", "base64-decoder", "json-formatter"],
  },
  {
    name: "UUID Generator",
    slug: "uuid-generator",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Generate UUIDs (Universally Unique Identifiers)",
    longDescription: "Generate random UUID v4 identifiers for use in databases, APIs, and applications. Generate single or batch UUIDs.",
    instructions: ["Select number of UUIDs", "Choose format options", "Click Generate", "Copy UUIDs"],
    processingType: "browser",
    seoTitle: "UUID Generator – Free Online Generate UUIDs | ToolPilot",
    seoDescription: "Generate UUIDs online for free. Create v4 UUIDs for databases and APIs. Batch generation supported.",
    keywords: ["uuid generator", "generate uuid", "unique identifier", "guid generator"],
    icon: "Code2",
    faqs: [
      { question: "What is a UUID?", answer: "A UUID (Universally Unique Identifier) is a 128-bit number used to uniquely identify information in computer systems." },
      { question: "How many UUIDs can I generate?", answer: "You can generate up to 100 UUIDs at once in various formats." },
    ],
    relatedTools: ["timestamp-converter", "json-formatter", "base64-encoder"],
  },
  {
    name: "Timestamp Converter",
    slug: "timestamp-converter",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Convert Unix timestamps to dates and back",
    longDescription: "Convert Unix timestamps (seconds/milliseconds) to human-readable dates and vice versa. Supports multiple date formats.",
    instructions: ["Enter timestamp or date", "Click Convert", "View result in various formats"],
    processingType: "browser",
    seoTitle: "Timestamp Converter – Free Online Unix Timestamp Tool | ToolPilot",
    seoDescription: "Convert Unix timestamps to dates online for free. Multiple formats supported. Instant conversion.",
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "date to timestamp"],
    icon: "Code2",
    faqs: [
      { question: "What is a Unix timestamp?", answer: "A Unix timestamp is the number of seconds elapsed since January 1, 1970 (the Unix epoch)." },
    ],
    relatedTools: ["uuid-generator", "json-formatter", "date-calculator"],
  },
  {
    name: "Regex Tester",
    slug: "regex-tester",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Test and debug regular expressions",
    longDescription: "Test regular expressions against sample text. See matches, groups, and highlights in real-time. Supports JavaScript regex syntax.",
    instructions: ["Enter your regex pattern", "Enter test string", "View matches and groups"],
    processingType: "browser",
    seoTitle: "Regex Tester – Free Online Regular Expression Tester | ToolPilot",
    seoDescription: "Test regular expressions online for free. Real-time matching, groups, and highlights. Developer-friendly.",
    keywords: ["regex tester", "regular expression tester", "regex test", "regex validator"],
    icon: "Code2",
    faqs: [
      { question: "What regex flavor is supported?", answer: "We support JavaScript regex syntax including flags like g (global), i (case-insensitive), and m (multiline)." },
    ],
    relatedTools: ["json-formatter", "word-counter", "json-validator"],
  },
  {
    name: "Word Counter",
    slug: "word-counter",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Count words, characters, and sentences",
    longDescription: "Count words, characters (with and without spaces), sentences, paragraphs, and lines in any text. Useful for essays, articles, and social media.",
    instructions: ["Paste your text", "View instant word and character counts", "See detailed breakdown"],
    processingType: "browser",
    seoTitle: "Word Counter – Free Online Word and Character Count | ToolPilot",
    seoDescription: "Count words and characters online for free. Instant word count, character count, sentence count. No signup.",
    keywords: ["word counter", "character counter", "word count", "text counter"],
    icon: "Code2",
    popular: true,
    faqs: [
      { question: "What counts are displayed?", answer: "Words, characters (with and without spaces), sentences, paragraphs, and estimated reading time." },
    ],
    relatedTools: ["lorem-ipsum-generator", "regex-tester", "json-formatter"],
  },
  {
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Generate placeholder text for designs and layouts",
    longDescription: "Generate random Lorem Ipsum placeholder text for website designs, mockups, and layouts. Choose paragraph count and word limits.",
    instructions: ["Select number of paragraphs", "Set word limit per paragraph", "Click Generate", "Copy text"],
    processingType: "browser",
    seoTitle: "Lorem Ipsum Generator – Free Online Placeholder Text | ToolPilot",
    seoDescription: "Generate Lorem Ipsum placeholder text online for free. Customizable paragraphs and word count.",
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "lorem ipsum"],
    icon: "Code2",
    faqs: [
      { question: "What is Lorem Ipsum?", answer: "Lorem Ipsum is standard placeholder text used in the design industry to demonstrate layout and typography." },
    ],
    relatedTools: ["word-counter", "json-formatter", "regex-tester"],
  },
];
