import { ToolConfig } from "@/types/tool";

export const careerTools: ToolConfig[] = [
  {
    name: "Resume Builder",
    slug: "resume-builder",
    category: "Career Tools",
    categorySlug: "career",
    description: "Build a professional resume with our free builder",
    longDescription: "Create a professional, ATS-friendly resume in minutes by choosing a ready-made template, adding your contact details, education, work history, and skills, and downloading the finished result as a PDF. It is built for Indian job seekers applying through job portals and company career pages, where a clean, scannable layout and standard section headings help your resume pass ATS filters and reach a recruiter.",
    instructions: [
      "Choose a template",
      "Fill in your contact details, education, and work history",
      "Customize each section with your skills and achievements",
      "Preview the final layout",
      "Download your resume as a PDF",
    ],
    processingType: "browser",
    seoTitle: "Resume Builder – Free Online Professional Resume Maker | ToolPilot",
    seoDescription: "Build a professional resume online for free. ATS-friendly templates. Download as PDF. No signup required.",
    keywords: ["resume builder", "free resume maker", "cv builder", "resume template"],
    icon: "Briefcase",
    featured: true,
    popular: true,
    faqs: [
      { question: "Are the resumes ATS-friendly?", answer: "Yes, our templates are designed to pass Applicant Tracking Systems (ATS) used by employers." },
      { question: "Can I download as PDF?", answer: "Yes, you can download your completed resume as a high-quality PDF file." },
      { question: "Do I need to create an account?", answer: "No, you can build and download your resume without signing up or paying anything." },
      { question: "Can I edit my resume later?", answer: "Yes, you can change any detail and re-download an updated PDF whenever you need it, for example before your next application." },
      { question: "Will the PDF look the same on any device?", answer: "Yes, the PDF keeps your layout intact on computers, phones, and when printed, which is mostly how recruiters will view it." },
    ],
    relatedTools: ["resume-analyzer", "resume-ats-checker", "resume-jd-matcher", "cover-letter-generator"],
  },
  {
    name: "Resume Analyzer",
    slug: "resume-analyzer",
    category: "Career Tools",
    categorySlug: "career",
    description: "Upload or paste your resume for full ATS analysis, JD matching, and rewrite suggestions",
    longDescription: "The ultimate resume optimization tool. Upload a PDF, DOCX, or paste text to get: ATS compatibility score with category breakdown, job description matching with semantic gap analysis, and AI-powered rewrite suggestions. All processing happens in your browser.",
    instructions: ["Upload a PDF/DOCX or paste your resume text", "View ATS score and category breakdown", "Paste a job description to match", "Get rewrite suggestions"],
    processingType: "browser",
    seoTitle: "Resume Analyzer – Free ATS Score, JD Match & Rewrite Suggestions | ToolPilot",
    seoDescription: "Analyze your resume for free. Get ATS score, job description matching, semantic gap analysis, and rewrite suggestions. Upload PDF or paste text.",
    keywords: ["resume analyzer", "ats score checker", "resume jd match", "resume rewrite", "resume optimization"],
    icon: "Briefcase",
    featured: true,
    popular: true,
    faqs: [
      { question: "What file formats are supported?", answer: "PDF, DOCX, and plain text files. All parsing happens in your browser — files are never uploaded to any server." },
      { question: "How does JD matching work?", answer: "It compares your resume against the job description using keyword matching, semantic analysis, and identifies gaps, over-indexed items, and missing requirements." },
      { question: "What are rewrite suggestions?", answer: "Actionable improvements for each section — identifies clichés, weak verbs, missing quantified achievements, and suggests stronger alternatives." },
    ],
    relatedTools: ["resume-builder", "resume-ats-checker", "resume-jd-matcher", "cover-letter-generator"],
  },
  {
    name: "Resume ATS Checker",
    slug: "resume-ats-checker",
    category: "Career Tools",
    categorySlug: "career",
    description: "Check if your resume passes ATS screening",
    longDescription: "Upload or paste your resume and receive an ATS compatibility score with clear feedback on layout, section headings, keyword coverage, and missing details that automated screening systems flag. It is helpful when your applications keep getting rejected without interviews, because small fixes like standard headings, straightforward formatting, and matching the keywords in the job posting can noticeably improve how your resume performs.",
    instructions: [
      "Upload your resume as a PDF or paste the text",
      "Enter the job description to match against (optional)",
      "Run the ATS analysis",
      "Review your ATS score and section-by-section feedback",
      "Apply the recommendations and re-check your resume",
    ],
    processingType: "ai",
    seoTitle: "Resume ATS Checker – Free Online ATS Score Checker | ToolPilot",
    seoDescription: "Check your resume ATS score online for free. See if your resume passes Applicant Tracking Systems.",
    keywords: ["ats checker", "resume ats score", "ats resume check", "resume scanner"],
    icon: "Briefcase",
    popular: true,
    faqs: [
      { question: "What is ATS?", answer: "ATS (Applicant Tracking System) is software used by employers to filter and rank job applications." },
      { question: "How accurate is the ATS score?", answer: "This is an AI-based estimate, not an actual employer ATS score. It provides useful guidance for optimization." },
      { question: "Which parts of my resume are checked?", answer: "The tool reviews common ATS checks such as standard section headings, contact details, keyword coverage, and layout issues that can stop your resume from being parsed correctly." },
      { question: "Is my resume data private?", answer: "Yes, your resume is handled securely and is not stored or shared after the check." },
      { question: "Can I check the same resume again after editing?", answer: "Yes, you can run the check as many times as you like and keep improving until you are happy with the feedback." },
    ],
    relatedTools: ["resume-builder", "resume-jd-matcher", "cover-letter-generator"],
  },
  {
    name: "Resume-JD Matcher",
    slug: "resume-jd-matcher",
    category: "Career Tools",
    categorySlug: "career",
    description: "Match your resume against a job description",
    longDescription: "Paste a job description alongside your resume to receive a compatibility score, a skill-gap breakdown, and the keywords the employer is looking for. It is especially useful while applying to specific openings, since you can spot which requirements you already meet, which ones to highlight or learn, and how to tailor one resume to a particular role before you hit submit.",
    instructions: [
      "Upload your resume or paste its text",
      "Paste the full job description",
      "Run the matching analysis",
      "Review the compatibility score and skill-gap breakdown",
      "Use the recommendations to tailor your resume for the role",
    ],
    processingType: "ai",
    seoTitle: "Resume-JD Matcher – Free Online Resume Job Match Tool | ToolPilot",
    seoDescription: "Match your resume against job descriptions online. Find skill gaps and missing keywords. AI-powered analysis.",
    keywords: ["resume matcher", "job description matcher", "resume job match", "skill gap analyzer"],
    icon: "Briefcase",
    faqs: [
      { question: "Is this the same as an employer's ATS score?", answer: "No, this is an AI-based compatibility estimate designed to help you improve your resume. It is not an actual employer ATS score." },
      { question: "What does it analyze?", answer: "Overall match, skills match, experience, education, domain relevance, missing keywords, strengths, weaknesses, and recommendations." },
      { question: "Which file formats are supported?", answer: "You can upload a PDF or DOCX resume, or simply paste the resume text directly, whichever is easier for you." },
      { question: "How can I improve my match score?", answer: "Look at the missing keywords and skill gaps in the report and update your resume to include those points honestly, then run the match again to see your progress." },
      { question: "Can I match the same resume against different job descriptions?", answer: "Yes, paste each new job description and analyze it separately, which helps when you are applying to several different roles." },
    ],
    relatedTools: ["resume-ats-checker", "resume-builder", "cover-letter-generator"],
  },
  {
    name: "Cover Letter Generator",
    slug: "cover-letter-generator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Generate a professional cover letter with AI",
    longDescription: "Create a personalized cover letter in minutes by uploading your resume and pasting the job description, and the generator will draft a tailored letter that matches the role. It takes the pain out of job applications when you are applying to many companies at once, giving you a relevant, professional starting point for every position instead of writing each letter from scratch.",
    instructions: [
      "Upload your resume or paste your key details",
      "Paste the job description for the role",
      "Generate your tailored cover letter",
      "Review and edit the draft to add your own voice",
      "Download or copy the final letter",
    ],
    processingType: "ai",
    seoTitle: "Cover Letter Generator – Free AI Cover Letter Maker | ToolPilot",
    seoDescription: "Generate professional cover letters online for free. AI-powered, personalized for each job application.",
    keywords: ["cover letter generator", "cover letter maker", "ai cover letter", "cover letter template"],
    icon: "Briefcase",
    popular: true,
    faqs: [
      { question: "Is the cover letter unique?", answer: "Yes, each cover letter is generated uniquely based on your resume and the specific job description." },
      { question: "Do I need to write the letter myself?", answer: "No, the generator writes the first draft for you. You can still review and tweak it so the tone sounds like you." },
      { question: "Can I use it for any job role?", answer: "Yes, it works across a wide range of roles and industries because the letter is built around the job description you provide." },
      { question: "Is the cover letter generator free?", answer: "Yes, generating cover letters is free and does not require creating an account." },
    ],
    relatedTools: ["resume-builder", "resume-ats-checker", "resume-jd-matcher"],
  },
  {
    name: "Salary Calculator",
    slug: "salary-calculator-career",
    category: "Career Tools",
    categorySlug: "career",
    description: "Estimate your market salary based on experience and skills",
    longDescription: "Get an estimated market salary range for your role by entering your job title, years of experience, core skills, and location. It helps you negotiate with confidence during job offers and appraisals, so you know whether a package is fair for your level and can plan your next career step without guesswork.",
    instructions: [
      "Select your job role",
      "Enter your years of experience",
      "Add your core skills",
      "Choose your work location",
      "View your estimated salary range",
    ],
    processingType: "browser",
    seoTitle: "Salary Calculator – Free Online Salary Estimator | ToolPilot",
    seoDescription: "Estimate your market salary online for free. Based on role, experience, skills, and location.",
    keywords: ["salary calculator", "salary estimator", "market salary", "salary range"],
    icon: "Briefcase",
    faqs: [
      { question: "How accurate is the estimate?", answer: "This is an approximate estimate based on market data. Actual salaries may vary based on company, negotiation, and other factors." },
      { question: "Do I need to share my current salary?", answer: "No, the estimate is based only on your role, experience, skills, and location. Your current salary and company details are not required." },
      { question: "Is the salary calculator free?", answer: "Yes, it is completely free and gives you an estimate instantly without creating an account." },
      { question: "How can I use the range in negotiation?", answer: "Use the range as a reference point for your level and back it up with the skills you bring. Final offers still depend on the company's budget and market conditions." },
    ],
    relatedTools: ["resume-builder", "notice-period-calculator", "experience-calculator"],
  },
  {
    name: "Notice Period Calculator",
    slug: "notice-period-calculator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Calculate your notice period end date",
    longDescription: "Calculate the exact end date of your notice period by entering your notice start date and the agreed duration, with the option to skip weekends and public holidays. It is handy when resigning from a current job, joining a new company, or confirming your last working day for relieving letters and experience certificates, so you can plan a smooth transition without guesswork.",
    instructions: [
      "Enter your notice period start date",
      "Enter the notice period duration in days or months",
      "Choose whether to exclude weekends",
      "Add public holidays to exclude, if any",
      "View your last working day and total days",
    ],
    processingType: "browser",
    seoTitle: "Notice Period Calculator – Free Online Calculate Notice Period | ToolPilot",
    seoDescription: "Calculate your notice period end date online for free. Include or exclude weekends.",
    keywords: ["notice period calculator", "notice period end date", "last working day calculator"],
    icon: "Briefcase",
    faqs: [
      { question: "Does it exclude weekends?", answer: "Yes, you can choose to exclude weekends and public holidays from the notice period calculation." },
      { question: "What does the end date mean?", answer: "The end date is your expected last working day based on the start date and the full notice duration you entered. Your HR team still confirms the final date officially." },
      { question: "Can I count my notice period in days?", answer: "Yes, you can enter the duration in days or months so it fits however your offer letter states the notice period." },
      { question: "Is the notice period calculator free?", answer: "Yes, it works instantly in your browser and is free to use without any signup." },
    ],
    relatedTools: ["experience-calculator", "date-calculator", "salary-calculator-career"],
  },
  {
    name: "Experience Calculator",
    slug: "experience-calculator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Calculate total work experience in years and months",
    longDescription: "Calculate your total professional work experience in years, months, and days by adding each job with its start and end dates, including current roles. It is useful when filling in application forms, updating a resume or LinkedIn profile, and quoting your total experience in interviews, so your numbers stay consistent with what recruiters and HR systems compute.",
    instructions: [
      "Add your first job with its start and end dates",
      "Repeat for each additional job tenure",
      "Mark any role that is still ongoing",
      "Review each entry for accuracy",
      "View your total experience in years, months, and days",
    ],
    processingType: "browser",
    seoTitle: "Experience Calculator – Free Online Work Experience Calculator | ToolPilot",
    seoDescription: "Calculate total work experience online for free. Add multiple tenures. Get years, months, and days.",
    keywords: ["experience calculator", "work experience calculator", "total experience", "career calculator"],
    icon: "Briefcase",
    faqs: [
      { question: "Can I add multiple jobs?", answer: "Yes, you can add unlimited job tenures to calculate your total combined experience." },
      { question: "Does it count a current role?", answer: "Yes, you can mark a role as ongoing and the calculator counts it up to the present date." },
      { question: "What if two jobs overlap?", answer: "The calculator adds the duration of every tenure you enter, so overlapping periods are counted twice. Review your entries if your roles overlap." },
      { question: "How do I use the result on my resume?", answer: "Quote the total years and months in your resume summary and interview answers so your experience is consistent everywhere." },
    ],
    relatedTools: ["notice-period-calculator", "resume-builder", "salary-calculator-career"],
  },
  {
    name: "Interview Question Generator",
    slug: "interview-question-generator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Generate interview questions for any role",
    longDescription: "Generate realistic interview questions for any job role and industry by choosing the role, seniority level, and question type, including behavioral, technical, and situational formats. It is a practical way to prepare before interviews, whether you are a fresh graduate facing campus recruitment or an experienced professional switching companies, so you can practice strong, honest answers and feel confident on the day.",
    instructions: [
      "Choose a job role and industry",
      "Select the seniority level, such as fresher or experienced",
      "Pick the question types, like technical or behavioral",
      "Generate the interview question set",
      "Review the questions and practice your answers",
    ],
    processingType: "ai",
    seoTitle: "Interview Question Generator – Free Online Interview Prep | ToolPilot",
    seoDescription: "Generate interview questions online for free. Practice for any role or industry. AI-powered.",
    keywords: ["interview questions", "interview prep", "mock interview", "interview practice"],
    icon: "Briefcase",
    faqs: [
      { question: "What types of questions are generated?", answer: "Behavioral, technical, situational, and role-specific questions tailored to your selected job role." },
      { question: "Can I use this for campus placements?", answer: "Yes, you can pick fresher or entry-level roles and generate questions commonly asked during campus recruitment and first interviews." },
      { question: "Does it include answers?", answer: "It provides practice questions to work through. Try answering each one out loud or in writing to build confidence before the interview." },
      { question: "Is the generator free?", answer: "Yes, generating practice questions is free and does not require creating an account." },
    ],
    relatedTools: ["resume-builder", "resume-ats-checker", "cover-letter-generator"],
  },
  {
    name: "Job Description Analyzer",
    slug: "job-description-analyzer",
    category: "Career Tools",
    categorySlug: "career",
    description: "Analyze job descriptions for key requirements",
    longDescription: "Paste any job description and get a clear breakdown of the key skills, qualifications, responsibilities, and important keywords the employer is looking for. It is useful when tailoring your resume and preparing for interviews, because it shows exactly what matters for the role so you can align your application and answers to the job instead of guessing.",
    instructions: [
      "Copy the full job description text",
      "Paste it into the analyzer",
      "Run the analysis",
      "Review the extracted skills, qualifications, and responsibilities",
      "Apply the important keywords to your resume",
    ],
    processingType: "ai",
    seoTitle: "Job Description Analyzer – Free Online JD Analyzer | ToolPilot",
    seoDescription: "Analyze job descriptions online for free. Extract key skills, requirements, and keywords. AI-powered.",
    keywords: ["job description analyzer", "jd analyzer", "job requirements", "keyword extractor"],
    icon: "Briefcase",
    faqs: [
      { question: "What does it extract?", answer: "Key skills, required qualifications, experience level, responsibilities, and important keywords." },
      { question: "What experience level does the job need?", answer: "The analyzer identifies the experience level and qualifications mentioned in the job description, along with the main responsibilities." },
      { question: "Can I analyze more than one job description?", answer: "Yes, paste a different job description anytime and run the analysis again to compare requirements across roles." },
      { question: "Is the analyzer free?", answer: "Yes, it is free to use and does not require creating an account." },
    ],
    relatedTools: ["resume-jd-matcher", "resume-ats-checker", "interview-question-generator"],
  },
];
