import { ToolConfig } from "@/types/tool";

export const imageTools: ToolConfig[] = [
  {
    name: "Image Compressor",
    slug: "image-compressor",
    category: "Image Tools",
    categorySlug: "image",
    description: "Compress images to reduce file size without losing quality",
    longDescription: "Shrink your JPG, PNG, WebP, and GIF images without sacrificing visible quality. Perfect for making images load faster on your website, fitting them inside email or WhatsApp attachments, and keeping your photo library small. Our image compressor runs entirely in your browser and shows you a live before-and-after preview, so you can choose the right balance between file size and clarity. No uploads, no servers, and no limits — your photos never leave your device.",
    instructions: [
      "Upload one or more images (JPG, PNG, WebP, or GIF)",
      "Move the quality slider to your preferred level",
      "Watch the live size-reduction preview",
      "Click Compress",
      "Download your optimized images",
    ],
    processingType: "browser",
    seoTitle: "Image Compressor – Free Online Reduce Image Size | ToolPilot",
    seoDescription: "Compress images online for free. Reduce JPG, PNG, WebP size without losing quality. Fast, private, and easy to use.",
    keywords: ["image compressor", "compress image", "reduce image size", "optimize image"],
    icon: "Image",
    featured: true,
    popular: true,
    faqs: [
      { question: "What image formats are supported?", answer: "We support JPG, PNG, WebP, and GIF formats." },
      { question: "Is compression done in my browser?", answer: "Yes, all compression happens locally in your browser. Your images never leave your device." },
      { question: "How much will my image shrink?", answer: "Depending on the format and quality level you choose, most images reduce in size by 50-80% with no visible difference in quality." },
      { question: "Can I compress multiple images at once?", answer: "Yes, you can upload and compress several images in one go and download them together." },
    ],
    relatedTools: ["image-resizer", "webp-converter", "image-quality-optimizer"],
  },
  {
    name: "Image Resizer",
    slug: "image-resizer",
    category: "Image Tools",
    categorySlug: "image",
    description: "Resize images to any dimension online for free",
    longDescription: "Change your image to any width and height in seconds, without installing software. Perfect for resizing photos for social media profile pictures, website banners, document attachments, or product images. You can enter exact dimensions, choose a preset like square or 16:9, and let the tool maintain the aspect ratio automatically to avoid stretching. Everything is processed locally in your browser, keeping your images private.",
    instructions: [
      "Upload your image",
      "Enter the desired width and height",
      "Choose a preset ratio or keep aspect ratio locked",
      "Preview the result",
      "Download your resized image",
    ],
    processingType: "browser",
    seoTitle: "Image Resizer – Free Online Resize Image Tool | ToolPilot",
    seoDescription: "Resize images online for free. Change width and height. Maintain aspect ratio. Fast and private.",
    keywords: ["image resizer", "resize image", "change image size", "image dimensions"],
    icon: "Image",
    popular: true,
    faqs: [
      { question: "Can I maintain aspect ratio?", answer: "Yes, by default aspect ratio is maintained. You can also lock or unlock it manually to set custom proportions." },
      { question: "What sizes can I resize to?", answer: "Any size. Enter exact pixel dimensions or pick a preset such as square, 4:3, 16:9, or 9:16 for stories and posts." },
      { question: "Why does image size matter?", answer: "Instagram posts are around 1080x1080, YouTube thumbnails 1280x720, and passport photos have their own standards, so resizing saves time and storage." },
      { question: "Are my images private?", answer: "Yes. Resizing happens entirely in your browser, so your image never leaves your device." },
    ],
    relatedTools: ["image-compressor", "image-cropper", "image-rotator"],
  },
  {
    name: "JPG to PNG",
    slug: "jpg-to-png",
    category: "Image Tools",
    categorySlug: "image",
    description: "Convert JPG images to PNG format online for free",
    longDescription: "Convert JPG/JPEG images to PNG format with transparency support. Perfect for graphics, logos, and images that need transparent backgrounds.",
    instructions: ["Upload your JPG image", "Click Convert", "Download PNG image"],
    processingType: "browser",
    seoTitle: "JPG to PNG Converter – Free Online JPG to PNG Tool | ToolPilot",
    seoDescription: "Convert JPG to PNG online for free. Fast image format converter. Supports transparency. No signup required.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png", "image converter"],
    icon: "Image",
    faqs: [
      { question: "Why convert JPG to PNG?", answer: "PNG supports transparency and lossless compression, making it ideal for graphics and logos." },
    ],
    relatedTools: ["png-to-jpg", "webp-converter", "image-compressor"],
  },
  {
    name: "PNG to JPG",
    slug: "png-to-jpg",
    category: "Image Tools",
    categorySlug: "image",
    description: "Convert PNG images to JPG format online for free",
    longDescription: "Convert PNG images to JPG format for smaller file sizes. Ideal for photos and images without transparency.",
    instructions: ["Upload your PNG image", "Adjust quality if needed", "Click Convert", "Download JPG image"],
    processingType: "browser",
    seoTitle: "PNG to JPG Converter – Free Online PNG to JPG Tool | ToolPilot",
    seoDescription: "Convert PNG to JPG online for free. Reduce file size with quality control. Fast and private.",
    keywords: ["png to jpg", "convert png to jpg", "png to jpeg", "image converter"],
    icon: "Image",
    faqs: [
      { question: "Will PNG to JPG reduce quality?", answer: "JPG uses lossy compression so there may be slight quality reduction, but file sizes are much smaller." },
    ],
    relatedTools: ["jpg-to-png", "webp-converter", "image-compressor"],
  },
  {
    name: "WebP Converter",
    slug: "webp-converter",
    category: "Image Tools",
    categorySlug: "image",
    description: "Convert images to/from WebP format online for free",
    longDescription: "Convert any image format to WebP or convert WebP to JPG/PNG. WebP offers better compression for web images.",
    instructions: ["Upload your image", "Select output format", "Click Convert", "Download converted image"],
    processingType: "browser",
    seoTitle: "WebP Converter – Free Online WebP Image Tool | ToolPilot",
    seoDescription: "Convert images to/from WebP format online for free. Better compression, smaller files. Fast and private.",
    keywords: ["webp converter", "convert to webp", "webp to jpg", "webp to png"],
    icon: "Image",
    faqs: [
      { question: "What is WebP?", answer: "WebP is a modern image format by Google that provides superior compression for web images." },
    ],
    relatedTools: ["jpg-to-png", "png-to-jpg", "image-compressor"],
  },
  {
    name: "Image Cropper",
    slug: "image-cropper",
    category: "Image Tools",
    categorySlug: "image",
    description: "Crop images to any size or aspect ratio online for free",
    longDescription: "Crop images to custom dimensions or predefined aspect ratios. Perfect for profile pictures, thumbnails, and social media.",
    instructions: ["Upload your image", "Select crop area", "Choose aspect ratio", "Download cropped image"],
    processingType: "browser",
    seoTitle: "Image Cropper – Free Online Crop Image Tool | ToolPilot",
    seoDescription: "Crop images online for free. Custom dimensions and aspect ratios. Fast, easy, and private.",
    keywords: ["image cropper", "crop image", "trim image", "cut image"],
    icon: "Image",
    faqs: [
      { question: "What aspect ratios are available?", answer: "We offer free crop, square, 16:9, 4:3, 3:2, and custom ratios." },
    ],
    relatedTools: ["image-resizer", "image-rotator", "image-compressor"],
  },
  {
    name: "Image Rotator",
    slug: "image-rotator",
    category: "Image Tools",
    categorySlug: "image",
    description: "Rotate images online for free",
    longDescription: "Rotate images by any angle or flip horizontally/vertically. Fix orientation from phone photos and scans.",
    instructions: ["Upload your image", "Choose rotation angle", "Preview result", "Download rotated image"],
    processingType: "browser",
    seoTitle: "Image Rotator – Free Online Rotate Image Tool | ToolPilot",
    seoDescription: "Rotate images online for free. Any angle, flip horizontal/vertical. Fast and private.",
    keywords: ["image rotator", "rotate image", "flip image", "turn image"],
    icon: "Image",
    faqs: [
      { question: "Can I rotate by custom angles?", answer: "Yes, you can rotate by 90 degrees, 180 degrees, 270 degrees or any custom angle." },
    ],
    relatedTools: ["image-cropper", "image-resizer", "image-compressor"],
  },
  {
    name: "Image Quality Optimizer",
    slug: "image-quality-optimizer",
    category: "Image Tools",
    categorySlug: "image",
    description: "Optimize image quality and file size for web use",
    longDescription: "Automatically optimize images for web by balancing quality and file size. Perfect for website performance and faster page loads.",
    instructions: ["Upload your image", "Select optimization level", "Click Optimize", "Download optimized image"],
    processingType: "browser",
    seoTitle: "Image Quality Optimizer – Free Online Image Optimization | ToolPilot",
    seoDescription: "Optimize images for web automatically. Balance quality and file size. Improve page speed.",
    keywords: ["image optimizer", "optimize image", "image quality", "web image optimization"],
    icon: "Image",
    faqs: [
      { question: "How does optimization differ from compression?", answer: "Optimization considers both quality and file size to find the best balance for web use." },
    ],
    relatedTools: ["image-compressor", "image-resizer", "webp-converter"],
  },
];
