import { ToolConfig } from "@/types/tool";

export const aiTools: ToolConfig[] = [
  {
    name: "AI Text Humanizer",
    slug: "ai-text-humanizer",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Make AI-generated text sound natural and human",
    longDescription: "Transform AI-generated content into natural, human-sounding text. Remove robotic patterns and make content more engaging and authentic.",
    instructions: ["Paste AI-generated text", "Click Humanize", "Copy the humanized text"],
    processingType: "ai",
    seoTitle: "AI Text Humanizer – Free Online Make AI Text Human | ToolPilot",
    seoDescription: "Humanize AI-generated text online for free. Make AI content sound natural and authentic.",
    keywords: ["ai humanizer", "text humanizer", "ai to human text", "make ai text natural"],
    icon: "Sparkles",
    popular: true,
    faqs: [
      { question: "How does text humanization work?", answer: "AI restructures sentences, varies vocabulary, and adds natural phrasing while preserving the original meaning." },
      { question: "Does it change the meaning?", answer: "No, the core message and meaning are preserved while the writing style becomes more natural." },
    ],
    relatedTools: ["ai-text-summarizer", "ai-paraphraser", "ai-email-generator"],
  },
  {
    name: "AI Text Summarizer",
    slug: "ai-text-summarizer",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Summarize long text into key points",
    longDescription: "Condense long articles, documents, or text into concise summaries. Get the key points without reading the entire content.",
    instructions: ["Paste the text to summarize", "Select summary length", "Get your summary"],
    processingType: "ai",
    seoTitle: "AI Text Summarizer – Free Online Summarize Text | ToolPilot",
    seoDescription: "Summarize text online for free. AI-powered text summarizer. Get key points instantly.",
    keywords: ["text summarizer", "ai summarizer", "summarize text", "text summarization"],
    icon: "Sparkles",
    faqs: [
      { question: "How long can the input text be?", answer: "You can summarize text up to 10,000 words at once." },
    ],
    relatedTools: ["ai-text-humanizer", "ai-paraphraser", "word-counter"],
  },
  {
    name: "AI Paraphraser",
    slug: "ai-paraphraser",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Rewrite text while preserving meaning",
    longDescription: "Rewrite content in different words while maintaining the original meaning. Useful for improving clarity and avoiding repetition.",
    instructions: ["Paste the text to paraphrase", "Select style (formal/casual/creative)", "Get paraphrased text"],
    processingType: "ai",
    seoTitle: "AI Paraphraser – Free Online Rewrite Text | ToolPilot",
    seoDescription: "Paraphrase text online for free. AI-powered rewriting tool. Multiple styles available.",
    keywords: ["paraphraser", "ai paraphraser", "rewrite text", "text rewriter"],
    icon: "Sparkles",
    faqs: [
      { question: "What styles are available?", answer: "Formal, casual, creative, academic, and professional writing styles." },
    ],
    relatedTools: ["ai-text-humanizer", "ai-text-summarizer", "ai-email-generator"],
  },
  {
    name: "AI Cover Letter Generator",
    slug: "ai-cover-letter-generator",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Generate tailored cover letters with AI",
    longDescription: "Create personalized cover letters for any job application. AI crafts content based on your resume and job description.",
    instructions: ["Upload your resume", "Paste job description", "Generate and download cover letter"],
    processingType: "ai",
    seoTitle: "AI Cover Letter Generator – Free Online Cover Letter Maker | ToolPilot",
    seoDescription: "Generate AI cover letters online for free. Tailored for each job application. Professional and unique.",
    keywords: ["ai cover letter", "cover letter generator", "cover letter maker", "job cover letter"],
    icon: "Sparkles",
    faqs: [
      { question: "Is each cover letter unique?", answer: "Yes, each cover letter is uniquely generated based on your specific resume and the target job." },
    ],
    relatedTools: ["ai-resume-summary-generator", "ai-email-generator", "resume-builder"],
  },
  {
    name: "AI Resume Summary Generator",
    slug: "ai-resume-summary-generator",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Generate a professional resume summary",
    longDescription: "Create a compelling resume summary or objective statement. AI analyzes your experience and generates a tailored professional summary.",
    instructions: ["Enter your role and experience", "Add key skills", "Generate resume summary"],
    processingType: "ai",
    seoTitle: "AI Resume Summary Generator – Free Online Resume Summary | ToolPilot",
    seoDescription: "Generate resume summaries online for free. AI-powered professional summary for your resume.",
    keywords: ["resume summary generator", "professional summary", "resume objective", "career summary"],
    icon: "Sparkles",
    faqs: [
      { question: "How long should a resume summary be?", answer: "2-4 sentences or 50-100 words is ideal. It should highlight your key qualifications and career goals." },
    ],
    relatedTools: ["ai-cover-letter-generator", "resume-builder", "ai-paraphraser"],
  },
  {
    name: "AI Email Generator",
    slug: "ai-email-generator",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Generate professional emails for any occasion",
    longDescription: "Create professional emails for business communication, follow-ups, cold outreach, and more. Choose tone and purpose.",
    instructions: ["Select email type and tone", "Add context and details", "Generate and copy email"],
    processingType: "ai",
    seoTitle: "AI Email Generator – Free Online Professional Email Writer | ToolPilot",
    seoDescription: "Generate professional emails online for free. AI-powered email writer for business and personal use.",
    keywords: ["email generator", "ai email writer", "professional email", "email template"],
    icon: "Sparkles",
    faqs: [
      { question: "What email types are supported?", answer: "Business inquiry, follow-up, cold outreach, thank you, apology, resignation, and custom emails." },
    ],
    relatedTools: ["ai-text-humanizer", "ai-paraphraser", "ai-text-summarizer"],
  },
];
