import { ToolConfig } from "@/types/tool";

export const videoTools: ToolConfig[] = [
  {
    name: "Video Compressor",
    slug: "video-compressor",
    category: "Video Tools",
    categorySlug: "video",
    description: "Compress MP4 video files to reduce size without losing much quality",
    longDescription: "Compress MP4 videos right in your browser using the full FFmpeg engine, no upload required. Choose a compression level that balances file size and quality, or downscale to 720p or 480p for videos meant for WhatsApp, email, or uploading with a slow connection. The compression runs entirely on your device with FFmpeg's H.264 encoder, which is the same professional encoder used by broadcasters and video hosting sites. Your video never leaves your computer, so you can safely work with personal or client footage. Ideal for shrinking large phone recordings, screen captures, and marketing clips before sending them anywhere.",
    instructions: [
      "Upload your MP4 (or MOV, WebM, AVI, MKV) video",
      "Choose a compression level: Balanced, Smaller file, or Higher quality",
      "Optionally pick a smaller output resolution like 720p or 480p",
      "Click Compress Video",
      "Wait for the on-device FFmpeg engine to finish, then download the result",
    ],
    processingType: "browser",
    seoTitle: "Video Compressor – Compress MP4 Online Free | ToolPilot",
    seoDescription: "Compress MP4 video online for free. Reduce video file size right in your browser with FFmpeg. No upload, no signup.",
    keywords: ["video compressor", "compress video", "reduce video size", "mp4 compressor", "shrink video file"],
    icon: "Video",
    featured: true,
    popular: true,
    faqs: [
      { question: "Is the video uploaded to a server?", answer: "No. Compression runs entirely in your browser using FFmpeg. Your video never leaves your device." },
      { question: "How much will my video shrink?", answer: "The Balanced preset with the default CRF value typically cuts file size roughly in half or more on phone recordings. Downscaling to 720p or 480p shrinks it further when full resolution is not needed." },
      { question: "Which formats are supported?", answer: "The compressor reads MP4, MOV, WebM, AVI, MKV, and M4V files and always outputs a broadly compatible MP4 with H.264 video and AAC audio." },
      { question: "Why does it take a while on the first run?", answer: "The first conversion downloads and loads the FFmpeg engine (~30 MB) into your browser. Later conversions reuse it, so they start instantly." },
      { question: "Is this free?", answer: "Yes, completely free with no watermark, no signup, and no usage limits." },
    ],
    relatedTools: ["video-to-gif", "mp4-to-mp3"],
  },
  {
    name: "MP4 to MP3 Converter",
    slug: "mp4-to-mp3",
    category: "Video Tools",
    categorySlug: "video",
    description: "Extract audio from video and save it as an MP3 file online free",
    longDescription: "Turn any video into an MP3 audio file in your browser. Perfect for pulling a song out of a music video, saving the audio from a lecture recording, converting a voice memo, or building a personal podcast collection. Choose your bitrate — 128, 192, or 320 kbps — to balance file size against audio fidelity. The conversion runs locally on your device with the FFmpeg engine, so your file is never uploaded anywhere. Video, audio, and screencast files are all supported as input.",
    instructions: [
      "Upload your video or audio file (MP4, MOV, WebM, MKV, AVI, M4A, and more)",
      "Pick an audio quality: 128, 192, or 320 kbps",
      "Click Convert to MP3",
      "Wait for the on-device conversion, then download your MP3",
    ],
    processingType: "browser",
    seoTitle: "MP4 to MP3 Converter – Extract Audio Online Free | ToolPilot",
    seoDescription: "Convert MP4 to MP3 online free. Extract audio from any video in your browser with FFmpeg. No upload, no signup.",
    keywords: ["mp4 to mp3", "extract audio from video", "video to audio", "mp3 converter", "audio extractor"],
    icon: "Music",
    popular: true,
    faqs: [
      { question: "Is this a YouTube downloader?", answer: "No. This tool converts files that are already on your device. Please download videos only when you have the rights or permission to do so." },
      { question: "Which bitrate should I choose?", answer: "192 kbps is a great balance for most audio. Choose 320 kbps for music you care about and 128 kbps when file size matters more, like for voice recordings." },
      { question: "Does my file leave my device?", answer: "No. The conversion runs in your browser with FFmpeg, so your file is processed locally and never uploaded." },
      { question: "Can I convert from a phone?", answer: "Yes, the tool works fully on mobile browsers. On iPhone, export videos to Files first if the upload picker limits you." },
    ],
    relatedTools: ["video-compressor", "video-to-gif"],
  },
  {
    name: "Video to GIF Converter",
    slug: "video-to-gif",
    category: "Video Tools",
    categorySlug: "video",
    description: "Convert video clips into animated GIFs online for free",
    longDescription: "Turn your favorite video moments into shareable animated GIFs without leaving your browser. Upload any MP4, MOV, WebM, AVI, or MKV clip, choose the frame rate, output width, and clip length, and download a ready-to-share GIF. Great for making reaction GIFs from movie scenes, short product demos for WhatsApp, or looping memes for social posts. The whole conversion runs locally with FFmpeg, so your clip never gets uploaded to a server.",
    instructions: [
      "Upload your video clip",
      "Choose a frame rate: 10, 15, or 24 fps",
      "Pick an output width or keep the original",
      "Choose a clip length or use the full video",
      "Click Create GIF and download the result",
    ],
    processingType: "browser",
    seoTitle: "Video to GIF Converter – Create Animated GIF Online Free | ToolPilot",
    seoDescription: "Convert video to animated GIF online free. Make GIFs from MP4, MOV, WebM clips in your browser with FFmpeg.",
    keywords: ["video to gif", "make gif from video", "gif maker", "animated gif converter", "create gif online"],
    icon: "Film",
    faqs: [
      { question: "How do I make a GIF smaller?", answer: "Lower the frame rate to 10 fps, reduce the width to 360 or 480 px, and clip to the first 5 seconds — all three shrink the file a lot with short clips." },
      { question: "Is the clip uploaded anywhere?", answer: "No. Conversion runs entirely in your browser, so your video is never sent to a server." },
      { question: "Why do GIF files stay larger than video?", answer: "GIF is an old lossless format without modern video compression, so size grows quickly with high frame rates and resolution. Keeping clips short and small is the key." },
      { question: "What clip lengths can I use?", answer: "The Full video option uses the entire clip. For quick shares, the first-5-seconds or first-10-seconds options work best and keep the file small." },
    ],
    relatedTools: ["video-compressor", "mp4-to-mp3"],
  },
];