import { ToolConfig } from "@/types/tool";

export const businessTools: ToolConfig[] = [
  {
    name: "Invoice Generator",
    slug: "invoice-generator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Generate professional invoices online for free",
    longDescription: "Create professional invoices with your company details, client information, line items, taxes, and discounts, then export them as polished PDF files. Whether you are a freelancer, a shopkeeper, or a small business owner, this tool helps you bill customers quickly, track every charge, and share clean, printable invoices that look like they were made by a dedicated accounting team. No software to install and no signup required, so you can send your first invoice in minutes.",
    instructions: [
      "Enter your company details such as business name, address, and GSTIN",
      "Add your client's name and contact information",
      "Add line items with quantities, rates, taxes, and any discounts",
      "Review the invoice preview to check totals and details",
      "Download the invoice as a PDF to print or email",
    ],
    processingType: "browser",
    seoTitle: "Invoice Generator – Free Online Create Invoices | ToolPilot",
    seoDescription: "Generate professional invoices online for free. Add company details, items, taxes, and discounts. Download as PDF with no signup.",
    keywords: ["invoice generator", "create invoice", "free invoice", "invoice template"],
    icon: "Building2",
    featured: true,
    popular: true,
    faqs: [
      { question: "Can I add my company logo?", answer: "Yes, you can upload your company logo to include on the invoice and make it look more professional." },
      { question: "What format can I download?", answer: "You can download invoices as PDF files that are ready for printing or emailing directly to clients." },
      { question: "Can I add taxes and discounts?", answer: "Yes, you can apply taxes and discounts to individual line items or the whole invoice before downloading." },
      { question: "Is this free to use?", answer: "Yes, the invoice generator is completely free. There is no signup, no watermark, and no limit on the number of invoices you can create." },
      { question: "Who can use this invoice generator?", answer: "Freelancers, shopkeepers, and small business owners who need a quick way to bill clients without buying expensive accounting software." },
    ],
    relatedTools: ["quotation-generator", "gst-invoice-generator", "profit-margin-calculator"],
  },
  {
    name: "Quotation Generator",
    slug: "quotation-generator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Generate professional quotations and estimates",
    longDescription: "Create detailed quotations with itemized pricing, custom terms and conditions, and a professional layout that closes deals faster. Whether you are a freelancer quoting a project, a shopkeeper pricing an order, or a small business responding to a tender, this tool helps you send clear, organized price quotes that give clients confidence and cut down on back-and-forth emails. Everything runs in your browser and exports to PDF at the click of a button.",
    instructions: [
      "Enter your business name and contact details",
      "Add the client's name and contact information",
      "Add line items with descriptions, quantities, and rates",
      "Write your payment terms and conditions",
      "Download the quotation as a PDF to send to your client",
    ],
    processingType: "browser",
    seoTitle: "Quotation Generator – Free Online Quote Maker | ToolPilot",
    seoDescription: "Generate professional quotations online for free. Itemized pricing, custom terms. Download as PDF without signup.",
    keywords: ["quotation generator", "quote maker", "estimate generator", "price quote"],
    icon: "Building2",
    faqs: [
      { question: "Can I add terms and conditions?", answer: "Yes, you can write custom terms and conditions, such as payment deadlines and validity period, for each quotation." },
      { question: "Can I itemize the pricing?", answer: "Yes, you can add multiple line items with quantities and rates, and the tool totals everything for you automatically." },
      { question: "Who normally uses a quotation generator?", answer: "Freelancers, contractors, shopkeepers, and small businesses that need to send professional price quotes to customers." },
      { question: "Is this free and private?", answer: "Yes, it is completely free to use and works entirely in your browser, so your quotation data never leaves your device." },
    ],
    relatedTools: ["invoice-generator", "gst-invoice-generator", "profit-margin-calculator"],
  },
  {
    name: "GST Invoice Generator",
    slug: "gst-invoice-generator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Generate GST-compliant invoices with tax breakup",
    longDescription: "Create GST-compliant invoices with a proper CGST, SGST, or IGST breakup and all the fields required for a valid tax invoice. The tool includes GSTIN, HSN/SAC codes, supplier and recipient details, and itemized entries, making it useful for small businesses, shopkeepers, and freelancers who need to bill registered customers correctly and keep clean records for return filing. Your invoice downloads as a neat PDF ready to print or share.",
    instructions: [
      "Enter your GSTIN and business details",
      "Add the buyer's GSTIN and recipient details",
      "Add items with HSN/SAC codes and applicable GST rates",
      "Verify the CGST, SGST, or IGST breakup in the summary",
      "Download the GST invoice as a PDF to print or email",
    ],
    processingType: "browser",
    seoTitle: "GST Invoice Generator – Free Online GST Invoice Tool | ToolPilot",
    seoDescription: "Generate GST invoices online for free. CGST/SGST/IGST breakup, GSTIN and HSN/SAC codes. Download as PDF.",
    keywords: ["gst invoice generator", "gst invoice", "tax invoice", "gst bill"],
    icon: "Building2",
    faqs: [
      { question: "What fields are included?", answer: "GSTIN, HSN/SAC codes, CGST/SGST/IGST breakup, supplier and recipient details, itemized list, and totals are all covered." },
      { question: "Can I use this for intra-state and inter-state sales?", answer: "Yes, the tool supports CGST and SGST for intra-state sales and IGST for inter-state sales." },
      { question: "Is the invoice valid for GST compliance?", answer: "The invoice includes the standard fields expected on a tax invoice, but it is always best to verify against current rules with your tax advisor." },
      { question: "Who is this tool for?", answer: "Small businesses, shopkeepers, and freelancers who need to issue GST-compliant invoices without buying expensive accounting software." },
    ],
    relatedTools: ["invoice-generator", "gst-calculator", "quotation-generator"],
  },
  {
    name: "Profit Margin Calculator",
    slug: "profit-margin-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate profit margin and markup percentage",
    longDescription: "Calculate your gross profit margin, net profit margin, and markup percentage instantly from your selling price and costs, with a clear breakdown of revenue, cost, and profit. Whether you are a shopkeeper pricing goods, a freelancer setting project rates, or a small business owner reviewing product profitability, this tool helps you price smarter and make sure every sale actually leaves you with a healthy profit. Get instant answers with no guesswork.",
    instructions: [
      "Enter your selling price for the product or service",
      "Enter your cost price or total costs",
      "Enter any other expenses if you want to include them",
      "Choose between gross or net margin calculation",
      "View your profit amount, margin, and markup percentage",
    ],
    processingType: "browser",
    seoTitle: "Profit Margin Calculator – Free Online Margin Calculator | ToolPilot",
    seoDescription: "Calculate profit margin online for free. Gross and net margin, markup percentage, and profit breakdown. Instant results.",
    keywords: ["profit margin calculator", "margin calculator", "markup calculator", "profit percentage"],
    icon: "Building2",
    faqs: [
      { question: "What is the difference between margin and markup?", answer: "Margin is profit expressed as a percentage of the selling price, while markup is profit expressed as a percentage of the cost price." },
      { question: "How do I know if my margin is healthy?", answer: "A healthy margin depends on your industry, but consistently positive margins that cover your overheads and leave room to grow are a good target." },
      { question: "Can I use this for services as well as products?", answer: "Yes, as long as you enter your selling price and costs, the calculator works for both physical goods and services like freelancing projects." },
      { question: "Is this free to use?", answer: "Yes, this profit margin calculator is completely free with no signup, and calculations happen instantly in your browser." },
    ],
    relatedTools: ["markup-calculator", "break-even-calculator", "roi-calculator"],
  },
  {
    name: "Markup Calculator",
    slug: "markup-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate markup percentage on cost price",
    longDescription: "Determine the selling price you should charge by applying your desired markup percentage over cost, and see your profit per unit at the same time. This is a handy tool for shopkeepers and small business owners who buy goods and want a clear, consistent pricing strategy that guarantees a profit on every item. Enter your cost and markup, and the calculator gives you the exact selling price in seconds.",
    instructions: [
      "Enter the cost price of the item",
      "Enter your desired markup percentage",
      "Optionally add other costs like delivery or packaging",
      "Review the calculated selling price",
      "Note the profit you will earn per unit",
    ],
    processingType: "browser",
    seoTitle: "Markup Calculator – Free Online Calculate Markup | ToolPilot",
    seoDescription: "Calculate markup percentage online for free. Determine your selling price from cost and see profit per unit. Instant results.",
    keywords: ["markup calculator", "cost markup", "pricing calculator", "selling price calculator"],
    icon: "Building2",
    faqs: [
      { question: "How do I calculate markup?", answer: "Selling Price = Cost x (1 + Markup/100). For example, a 50% markup on a $100 cost gives a $150 selling price." },
      { question: "What markup should I use?", answer: "It varies by industry, but many small retailers aim for a markup that covers overheads, taxes, and leaves room for profit." },
      { question: "Can I include other costs?", answer: "Yes, you can add extra costs like delivery, packaging, or commissions so your selling price reflects true expenses." },
      { question: "Is this free to use?", answer: "Yes, this markup calculator is completely free and works instantly in your browser with no signup required." },
    ],
    relatedTools: ["profit-margin-calculator", "break-even-calculator", "discount-calculator"],
  },
  {
    name: "Break-Even Calculator",
    slug: "break-even-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate break-even point for your business",
    longDescription: "Find the exact break-even point where your total revenue equals your total costs, and see how many units you need to sell before you start making a profit. This is a must-have planning tool for shopkeepers, freelancers, and small business owners launching a product or service, because it shows at a glance whether a pricing plan is realistic. Enter your costs and price, and the calculator tells you the sales target to aim for.",
    instructions: [
      "Enter your total fixed costs for the period",
      "Enter the variable cost per unit",
      "Enter the selling price per unit",
      "Review the calculated break-even point in units",
      "Check the sales revenue needed to break even",
    ],
    processingType: "browser",
    seoTitle: "Break-Even Calculator – Free Online Break-Even Analysis | ToolPilot",
    seoDescription: "Calculate break-even point online for free. Find how many units to sell to break even and start profiting.",
    keywords: ["break even calculator", "break even analysis", "break even point", "business calculator"],
    icon: "Building2",
    faqs: [
      { question: "What is break-even?", answer: "Break-even is the point where total revenue equals total costs, meaning you have made zero profit and zero loss." },
      { question: "Why is the break-even point important?", answer: "It tells you how many units or how much revenue you need to cover your costs, which is essential before launching a new product or service." },
      { question: "What costs should I include?", answer: "Include your fixed costs like rent and salaries, plus the variable cost of producing or buying each unit." },
      { question: "Is this free to use?", answer: "Yes, this break-even calculator is completely free and gives instant results in your browser with no signup." },
    ],
    relatedTools: ["profit-margin-calculator", "project-cost-calculator", "roi-calculator"],
  },
  {
    name: "Project Cost Calculator",
    slug: "project-cost-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Estimate total project costs with breakdown",
    longDescription: "Calculate the total cost of any project by adding up labor, materials, equipment, overhead, and contingency, with a clear breakdown of where every rupee goes. Whether you are a contractor quoting a job, a freelancer scoping a delivery, or a small business planning an upcoming project, this tool helps you build an accurate budget so you avoid underpricing and surprise expenses. Adjust the numbers and see the total update instantly.",
    instructions: [
      "Add your labor costs and number of workers",
      "Add materials and equipment costs",
      "Add overhead costs like permits and utilities",
      "Set a contingency percentage for unexpected expenses",
      "View the detailed cost breakdown and total project cost",
    ],
    processingType: "browser",
    seoTitle: "Project Cost Calculator – Free Online Estimate Project Costs | ToolPilot",
    seoDescription: "Estimate project costs online for free. Labor, materials, equipment, overhead and contingency breakdown. Budget planner.",
    keywords: ["project cost calculator", "project estimate", "project budget", "cost estimator"],
    icon: "Building2",
    faqs: [
      { question: "Can I add contingency costs?", answer: "Yes, you can add a contingency percentage to cover unexpected expenses and avoid going over budget." },
      { question: "What categories can I include?", answer: "You can include labor, materials, equipment, overhead, and contingency to build a complete project budget." },
      { question: "Is this useful for freelancers too?", answer: "Yes, freelancers and consultants can use it to cost out a project accurately before quoting a client." },
      { question: "Is this free to use?", answer: "Yes, the project cost calculator is completely free and gives instant totals in your browser." },
    ],
    relatedTools: ["construction-cost-calculator", "boq-calculator", "break-even-calculator"],
  },
  {
    name: "Construction Cost Calculator",
    slug: "construction-cost-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Estimate construction costs per square foot",
    longDescription: "Estimate your construction budget by entering the building area, material type, and quality level, and get a cost per square foot along with a total estimate. This gives homeowners and small contractors a realistic starting point before hiring an architect or comparing building quotes, especially for house construction planning. Adjust the area or quality settings and the estimate updates instantly to help you plan your finances.",
    instructions: [
      "Enter the total construction area in square feet",
      "Select the material type and construction quality",
      "Choose your location tier if prompted",
      "Review the estimated cost per square foot",
      "View the total construction cost estimate",
    ],
    processingType: "browser",
    seoTitle: "Construction Cost Calculator – Free Online Building Cost Estimator | ToolPilot",
    seoDescription: "Estimate construction costs online for free. Per square foot calculation with material and quality options.",
    keywords: ["construction cost calculator", "building cost estimator", "house construction cost", "sq ft cost"],
    icon: "Building2",
    faqs: [
      { question: "What factors affect construction cost?", answer: "Area, material type, location, labor rates, design complexity, and finishing level all affect the total construction cost." },
      { question: "Is this estimate accurate?", answer: "It is a helpful planning estimate based on your inputs, but actual costs vary by location and contractor, so treat it as a starting point." },
      { question: "What is cost per square foot?", answer: "It is the average construction cost per square foot of built area, useful for quickly comparing different property sizes." },
      { question: "Who can use this tool?", answer: "Homeowners planning a house build and small contractors preparing early cost estimates for clients." },
    ],
    relatedTools: ["project-cost-calculator", "boq-calculator", "roi-calculator"],
  },
  {
    name: "BOQ Calculator",
    slug: "boq-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Create and calculate Bill of Quantities",
    longDescription: "Create a detailed Bill of Quantities (BOQ) by entering itemized materials, quantities, and unit rates, and the tool calculates item and total costs for you automatically. This is a practical tool for contractors and small construction businesses who need to prepare a clear, itemized cost sheet for a project before inviting quotes or sharing it with a client. Add as many line items as you need and export a clean breakdown ready for use.",
    instructions: [
      "Add a new line item with a description",
      "Enter the quantity and unit of measurement",
      "Enter the unit rate for each item",
      "Repeat for every material or work item in the project",
      "Review the itemized and total costs",
    ],
    processingType: "browser",
    seoTitle: "BOQ Calculator – Free Online Bill of Quantities Tool | ToolPilot",
    seoDescription: "Create BOQ online for free. Itemized materials, quantities, and rates with automatic total cost calculation.",
    keywords: ["boq calculator", "bill of quantities", "boq format", "construction boq"],
    icon: "Building2",
    faqs: [
      { question: "What is a BOQ?", answer: "A Bill of Quantities (BOQ) is a document that lists all the materials, labor, and costs required for a construction project." },
      { question: "Who needs a BOQ?", answer: "Contractors, builders, and site estimators use a BOQ to define project scope, invite quotes, and track costs." },
      { question: "Can I add many line items?", answer: "Yes, you can add as many line items as your project needs, each with its own quantity and unit rate." },
      { question: "Is this free to use?", answer: "Yes, the BOQ calculator is completely free and calculates your totals instantly in the browser." },
    ],
    relatedTools: ["construction-cost-calculator", "project-cost-calculator", "invoice-generator"],
  },
  {
    name: "ROI Calculator",
    slug: "roi-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate Return on Investment",
    longDescription: "Calculate the return on investment (ROI) percentage for any investment and see your profit or loss and return rate, with support for both simple and annualized ROI. Whether you are a small business owner evaluating a new purchase, a freelancer deciding on equipment, or anyone comparing where to put money, this tool turns your numbers into a clear percentage you can compare across opportunities. Enter the investment and return to see the result instantly.",
    instructions: [
      "Enter your total investment amount",
      "Enter the final return or selling value",
      "Choose between simple or annualized ROI",
      "Enter the number of years if using annualized ROI",
      "View your ROI percentage and profit or loss",
    ],
    processingType: "browser",
    seoTitle: "ROI Calculator – Free Online Return on Investment Calculator | ToolPilot",
    seoDescription: "Calculate ROI online for free. Return on investment percentage, profit, simple and annualized returns.",
    keywords: ["roi calculator", "return on investment", "investment return", "roi formula"],
    icon: "Building2",
    faqs: [
      { question: "What is the ROI formula?", answer: "ROI = ((Return - Investment) / Investment) x 100. For annualized ROI, the result is adjusted for the number of years." },
      { question: "What is the difference between simple and annualized ROI?", answer: "Simple ROI shows the total return over the whole period, while annualized ROI shows the average yearly return, useful for comparing investments held for different lengths." },
      { question: "Can I calculate a negative ROI?", answer: "Yes, if your return is less than your investment, the calculator shows a negative ROI to indicate a loss." },
      { question: "Who can use this calculator?", answer: "Small business owners, freelancers, and individual investors comparing returns on different purchases or opportunities." },
    ],
    relatedTools: ["profit-margin-calculator", "break-even-calculator", "compound-interest-calculator"],
  },
];
