import { ToolConfig } from "@/types/tool";

export const aiTools: ToolConfig[] = [
  {
    name: "AI Text Humanizer",
    slug: "ai-text-humanizer",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Make AI-generated text sound natural and human",
    longDescription: "Transform AI-generated content into natural, human-sounding text that reads as if a person wrote it. Use it to remove robotic phrasing from essays, emails, blog posts, or social media captions so your writing feels more engaging and authentic without changing the original meaning.",
    instructions: [
      "Paste AI-generated text into the input box",
      "Review the suggested changes for wording and tone",
      "Click Humanize to rewrite the text naturally",
      "Preview the humanized output side by side",
      "Copy the humanized text to use in your document",
    ],
    processingType: "ai",
    seoTitle: "AI Text Humanizer – Free Online Make AI Text Human | ToolPilot",
    seoDescription: "Humanize AI-generated text online for free. Make AI content sound natural and authentic.",
    keywords: ["ai humanizer", "text humanizer", "ai to human text", "make ai text natural"],
    icon: "Sparkles",
    popular: true,
    faqs: [
      { question: "How does text humanization work?", answer: "The tool restructures sentences, varies vocabulary, and adds natural phrasing while preserving the original meaning." },
      { question: "Does it change the meaning?", answer: "No, the core message and meaning are preserved while the writing style becomes more natural." },
      { question: "Can it be used for school or work writing?", answer: "Yes, it can help essays, assignments, emails, and reports sound more natural. Review the result yourself and use it responsibly according to your school or workplace rules." },
      { question: "Is the tool free to use?", answer: "Yes, the AI text humanizer is free to use online, so you can improve as much writing as you need without any cost." },
    ],
    relatedTools: ["ai-text-summarizer", "ai-paraphraser", "ai-email-generator"],
  },
  {
    name: "AI Text Summarizer",
    slug: "ai-text-summarizer",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Summarize long text into key points",
    longDescription: "Condense long articles, documents, reports, or notes into concise, easy-to-read summaries that capture the most important points. Use it to review research papers, news articles, or meeting notes quickly and save time when you need the key details without reading everything.",
    instructions: [
      "Paste the text you want to summarize into the input box",
      "Choose the summary length you prefer",
      "Click Summarize to extract the key points",
      "Review the generated summary for accuracy",
      "Copy or download your summary",
    ],
    processingType: "ai",
    seoTitle: "AI Text Summarizer – Free Online Summarize Text | ToolPilot",
    seoDescription: "Summarize text online for free. AI-powered text summarizer. Get key points instantly.",
    keywords: ["text summarizer", "ai summarizer", "summarize text", "text summarization"],
    icon: "Sparkles",
    faqs: [
      { question: "How long can the input text be?", answer: "You can summarize text up to 10,000 words at once, which covers most articles, chapters, and reports." },
      { question: "Will the summary keep the main points?", answer: "Yes, the summary highlights the key ideas and important details of the original text while removing less essential content." },
      { question: "Can I choose how short or long the summary is?", answer: "Yes, you can pick a summary length, so you can get anything from a quick overview to a more detailed recap." },
      { question: "Is the text summarizer free to use?", answer: "Yes, the AI text summarizer is free to use online, so you can summarize as many documents as you need without paying." },
    ],
    relatedTools: ["ai-text-humanizer", "ai-paraphraser", "word-counter"],
  },
  {
    name: "AI Paraphraser",
    slug: "ai-paraphraser",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Rewrite text while preserving meaning",
    longDescription: "Rewrite content in different words while keeping the original meaning, tone, and message intact. Use it to improve clarity, avoid repetition, or rephrase academic papers, articles, and social media posts for a fresher and more natural read.",
    instructions: [
      "Paste the text you want to paraphrase into the input box",
      "Select the writing style you need, such as formal, casual, or creative",
      "Click Paraphrase to rewrite the text",
      "Compare the rewritten version with the original",
      "Copy the paraphrased text for your document",
    ],
    processingType: "ai",
    seoTitle: "AI Paraphraser – Free Online Rewrite Text | ToolPilot",
    seoDescription: "Paraphrase text online for free. AI-powered rewriting tool. Multiple styles available.",
    keywords: ["paraphraser", "ai paraphraser", "rewrite text", "text rewriter"],
    icon: "Sparkles",
    faqs: [
      { question: "What styles are available?", answer: "Formal, casual, creative, academic, and professional writing styles are available, so you can match the tone to your audience." },
      { question: "Does paraphrasing preserve the meaning?", answer: "Yes, the tool keeps the original meaning and message while changing the choice of words and sentence structure." },
      { question: "Can I paraphrase long pieces of text?", answer: "Yes, you can paste longer passages and paragraphs into the tool and paraphrase them in one go." },
      { question: "Is the paraphraser free to use?", answer: "Yes, the AI paraphraser is free to use online, so you can rewrite as much text as you need without paying." },
    ],
    relatedTools: ["ai-text-humanizer", "ai-text-summarizer", "ai-email-generator"],
  },
  {
    name: "AI Cover Letter Generator",
    slug: "ai-cover-letter-generator",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Generate tailored cover letters with AI",
    longDescription: "Create personalized cover letters for any job application by tailoring the content to your resume and the target job description. Use it to prepare a professional, ready-to-send cover letter quickly so you can apply for more roles without staring at a blank page.",
    instructions: [
      "Upload your resume so the AI can use your experience",
      "Paste the job description for the role you are applying for",
      "Add any extra details, such as a preferred tone or focus area",
      "Generate your tailored cover letter",
      "Download or copy the cover letter to submit with your application",
    ],
    processingType: "ai",
    seoTitle: "AI Cover Letter Generator – Free Online Cover Letter Maker | ToolPilot",
    seoDescription: "Generate AI cover letters online for free. Tailored for each job application. Professional and unique.",
    keywords: ["ai cover letter", "cover letter generator", "cover letter maker", "job cover letter"],
    icon: "Sparkles",
    faqs: [
      { question: "Is each cover letter unique?", answer: "Yes, each cover letter is uniquely generated based on your specific resume and the target job, so it is tailored to the role." },
      { question: "What information do I need to provide?", answer: "You need your resume and the job description. Adding a few extra details about the role or tone can help the letter feel more personal." },
      { question: "Is the cover letter generator free?", answer: "Yes, the AI cover letter generator is free to use online, so you can create cover letters for as many applications as you need." },
      { question: "Can I edit the cover letter after generating it?", answer: "Yes, after the cover letter is generated you can review and edit it before downloading, so you can personalise it further." },
    ],
    relatedTools: ["ai-resume-summary-generator", "ai-email-generator", "resume-builder"],
  },
  {
    name: "AI Resume Summary Generator",
    slug: "ai-resume-summary-generator",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Generate a professional resume summary",
    longDescription: "Create a compelling resume summary or objective statement that highlights your experience, skills, and career goals. Use it to craft a strong opening paragraph for job applications and LinkedIn so recruiters grasp your strengths at a glance without overthinking the wording.",
    instructions: [
      "Enter your job role and years of experience",
      "Add your key skills and main achievements",
      "Choose between a professional summary or an objective statement",
      "Generate your resume summary",
      "Copy the summary into your resume or LinkedIn profile",
    ],
    processingType: "ai",
    seoTitle: "AI Resume Summary Generator – Free Online Resume Summary | ToolPilot",
    seoDescription: "Generate resume summaries online for free. AI-powered professional summary for your resume.",
    keywords: ["resume summary generator", "professional summary", "resume objective", "career summary"],
    icon: "Sparkles",
    faqs: [
      { question: "How long should a resume summary be?", answer: "Around 2 to 4 sentences or 50 to 100 words is ideal. It should highlight your key qualifications and career goals." },
      { question: "What details should I include?", answer: "Your job role, years of experience, core skills, and a couple of key achievements or strengths that match the job you want." },
      { question: "Can I use it for my LinkedIn profile?", answer: "Yes, the same summary works well as the about section on your LinkedIn profile as a quick professional introduction." },
      { question: "Is the resume summary generator free?", answer: "Yes, it is free to use online, so you can generate and tweak your summary as often as you like without paying." },
    ],
    relatedTools: ["ai-cover-letter-generator", "resume-builder", "ai-paraphraser"],
  },
  {
    name: "AI Email Generator",
    slug: "ai-email-generator",
    category: "AI Tools",
    categorySlug: "ai",
    description: "Generate professional emails for any occasion",
    longDescription: "Write professional emails for business communication, follow-ups, cold outreach, and everyday messages by choosing a purpose and tone. Use it to draft clear, well-worded emails for work, applications, or personal requests when you are unsure how to phrase what you want to say.",
    instructions: [
      "Select the email type and tone you want, such as formal or friendly",
      "Add the context and key details for your message",
      "Generate the email draft",
      "Review and edit the draft to add your personal touch",
      "Copy the email into your mailbox and send it",
    ],
    processingType: "ai",
    seoTitle: "AI Email Generator – Free Online Professional Email Writer | ToolPilot",
    seoDescription: "Generate professional emails online for free. AI-powered email writer for business and personal use.",
    keywords: ["email generator", "ai email writer", "professional email", "email template"],
    icon: "Sparkles",
    faqs: [
      { question: "What email types are supported?", answer: "Business inquiry, follow-up, cold outreach, thank you, apology, resignation, and custom emails are all supported." },
      { question: "Can I choose the tone of the email?", answer: "Yes, you can choose a tone such as formal, casual, or friendly so the email matches your situation and audience." },
      { question: "Can I edit the email after it is generated?", answer: "Yes, after generating a draft you can review, edit, and personalise it before sending, so it sounds like you." },
      { question: "Is the email generator free to use?", answer: "Yes, the AI email generator is free to use online, so you can draft as many emails as you need without paying." },
    ],
    relatedTools: ["ai-text-humanizer", "ai-paraphraser", "ai-text-summarizer"],
  },
];
