import { ToolConfig } from "@/types/tool";

export const pdfTools: ToolConfig[] = [
  {
    name: "PDF to Word",
    slug: "pdf-to-word",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert PDF files to editable Word documents online for free",
    longDescription: "Transform your PDF files into fully editable Word (.docx) documents online for free. Our PDF to Word converter accurately extracts text while preserving images, fonts, tables, and page layout, so you can edit contracts, reports, resumes, and essays without retyping a single word. Whether you need an editable copy for a job application, a university assignment, or a business document, this converter delivers clean Microsoft Word output in seconds. No signup, no watermarks, and your documents are deleted automatically after conversion.",
    instructions: [
      "Upload your PDF file (drag and drop or browse)",
      "Wait a few seconds while our converter extracts text and layout",
      "Verify the converted Word document in the preview",
      "Download the .docx file",
      "Open and edit it in Microsoft Word or Google Docs",
    ],
    processingType: "server",
    seoTitle: "PDF to Word Converter – Free Online PDF to DOCX Tool | ToolPilot",
    seoDescription: "Convert PDF to Word online for free. Fast, accurate PDF to DOCX converter that preserves formatting. No signup required.",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "pdf converter"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "Is the PDF to Word converter free?", answer: "Yes, converting PDF to Word is 100% free. There are no hidden charges, no watermarks, and no account is required." },
      { question: "Is my PDF file safe?", answer: "Yes, files are processed securely and automatically deleted after conversion. We never store or share your documents." },
      { question: "Does it preserve formatting?", answer: "Our converter preserves text, images, fonts, tables, and basic layout from the original PDF so your document stays readable." },
      { question: "Can I convert large PDF files?", answer: "Yes, you can import large documents. Keep in mind that very large files may take a little longer to convert." },
      { question: "Will I get a DOCX or DOC file?", answer: "You get a modern .docx file that opens in Microsoft Word, Google Docs, and LibreOffice." },
    ],
    relatedTools: ["word-to-pdf", "pdf-merger", "pdf-splitter"],
  },
  {
    name: "Word to PDF",
    slug: "word-to-pdf",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert Word documents to PDF online for free",
    longDescription: "Convert your Word documents (.doc, .docx) to PDF format instantly. Perfect for sharing documents that look the same on any device.",
    instructions: ["Upload your Word document", "Wait for conversion", "Download your PDF file"],
    processingType: "server",
    seoTitle: "Word to PDF Converter – Free Online DOCX to PDF Tool | ToolPilot",
    seoDescription: "Convert Word to PDF online for free. Fast DOCX to PDF converter. Preserve formatting. No signup required.",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "What Word formats are supported?", answer: "We support .doc and .docx formats." },
    ],
    relatedTools: ["pdf-to-word", "jpg-to-pdf", "pdf-merger"],
  },
  {
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert JPG images to PDF online for free",
    longDescription: "Turn your JPG images into PDF documents. Merge multiple images into a single PDF. Perfect for creating photo albums, scanned documents, and more.",
    instructions: ["Upload JPG image(s)", "Arrange order if multiple", "Click Convert", "Download PDF"],
    processingType: "browser",
    seoTitle: "JPG to PDF Converter – Free Online JPG to PDF Tool | ToolPilot",
    seoDescription: "Convert JPG to PDF online for free. Merge multiple images into one PDF. Fast, simple, and private. No signup required.",
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf", "photo to pdf"],
    icon: "FileText",
    featured: true,
    popular: true,
    faqs: [
      { question: "Can I merge multiple JPGs into one PDF?", answer: "Yes, upload multiple images and they will be combined into a single PDF in the order you specify." },
      { question: "Is the conversion done in my browser?", answer: "Yes, JPG to PDF conversion happens entirely in your browser. Your images never leave your device." },
    ],
    relatedTools: ["pdf-to-jpg", "png-to-pdf", "image-compressor"],
  },
  {
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert PDF pages to JPG images online for free",
    longDescription: "Extract images from PDF or convert entire PDF pages to high-quality JPG images. Great for sharing individual pages as images.",
    instructions: ["Upload your PDF", "Select page range", "Click Convert", "Download JPG images"],
    processingType: "server",
    seoTitle: "PDF to JPG Converter – Free Online PDF to Image Tool | ToolPilot",
    seoDescription: "Convert PDF to JPG online for free. Extract pages as high-quality images. Fast and accurate. No signup required.",
    keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpg", "pdf to png"],
    icon: "FileText",
    faqs: [
      { question: "What quality will the JPG images be?", answer: "We extract images at the highest quality possible from the original PDF." },
    ],
    relatedTools: ["jpg-to-pdf", "pdf-to-word", "image-compressor"],
  },
  {
    name: "PDF Compressor",
    slug: "pdf-compressor",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Compress PDF files to reduce size online for free",
    longDescription: "Reduce the size of your PDF files instantly without visibly losing quality. Whether you need to fit a PDF under an email attachment limit, upload it to a website, or share it on WhatsApp, our online PDF compressor uses smart compression to shrink documents by up to 80% while keeping text razor sharp and images clear. Choose between low, medium, and high compression levels to balance file size against quality, and see the exact new size before you download. Everything happens securely in your browser, so your files never leave your device.",
    instructions: [
      "Upload your PDF file (drag and drop or browse)",
      "Choose a compression level: low, medium, or high",
      "Click Compress and wait for the file to be optimized",
      "Check the new file size shown in the preview",
      "Download your smaller PDF",
    ],
    processingType: "browser",
    seoTitle: "PDF Compressor – Free Online Reduce PDF Size | ToolPilot",
    seoDescription: "Compress PDF files online for free. Reduce PDF size without losing quality. Fast, easy, and private.",
    keywords: ["pdf compressor", "reduce pdf size", "compress pdf", "shrink pdf"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "Will compression reduce quality?", answer: "Our compression uses smart algorithms to minimize quality loss while significantly reducing file size. Text stays sharp and images remain clear." },
      { question: "How much smaller will my PDF get?", answer: "Most PDFs shrink by 40-80% depending on the content and the compression level you choose. You can preview the new size before downloading." },
      { question: "Is this the best way to fit a PDF in an email?", answer: "Yes. Most email providers allow attachments up to 25 MB, and this compressor easily brings documents under that limit." },
      { question: "Is my PDF private?", answer: "Yes. Compression happens entirely in your browser, so your file never leaves your device." },
    ],
    relatedTools: ["pdf-merger", "pdf-splitter", "image-compressor"],
  },
  {
    name: "PDF Merger",
    slug: "pdf-merger",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Merge multiple PDF files into one online for free",
    longDescription: "Combine multiple PDF files into one single document with just a few clicks. Upload two or more files, drag and drop them into the exact order you want, and merge them into a single PDF — perfect for combining reports, invoices, scanned pages, or project files before sending them to a client or submitting them for approval. The merged document keeps the formatting and quality of the originals, and no watermark is ever added. All processing happens in your browser, which makes it fast, free, and completely private.",
    instructions: [
      "Upload two or more PDF files",
      "Drag and drop the files to set the correct order",
      "Optionally rotate or remove any page",
      "Click Merge PDFs",
      "Download your combined file",
    ],
    processingType: "browser",
    seoTitle: "PDF Merger – Free Online Merge PDF Files | ToolPilot",
    seoDescription: "Merge PDF files online for free. Combine multiple PDFs into one. Fast, easy, and secure. No signup required.",
    keywords: ["pdf merger", "merge pdf", "combine pdf", "join pdf"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "How many PDFs can I merge?", answer: "You can merge up to 20 PDF files at once, as long as they fit in your browser." },
      { question: "Can I change the order of pages?", answer: "Yes. Drag and drop any file to reorder it, and rotate or remove individual pages before merging." },
      { question: "Does merging reduce quality?", answer: "No. The merged file keeps the full quality and formatting of the original documents, and no watermark is added." },
      { question: "Are my files safe and private?", answer: "Yes. Merging happens entirely in your browser, so your documents never leave your device." },
    ],
    relatedTools: ["pdf-splitter", "pdf-compressor", "pdf-to-word"],
  },
  {
    name: "PDF Splitter",
    slug: "pdf-splitter",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Split PDF into multiple files online for free",
    longDescription: "Extract specific pages or split a PDF into multiple files. Perfect for separating chapters, extracting signatures, or sharing specific pages.",
    instructions: ["Upload your PDF", "Select pages to extract", "Click Split", "Download split PDF files"],
    processingType: "browser",
    seoTitle: "PDF Splitter – Free Online Split PDF Pages | ToolPilot",
    seoDescription: "Split PDF files online for free. Extract specific pages or divide into multiple PDFs. Fast and private.",
    keywords: ["pdf splitter", "split pdf", "extract pdf pages", "separate pdf"],
    icon: "FileText",
    faqs: [
      { question: "Can I split by page range?", answer: "Yes, you can specify exact page ranges to extract." },
    ],
    relatedTools: ["pdf-merger", "pdf-rotator", "pdf-page-extractor"],
  },
  {
    name: "PDF Page Extractor",
    slug: "pdf-page-extractor",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Extract specific pages from a PDF file online for free",
    longDescription: "Select and extract specific pages from a PDF document. Create a new PDF with only the pages you need.",
    instructions: ["Upload your PDF", "Preview all pages", "Select pages to extract", "Download extracted PDF"],
    processingType: "browser",
    seoTitle: "PDF Page Extractor – Free Online Extract PDF Pages | ToolPilot",
    seoDescription: "Extract specific pages from PDF files online for free. Select and download only the pages you need.",
    keywords: ["pdf page extractor", "extract pdf pages", "select pdf pages"],
    icon: "FileText",
    faqs: [
      { question: "Can I preview pages before extracting?", answer: "Yes, you can see thumbnails of all pages and select the ones you want." },
    ],
    relatedTools: ["pdf-splitter", "pdf-merger", "pdf-to-jpg"],
  },
  {
    name: "PDF Rotator",
    slug: "pdf-rotator",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Rotate PDF pages online for free",
    longDescription: "Rotate individual pages or all pages in a PDF document. Fix orientation issues from scanned documents.",
    instructions: ["Upload your PDF", "Select pages to rotate", "Choose rotation angle", "Download rotated PDF"],
    processingType: "browser",
    seoTitle: "PDF Rotator – Free Online Rotate PDF Pages | ToolPilot",
    seoDescription: "Rotate PDF pages online for free. Fix page orientation instantly. Fast, easy, and private.",
    keywords: ["pdf rotator", "rotate pdf", "flip pdf pages", "pdf orientation"],
    icon: "FileText",
    faqs: [
      { question: "What rotation angles are available?", answer: "You can rotate pages by 90, 180, or 270 degrees." },
    ],
    relatedTools: ["pdf-splitter", "pdf-merger", "pdf-to-jpg"],
  },
];
