import { ToolConfig } from "@/types/tool";

export const pdfTools: ToolConfig[] = [
  {
    name: "PDF to Word",
    slug: "pdf-to-word",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert PDF files to editable Word documents online for free",
    longDescription: "Transform your PDF files into fully editable Word (.docx) documents online for free. Our PDF to Word converter accurately extracts text while preserving images, fonts, tables, and page layout, so you can edit contracts, reports, resumes, and essays without retyping a single word. Whether you need an editable copy for a job application, a university assignment, or a business document, this converter delivers clean Microsoft Word output in seconds. No signup, no watermarks, and your documents are deleted automatically after conversion.",
    instructions: [
      "Upload your PDF file (drag and drop or browse)",
      "Wait a few seconds while our converter extracts text and layout",
      "Verify the converted Word document in the preview",
      "Download the .docx file",
      "Open and edit it in Microsoft Word or Google Docs",
    ],
    processingType: "server",
    seoTitle: "PDF to Word Converter – Free Online PDF to DOCX Tool | ToolPilot",
    seoDescription: "Convert PDF to Word online for free. Fast, accurate PDF to DOCX converter that preserves formatting. No signup required.",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "pdf converter"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "Is the PDF to Word converter free?", answer: "Yes, converting PDF to Word is 100% free. There are no hidden charges, no watermarks, and no account is required." },
      { question: "Is my PDF file safe?", answer: "Yes, files are processed securely and automatically deleted after conversion. We never store or share your documents." },
      { question: "Does it preserve formatting?", answer: "Our converter preserves text, images, fonts, tables, and basic layout from the original PDF so your document stays readable." },
      { question: "Can I convert large PDF files?", answer: "Yes, you can import large documents. Keep in mind that very large files may take a little longer to convert." },
      { question: "Will I get a DOCX or DOC file?", answer: "You get a modern .docx file that opens in Microsoft Word, Google Docs, and LibreOffice." },
    ],
    relatedTools: ["word-to-pdf", "pdf-merger", "pdf-splitter"],
  },
  {
    name: "Word to PDF",
    slug: "word-to-pdf",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert Word documents to PDF online for free",
    longDescription: "Convert your Word documents (.doc and .docx) into polished, ready-to-share PDF files without installing any software. Whether you are submitting a resume for a job application, sending an invoice to a client, or sharing lecture notes with classmates, converting to PDF locks in the fonts, layout, and images so your document looks exactly the same on every phone, laptop, and printer. No signup and no watermark, and your converted file is ready in seconds.",
    instructions: [
      "Upload your Word document (.doc or .docx)",
      "Wait a few seconds while your file is converted to PDF",
      "Verify the result in the preview",
      "Download your PDF file",
      "Share it with confidence knowing it will look the same everywhere",
    ],
    processingType: "server",
    seoTitle: "Word to PDF Converter – Free Online DOCX to PDF Tool | ToolPilot",
    seoDescription: "Convert Word to PDF online for free. Fast DOCX to PDF converter. Preserve formatting. No signup required.",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "What Word formats are supported?", answer: "We support both .doc and .docx files, so older and newer Word documents both work." },
      { question: "Why shouldn't I just email the Word file?", answer: "Word files can look different on other devices and can be edited accidentally. Converting to PDF keeps your layout identical and protects your content." },
      { question: "Does the conversion change my formatting?", answer: "No. Fonts, images, tables, and page layout are preserved, so the PDF matches your original Word document." },
      { question: "Is Word to PDF conversion free?", answer: "Yes, converting Word to PDF is completely free. There are no hidden charges, no watermarks, and no account is required." },
      { question: "What can I use a Word to PDF converter for?", answer: "Common uses include submitting resumes, sending invoices and contracts, sharing assignments, and printing documents that need to look exactly as designed." },
    ],
    relatedTools: ["pdf-to-word", "jpg-to-pdf", "pdf-merger"],
  },
  {
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert JPG images to PDF online for free",
    longDescription: "Turn your JPG images into a single PDF document. Perfect for creating photo albums, scanned documents, and receipts to email, or for submitting image-based forms that only accept PDFs. You can upload multiple images, arrange their order, and merge them into one file in seconds. The conversion runs entirely in your browser, so your photos stay on your device.",
    instructions: [
      "Upload one or more JPG images",
      "Drag and drop to arrange the order",
      "Pick the page orientation",
      "Click Convert",
      "Download the combined PDF",
    ],
    processingType: "browser",
    seoTitle: "JPG to PDF Converter – Free Online JPG to PDF Tool | ToolPilot",
    seoDescription: "Convert JPG to PDF online for free. Merge multiple images into one PDF. Fast, simple, and private. No signup required.",
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf", "photo to pdf"],
    icon: "FileText",
    featured: true,
    popular: true,
    faqs: [
      { question: "Can I merge multiple JPGs into one PDF?", answer: "Yes, upload multiple images and they will be combined into a single PDF in the order you specify." },
      { question: "Is the conversion done in my browser?", answer: "Yes, JPG to PDF conversion happens entirely in your browser. Your images never leave your device." },
      { question: "Where would I use JPG to PDF?", answer: "Common uses include submitting scanned documents and resumes, creating photo albums, and emailing receipts as one file." },
      { question: "Can I change the orientation?", answer: "Yes, you can set pages to portrait or landscape before converting." },
    ],
    relatedTools: ["pdf-to-jpg", "png-to-pdf", "image-compressor"],
  },
  {
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert PDF pages to JPG images online for free",
    longDescription: "Turn any PDF into high-quality JPG images. Great for sharing individual pages on social media, sending a page to a colleague by email, or converting scanned PDFs into usable image files. You can convert the whole document or pick a specific page range. Each page is rendered as a crisp JPG that keeps text and images readable.",
    instructions: [
      "Upload your PDF file",
      "Choose whether to convert all pages or a page range",
      "Pick the output quality",
      "Click Convert",
      "Download your JPG images",
    ],
    processingType: "server",
    seoTitle: "PDF to JPG Converter – Free Online PDF to Image Tool | ToolPilot",
    seoDescription: "Convert PDF to JPG online for free. Extract pages as high-quality images. Fast and accurate. No signup required.",
    keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpg", "pdf to png"],
    icon: "FileText",
    faqs: [
      { question: "What quality will the JPG images be?", answer: "We render pages at the highest quality possible from the original PDF, so text and images stay crisp." },
      { question: "Can I convert only some pages?", answer: "Yes. You can convert a specific page range instead of the entire document." },
      { question: "Why convert PDF to JPG?", answer: "JPG images are easier to share on WhatsApp, social media, and email, and can be inserted directly into slides and documents." },
    ],
    relatedTools: ["jpg-to-pdf", "pdf-to-word", "image-compressor"],
  },
  {
    name: "PDF Compressor",
    slug: "pdf-compressor",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Compress PDF files to reduce size online for free",
    longDescription: "Reduce the size of your PDF files instantly without visibly losing quality. Whether you need to fit a PDF under an email attachment limit, upload it to a website, or share it on WhatsApp, our online PDF compressor uses smart compression to shrink documents by up to 80% while keeping text razor sharp and images clear. Choose between low, medium, and high compression levels to balance file size against quality, and see the exact new size before you download. Everything happens securely in your browser, so your files never leave your device.",
    instructions: [
      "Upload your PDF file (drag and drop or browse)",
      "Choose a compression level: low, medium, or high",
      "Click Compress and wait for the file to be optimized",
      "Check the new file size shown in the preview",
      "Download your smaller PDF",
    ],
    processingType: "browser",
    seoTitle: "PDF Compressor – Free Online Reduce PDF Size | ToolPilot",
    seoDescription: "Compress PDF files online for free. Reduce PDF size without losing quality. Fast, easy, and private.",
    keywords: ["pdf compressor", "reduce pdf size", "compress pdf", "shrink pdf"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "Will compression reduce quality?", answer: "Our compression uses smart algorithms to minimize quality loss while significantly reducing file size. Text stays sharp and images remain clear." },
      { question: "How much smaller will my PDF get?", answer: "Most PDFs shrink by 40-80% depending on the content and the compression level you choose. You can preview the new size before downloading." },
      { question: "Is this the best way to fit a PDF in an email?", answer: "Yes. Most email providers allow attachments up to 25 MB, and this compressor easily brings documents under that limit." },
      { question: "Is my PDF private?", answer: "Yes. Compression happens entirely in your browser, so your file never leaves your device." },
    ],
    relatedTools: ["pdf-merger", "pdf-splitter", "image-compressor"],
  },
  {
    name: "PDF Merger",
    slug: "pdf-merger",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Merge multiple PDF files into one online for free",
    longDescription: "Combine multiple PDF files into one single document with just a few clicks. Upload two or more files, drag and drop them into the exact order you want, and merge them into a single PDF — perfect for combining reports, invoices, scanned pages, or project files before sending them to a client or submitting them for approval. The merged document keeps the formatting and quality of the originals, and no watermark is ever added. All processing happens in your browser, which makes it fast, free, and completely private.",
    instructions: [
      "Upload two or more PDF files",
      "Drag and drop the files to set the correct order",
      "Optionally rotate or remove any page",
      "Click Merge PDFs",
      "Download your combined file",
    ],
    processingType: "browser",
    seoTitle: "PDF Merger – Free Online Merge PDF Files | ToolPilot",
    seoDescription: "Merge PDF files online for free. Combine multiple PDFs into one. Fast, easy, and secure. No signup required.",
    keywords: ["pdf merger", "merge pdf", "combine pdf", "join pdf"],
    icon: "FileText",
    popular: true,
    faqs: [
      { question: "How many PDFs can I merge?", answer: "You can merge up to 20 PDF files at once, as long as they fit in your browser." },
      { question: "Can I change the order of pages?", answer: "Yes. Drag and drop any file to reorder it, and rotate or remove individual pages before merging." },
      { question: "Does merging reduce quality?", answer: "No. The merged file keeps the full quality and formatting of the original documents, and no watermark is added." },
      { question: "Are my files safe and private?", answer: "Yes. Merging happens entirely in your browser, so your documents never leave your device." },
    ],
    relatedTools: ["pdf-splitter", "pdf-compressor", "pdf-to-word"],
  },
  {
    name: "PDF Splitter",
    slug: "pdf-splitter",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Split PDF into multiple files online for free",
    longDescription: "Extract specific pages and create clean, separate PDF files in seconds. Whether you need to pull out a signature page, split a long textbook into chapters, or share just a few pages from a big report, our PDF splitter gives you full control. Upload a file, mark the exact pages or page ranges you want, and download them as a fresh PDF. Everything runs locally in your browser, so the document never leaves your device.",
    instructions: [
      "Upload your PDF file",
      "Choose to extract single pages or page ranges",
      "Select the exact pages you need",
      "Click Split",
      "Download the extracted PDF files",
    ],
    processingType: "browser",
    seoTitle: "PDF Splitter – Free Online Split PDF Pages | ToolPilot",
    seoDescription: "Split PDF files online for free. Extract specific pages or divide into multiple PDFs. Fast and private.",
    keywords: ["pdf splitter", "split pdf", "extract pdf pages", "separate pdf"],
    icon: "FileText",
    faqs: [
      { question: "Can I split by page range?", answer: "Yes, you can specify exact page ranges such as pages 1-5 or individual pages like pages 3, 7, and 12." },
      { question: "What can I use this for?", answer: "Common uses include extracting a signature page, splitting a textbook into chapters, and sharing only relevant pages from a report." },
      { question: "Does splitting change quality?", answer: "No. Extracted pages keep the original quality, text, and layout of the source PDF." },
      { question: "Is my PDF private?", answer: "Yes. Splitting happens in your browser, so your file never leaves your device." },
    ],
    relatedTools: ["pdf-merger", "pdf-rotator", "pdf-page-extractor"],
  },
  {
    name: "PDF Page Extractor",
    slug: "pdf-page-extractor",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Extract specific pages from a PDF file online for free",
    longDescription: "Pull exactly the pages you need out of a PDF and save them as a fresh, clean PDF file. This is great for emailing just one signature page, separating the important chapters of a study guide, or sharing only the relevant pages of a contract without sending the whole document. Everything runs locally in your browser, so your file stays private and never leaves your device.",
    instructions: [
      "Upload your PDF file",
      "Preview all pages as thumbnails",
      "Select the individual pages you want to keep",
      "Click Extract",
      "Download the new PDF with only your chosen pages",
    ],
    processingType: "browser",
    seoTitle: "PDF Page Extractor – Free Online Extract PDF Pages | ToolPilot",
    seoDescription: "Extract specific pages from PDF files online for free. Select and download only the pages you need.",
    keywords: ["pdf page extractor", "extract pdf pages", "select pdf pages"],
    icon: "FileText",
    faqs: [
      { question: "Can I preview pages before extracting?", answer: "Yes, you can see thumbnails of all pages and select the exact ones you want before creating the new PDF." },
      { question: "What can I use this tool for?", answer: "Common uses include emailing a single signed page, pulling a contract clause out of a long agreement, and sharing just the important pages of a manual or textbook." },
      { question: "Is my PDF kept private?", answer: "Yes. Extraction happens entirely in your browser, so your document never leaves your device." },
      { question: "How is this different from splitting a PDF?", answer: "Page extraction lets you pick the exact pages you need and combines them into one tidy PDF, instead of creating a file for every page." },
    ],
    relatedTools: ["pdf-splitter", "pdf-merger", "pdf-to-jpg"],
  },
  {
    name: "PDF Rotator",
    slug: "pdf-rotator",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Rotate PDF pages online for free",
    longDescription: "Rotate individual pages or the entire PDF by 90, 180, or 270 degrees to fix upside-down or sideways pages. This is perfect for correcting scanned documents that were saved in the wrong orientation, turning landscape pages to portrait before printing, or preparing slides and reports that are easier to read. All processing happens right in your browser, keeping your files private and secure.",
    instructions: [
      "Upload your PDF file",
      "Choose whether to rotate all pages or just specific ones",
      "Select the rotation angle: 90, 180, or 270 degrees",
      "Preview the result",
      "Download your correctly oriented PDF",
    ],
    processingType: "browser",
    seoTitle: "PDF Rotator – Free Online Rotate PDF Pages | ToolPilot",
    seoDescription: "Rotate PDF pages online for free. Fix page orientation instantly. Fast, easy, and private.",
    keywords: ["pdf rotator", "rotate pdf", "flip pdf pages", "pdf orientation"],
    icon: "FileText",
    faqs: [
      { question: "What rotation angles are available?", answer: "You can rotate pages by 90, 180, or 270 degrees in either direction, which covers every orientation problem you are likely to run into." },
      { question: "Can I rotate only some pages?", answer: "Yes. You can rotate the whole document at once or choose a specific set of pages to fix individually." },
      { question: "Will rotating hurt the quality of my PDF?", answer: "No. Rotation only changes the orientation of the page; your text, images, and layout stay exactly the same." },
      { question: "Is my PDF private?", answer: "Yes. Rotation happens entirely in your browser, so your document never leaves your device." },
    ],
    relatedTools: ["pdf-splitter", "pdf-merger", "pdf-to-jpg"],
  },
  {
    name: "PDF Page Counter",
    slug: "pdf-page-counter",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Count pages in a PDF and view document details",
    longDescription: "Instantly see how many pages a PDF has by simply uploading the file. The tool reads page count, file size, title, author, creation date, and producer metadata straight from your document, all in the browser. Perfect for checking report and resume lengths before printing or submitting, verifying document sizes before emailing, and quickly confirming how many pages a scanned or prepared PDF actually contains.",
    instructions: [
      "Upload your PDF file",
      "Click Count Pages",
      "View the total page count and file details instantly",
    ],
    processingType: "browser",
    seoTitle: "PDF Page Counter - Free Online Count Pages in PDF | ToolPilot",
    seoDescription: "Count pages in a PDF online for free and view file details instantly. No upload - processed in your browser.",
    keywords: ["pdf page counter", "count pages in pdf", "how many pages in pdf", "pdf page count"],
    icon: "FileText",
    faqs: [
      { question: "How do I count pages in a PDF?", answer: "Just upload the PDF and the tool instantly shows the total number of pages as well as file size and other metadata." },
      { question: "Is my PDF uploaded anywhere?", answer: "No. The PDF is read entirely in your browser, so your document never leaves your device." },
      { question: "Can I check a PDF before printing?", answer: "Yes. Quickly check the page count before printing or submitting to avoid surprises with your printer or submission limits." },
      { question: "What other details can I see?", answer: "Besides page count, you can view file size, title, author, creation date, and the software that produced the PDF." },
    ],
    relatedTools: ["pdf-compressor", "pdf-splitter", "pdf-rotator"],
  },
  {
    name: "PDF to Excel",
    slug: "pdf-to-excel",
    category: "PDF Tools",
    categorySlug: "pdf",
    description: "Convert PDF tables to editable Excel spreadsheets",
    longDescription: "Turn the text and tabular data in a PDF into an editable Excel (.xlsx) file you can sort, filter, and reuse. Upload a selectable PDF with tables or columns, and the tool extracts the text into rows and columns, then downloads a real .xlsx workbook. This is perfect for financial statements, price lists, inventory sheets, mark sheets, and any printed data you need to bring into a spreadsheet without retyping.",
    instructions: [
      "Upload your PDF file",
      "Click Convert to Excel",
      "The tool extracts text into rows and columns",
      "Download the .xlsx file and open it in Excel",
    ],
    processingType: "browser",
    seoTitle: "PDF to Excel Converter - Free Online PDF to XLSX | ToolPilot",
    seoDescription: "Convert PDF tables to editable Excel online for free. Export PDF data to .xlsx without retyping. Fast and private.",
    keywords: ["pdf to excel", "pdf to xlsx", "convert pdf to excel", "extract table from pdf", "pdf to spreadsheet"],
    icon: "FileText",
    faqs: [
      { question: "How do I convert a PDF to Excel?", answer: "Upload your PDF and click Convert to Excel. The tool extracts the selectable text into rows and columns and downloads a real .xlsx workbook you can open in Excel." },
      { question: "Does it work with scanned PDFs?", answer: "It works best with digital, selectable PDFs. Scanned PDFs store text as images and need OCR, so those may not extract cleanly." },
      { question: "Is a real Excel file created?", answer: "Yes, the tool generates a genuine .xlsx file with proper rows and columns that opens directly in Microsoft Excel, Google Sheets, and LibreOffice." },
      { question: "Is my file uploaded to a server?", answer: "No. The PDF is processed entirely in your browser and your data never leaves your device." },
    ],
    relatedTools: ["pdf-to-word", "pdf-page-counter", "pdf-to-jpg"],
  },
];
