import { ToolConfig } from "@/types/tool";

export const imageTools: ToolConfig[] = [
  {
    name: "Image Compressor",
    slug: "image-compressor",
    category: "Image Tools",
    categorySlug: "image",
    description: "Compress images to reduce file size without losing quality",
    longDescription: "Shrink your JPG, PNG, WebP, and GIF images without sacrificing visible quality. Perfect for making images load faster on your website, fitting them inside email or WhatsApp attachments, and keeping your photo library small. Our image compressor runs entirely in your browser and shows you a live before-and-after preview, so you can choose the right balance between file size and clarity. No uploads, no servers, and no limits — your photos never leave your device.",
    instructions: [
      "Upload one or more images (JPG, PNG, WebP, or GIF)",
      "Move the quality slider to your preferred level",
      "Watch the live size-reduction preview",
      "Click Compress",
      "Download your optimized images",
    ],
    processingType: "browser",
    seoTitle: "Image Compressor – Free Online Reduce Image Size | ToolPilot",
    seoDescription: "Compress images online for free. Reduce JPG, PNG, WebP size without losing quality. Fast, private, and easy to use.",
    keywords: ["image compressor", "compress image", "reduce image size", "optimize image"],
    icon: "Image",
    featured: true,
    popular: true,
    faqs: [
      { question: "What image formats are supported?", answer: "We support JPG, PNG, WebP, and GIF formats." },
      { question: "Is compression done in my browser?", answer: "Yes, all compression happens locally in your browser. Your images never leave your device." },
      { question: "How much will my image shrink?", answer: "Depending on the format and quality level you choose, most images reduce in size by 50-80% with no visible difference in quality." },
      { question: "Can I compress multiple images at once?", answer: "Yes, you can upload and compress several images in one go and download them together." },
    ],
    relatedTools: ["image-resizer", "webp-converter", "image-quality-optimizer"],
  },
  {
    name: "Image Resizer",
    slug: "image-resizer",
    category: "Image Tools",
    categorySlug: "image",
    description: "Resize images to any dimension online for free",
    longDescription: "Change your image to any width and height in seconds, without installing software. Perfect for resizing photos for social media profile pictures, website banners, document attachments, or product images. You can enter exact dimensions, choose a preset like square or 16:9, and let the tool maintain the aspect ratio automatically to avoid stretching. Everything is processed locally in your browser, keeping your images private.",
    instructions: [
      "Upload your image",
      "Enter the desired width and height",
      "Choose a preset ratio or keep aspect ratio locked",
      "Preview the result",
      "Download your resized image",
    ],
    processingType: "browser",
    seoTitle: "Image Resizer – Free Online Resize Image Tool | ToolPilot",
    seoDescription: "Resize images online for free. Change width and height. Maintain aspect ratio. Fast and private.",
    keywords: ["image resizer", "resize image", "change image size", "image dimensions"],
    icon: "Image",
    popular: true,
    faqs: [
      { question: "Can I maintain aspect ratio?", answer: "Yes, by default aspect ratio is maintained. You can also lock or unlock it manually to set custom proportions." },
      { question: "What sizes can I resize to?", answer: "Any size. Enter exact pixel dimensions or pick a preset such as square, 4:3, 16:9, or 9:16 for stories and posts." },
      { question: "Why does image size matter?", answer: "Instagram posts are around 1080x1080, YouTube thumbnails 1280x720, and passport photos have their own standards, so resizing saves time and storage." },
      { question: "Are my images private?", answer: "Yes. Resizing happens entirely in your browser, so your image never leaves your device." },
    ],
    relatedTools: ["image-compressor", "image-cropper", "image-rotator"],
  },
  {
    name: "JPG to PNG",
    slug: "jpg-to-png",
    category: "Image Tools",
    categorySlug: "image",
    description: "Convert JPG images to PNG format online for free",
    longDescription: "Convert your JPG and JPEG images into crisp PNG format in seconds, without losing any quality. PNG files support transparency and lossless compression, which makes them ideal for logos, graphics, and images you plan to edit further or place over other designs. Everything happens in your browser, so your photos stay on your device and are never uploaded anywhere.",
    instructions: [
      "Upload your JPG or JPEG image",
      "Adjust the quality settings if you want more detail",
      "Click Convert",
      "Verify the result in the preview",
      "Download your PNG image",
    ],
    processingType: "browser",
    seoTitle: "JPG to PNG Converter – Free Online JPG to PNG Tool | ToolPilot",
    seoDescription: "Convert JPG to PNG online for free. Fast image format converter. Supports transparency. No signup required.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png", "image converter"],
    icon: "Image",
    faqs: [
      { question: "Why should I convert JPG to PNG?", answer: "PNG supports transparency and lossless compression, making it the better choice for logos, icons, and graphics with crisp edges. JPG keeps photos small but can soften sharp lines." },
      { question: "Will the conversion make my background transparent?", answer: "No. Transparency is only preserved if the source image already contains it; a JPG photo always has a solid background, and PNG conversion keeps that background intact." },
      { question: "Does converting to PNG lose quality?", answer: "No quality is lost because PNG uses lossless compression. The converted file keeps every pixel from your original JPG." },
      { question: "Why is my PNG bigger than the JPG?", answer: "PNG uses lossless compression, so files are naturally larger than JPGs of the same image. That size increase is the trade-off for keeping every detail." },
      { question: "Is the conversion done in my browser?", answer: "Yes. JPG to PNG conversion happens entirely in your browser, so your photo is never uploaded anywhere." },
    ],
    relatedTools: ["png-to-jpg", "webp-converter", "image-compressor"],
  },
  {
    name: "PNG to JPG",
    slug: "png-to-jpg",
    category: "Image Tools",
    categorySlug: "image",
    description: "Convert PNG images to JPG format online for free",
    longDescription: "Convert your PNG images into compact JPG files that are much easier to share and store. JPG delivers the smaller file sizes that email providers, social media, and websites expect, making this perfect for turning large screenshots or photos into lighter files you can send from your phone. You stay in control of image quality while the conversion runs privately in your browser.",
    instructions: [
      "Upload your PNG image",
      "Adjust the quality level if you want a smaller file",
      "Click Convert",
      "Verify the result in the preview",
      "Download your JPG image",
    ],
    processingType: "browser",
    seoTitle: "PNG to JPG Converter – Free Online PNG to JPG Tool | ToolPilot",
    seoDescription: "Convert PNG to JPG online for free. Reduce file size with quality control. Fast and private.",
    keywords: ["png to jpg", "convert png to jpg", "png to jpeg", "image converter"],
    icon: "Image",
    faqs: [
      { question: "Why convert PNG to JPG at all?", answer: "JPG files are much smaller than PNGs, so they upload faster, fit inside email limits, and are easier to share on WhatsApp and social media." },
      { question: "Will I lose quality?", answer: "JPG uses lossy compression, so there can be a small drop in quality depending on the setting you choose. You can keep quality high, but the file will be bigger." },
      { question: "What happens to transparent areas of my image?", answer: "JPG does not support transparency, so transparent areas are given a solid background, usually white." },
      { question: "Is the conversion done in my browser?", answer: "Yes. PNG to JPG conversion happens entirely in your browser, so your image is never uploaded anywhere." },
    ],
    relatedTools: ["jpg-to-png", "webp-converter", "image-compressor"],
  },
  {
    name: "WebP Converter",
    slug: "webp-converter",
    category: "Image Tools",
    categorySlug: "image",
    description: "Convert images to/from WebP format online for free",
    longDescription: "Convert images to and from the WebP format while keeping quality and speed balanced. WebP is a modern format that makes web images significantly smaller, so it is perfect for blog banners, product photos, and website graphics that need to load fast without looking pixelated. You can also convert existing WebP files back to JPG or PNG when a platform or app does not support the format.",
    instructions: [
      "Upload your image",
      "Choose the output format: WebP, JPG, or PNG",
      "Adjust the quality level if needed",
      "Click Convert",
      "Download your converted image",
    ],
    processingType: "browser",
    seoTitle: "WebP Converter – Free Online WebP Image Tool | ToolPilot",
    seoDescription: "Convert images to/from WebP format online for free. Better compression, smaller files. Fast and private.",
    keywords: ["webp converter", "convert to webp", "webp to jpg", "webp to png"],
    icon: "Image",
    faqs: [
      { question: "What is WebP?", answer: "WebP is a modern image format developed by Google that produces smaller files than JPG or PNG while keeping comparable visual quality, which makes web pages load faster." },
      { question: "Why should I convert images to WebP?", answer: "Smaller images mean quicker page loads, lower data usage for visitors, and better performance on mobile. WebP is a great fit for websites, blogs, and online stores." },
      { question: "Can I convert WebP back to JPG or PNG?", answer: "Yes. If a platform or older app does not support WebP, you can convert your WebP files back to a format that works everywhere." },
      { question: "Will converting affect my image quality?", answer: "WebP is built to preserve visual quality while shrinking file size. You can adjust the quality level to find the balance that suits you." },
      { question: "Is the conversion done in my browser?", answer: "Yes. WebP conversion happens entirely in your browser, so your images are never uploaded anywhere." },
    ],
    relatedTools: ["jpg-to-png", "png-to-jpg", "image-compressor"],
  },
  {
    name: "Image Cropper",
    slug: "image-cropper",
    category: "Image Tools",
    categorySlug: "image",
    description: "Crop images to any size or aspect ratio online for free",
    longDescription: "Crop your images to any size or aspect ratio and keep exactly the part you want. Whether you are making a profile picture, a YouTube thumbnail, a passport-style photo, or a social media post, you can drag the crop box into place and download the perfect framing in seconds. Everything runs privately in your browser, so your photos never leave your device.",
    instructions: [
      "Upload your image",
      "Drag the crop box over the area you want to keep",
      "Choose a preset aspect ratio or a custom size",
      "Verify the result in the preview",
      "Download your cropped image",
    ],
    processingType: "browser",
    seoTitle: "Image Cropper – Free Online Crop Image Tool | ToolPilot",
    seoDescription: "Crop images online for free. Custom dimensions and aspect ratios. Fast, easy, and private.",
    keywords: ["image cropper", "crop image", "trim image", "cut image"],
    icon: "Image",
    faqs: [
      { question: "What aspect ratios are available?", answer: "You can crop freely or use presets such as square, 16:9, 4:3, and 3:2, plus custom dimensions for exact sizes like passport photos." },
      { question: "Can I set a custom size?", answer: "Yes. Enter exact pixel dimensions and the tool will frame your crop to that size, which is useful for banners, thumbnails, and print sizes." },
      { question: "What can I use cropping for?", answer: "Common uses include removing unwanted edges, fitting images to social media sizes, making profile pictures, and preparing thumbnails that stand out." },
      { question: "Is the cropped image quality kept?", answer: "Yes. Cropping only changes the framing and dimensions of your image; it does not reduce the sharpness of the area you keep." },
      { question: "Is the crop done in my browser?", answer: "Yes. Cropping happens entirely in your browser, so your photos are never uploaded anywhere." },
    ],
    relatedTools: ["image-resizer", "image-rotator", "image-compressor"],
  },
  {
    name: "Image Rotator",
    slug: "image-rotator",
    category: "Image Tools",
    categorySlug: "image",
    description: "Rotate images online for free",
    longDescription: "Rotate your images by a preset angle or any custom angle, and flip them horizontally or vertically, all for free. This is perfect for fixing phone photos that saved sideways, straightening scanned documents, or adjusting images for posters and design work. Everything runs privately in your browser, so your pictures never leave your device.",
    instructions: [
      "Upload your image",
      "Choose the rotation angle: 90, 180, 270, or a custom one",
      "Flip the image horizontally or vertically if needed",
      "Preview the result",
      "Download your rotated image",
    ],
    processingType: "browser",
    seoTitle: "Image Rotator – Free Online Rotate Image Tool | ToolPilot",
    seoDescription: "Rotate images online for free. Any angle, flip horizontal/vertical. Fast and private.",
    keywords: ["image rotator", "rotate image", "flip image", "turn image"],
    icon: "Image",
    faqs: [
      { question: "Can I rotate by a custom angle?", answer: "Yes. Besides 90, 180, and 270 degrees, you can enter any exact angle you need for fine control over the orientation." },
      { question: "Can I flip the image too?", answer: "Yes, you can mirror the image horizontally or vertically, either on its own or together with a rotation." },
      { question: "What can I use image rotation for?", answer: "Common uses include fixing photos that saved sideways, correcting scanned documents, and leveling images taken at an angle before sharing or printing." },
      { question: "Will rotating reduce quality?", answer: "No. Rotation changes the direction of the image without compressing or degrading the pixels, so quality stays the same." },
      { question: "Is the rotation done in my browser?", answer: "Yes. Rotation happens entirely in your browser, so your photos are never uploaded anywhere." },
    ],
    relatedTools: ["image-cropper", "image-resizer", "image-compressor"],
  },
  {
    name: "Image Quality Optimizer",
    slug: "image-quality-optimizer",
    category: "Image Tools",
    categorySlug: "image",
    description: "Optimize image quality and file size for web use",
    longDescription: "Automatically refine your images so they keep looking sharp while taking up less space, which makes pages load faster. This is perfect for website owners, bloggers, and online sellers who want better page speed and a smoother experience for visitors without manually tweaking every picture. The optimization happens in your browser, so your images stay private.",
    instructions: [
      "Upload your image",
      "Choose the optimization level you prefer",
      "Preview the result",
      "Click Optimize",
      "Download your optimized image",
    ],
    processingType: "browser",
    seoTitle: "Image Quality Optimizer – Free Online Image Optimization | ToolPilot",
    seoDescription: "Optimize images for web automatically. Balance quality and file size. Improve page speed.",
    keywords: ["image optimizer", "optimize image", "image quality", "web image optimization"],
    icon: "Image",
    faqs: [
      { question: "How is optimization different from compression?", answer: "Both aim to reduce file size, but optimization focuses on finding the best balance between quality and size for the web, so images stay sharp while loading quickly." },
      { question: "Will my images still look good?", answer: "Yes. The optimizer works to keep visual quality while trimming unnecessary size, and you can preview the result before downloading." },
      { question: "Why does image optimization matter for my website?", answer: "Lighter images load faster on every connection, which improves page speed, lowers data usage for visitors, and helps with search rankings and conversions." },
      { question: "Is the optimization done in my browser?", answer: "Yes. Optimization happens entirely in your browser, so your images are never uploaded anywhere." },
    ],
    relatedTools: ["image-compressor", "image-resizer", "webp-converter"],
  },
];
