import { ToolConfig } from "@/types/tool";

export const calculatorTools: ToolConfig[] = [
  {
    name: "GST Calculator",
    slug: "gst-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate GST (CGST, SGST, IGST) instantly",
    longDescription: "Calculate Goods and Services Tax (GST) instantly with the correct CGST, SGST, and IGST split. Our free GST calculator supports every Indian GST rate — 0%, 5%, 12%, 18%, and 28% — and works both ways: add GST to a base amount (forward calculation) or remove GST from a bill total (reverse calculation). Perfect for shopkeepers, freelancers, and small businesses that create invoices, as well as students learning how GST works. All calculation happens instantly in your browser with a simple, clean interface.",
    instructions: [
      "Enter the amount (before or after GST)",
      "Select the applicable GST rate (0%, 5%, 12%, 18%, or 28%)",
      "Choose CGST+SGST for within-state or IGST for inter-state",
      "Review the GST amount and the total with tax",
      "Copy the result for your invoice or record",
    ],
    processingType: "browser",
    seoTitle: "GST Calculator – Free Online GST Calculation Tool | ToolPilot",
    seoDescription: "Calculate GST online for free. Quick GST calculator for CGST, SGST, IGST with forward and reverse calculation.",
    keywords: ["gst calculator", "cgst sgst calculator", "gst rate calculator", "reverse gst"],
    icon: "Calculator",
    featured: true,
    popular: true,
    faqs: [
      { question: "What is GST?", answer: "Goods and Services Tax (GST) is an indirect tax levied on the supply of goods and services in India, replacing older taxes like VAT and service tax." },
      { question: "What are the GST rates?", answer: "India has 4 main GST rates: 5%, 12%, 18%, and 28%. Some items are exempt (0%)." },
      { question: "What is the difference between CGST+SGST and IGST?", answer: "CGST+SGST applies to intra-state transactions, while IGST applies to inter-state transactions." },
      { question: "What is reverse GST calculation?", answer: "Reverse calculation finds the GST already included in a final bill amount, so you know the actual pre-tax price and the tax component." },
      { question: "Is the GST calculator free?", answer: "Yes, it is 100% free with no signup. Enter an amount, pick a rate, and get the tax in a second." },
    ],
    relatedTools: ["salary-calculator", "income-tax-calculator", "emi-calculator"],
  },
  {
    name: "EMI Calculator",
    slug: "emi-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate loan EMI with amortization schedule",
    longDescription: "Calculate your monthly EMI for home loans, car loans, personal loans, and education loans in seconds. Enter the loan amount, interest rate, and tenure, and instantly see your Equated Monthly Installment plus a detailed amortization schedule that breaks down every payment into principal and interest. Use it before applying for a loan to know what you can afford, or to compare different lenders and tenures side by side. No signup, no limits — just a fast and accurate tool.",
    instructions: [
      "Enter the loan amount",
      "Enter the annual interest rate",
      "Enter the loan tenure in years (or months)",
      "Press Calculate to see your EMI",
      "Review the principal vs interest and amortization breakdown",
    ],
    processingType: "browser",
    seoTitle: "EMI Calculator – Free Online Loan EMI Calculator | ToolPilot",
    seoDescription: "Calculate loan EMI online for free. Home loan, car loan, personal loan EMI calculator with amortization schedule.",
    keywords: ["emi calculator", "loan emi calculator", "home loan emi", "car loan emi"],
    icon: "Calculator",
    featured: true,
    popular: true,
    faqs: [
      { question: "What is EMI?", answer: "EMI stands for Equated Monthly Installment. It is a fixed monthly payment made to repay a loan over a specified tenure." },
      { question: "How is EMI calculated?", answer: "EMI = P x r x (1 + r)^n / ((1 + r)^n - 1), where P is principal, r is monthly interest rate, and n is tenure in months." },
      { question: "What is an amortization schedule?", answer: "It is a monthly breakdown showing how much of each EMI goes toward principal and how much toward interest over the full loan tenure." },
      { question: "Does a longer tenure mean lower EMI?", answer: "Yes, extending tenure lowers the EMI but increases the total interest paid. Use the calculator to compare both." },
      { question: "Can I compare different interest rates?", answer: "Yes, change the rate or tenure anytime to compare options and choose the cheapest loan." },
    ],
    relatedTools: ["compound-interest-calculator", "salary-calculator", "gst-calculator"],
  },
  {
    name: "Salary Calculator",
    slug: "salary-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate in-hand salary from CTC with tax deductions",
    longDescription: "Find out exactly how much money lands in your bank account every month. Enter your CTC (Cost to Company) and this free salary calculator works out your take-home (in-hand) salary after deducting Employee Provident Fund, Professional Tax, and income tax under both the old and new tax regimes — so you can see which regime leaves you with more. Ideal for job offers, salary negotiations, and monthly budgeting. All calculations run instantly in your browser with a clear monthly breakdown.",
    instructions: [
      "Enter your yearly CTC",
      "Add your basic salary and deductions like PF if known",
      "Select the old or new tax regime",
      "Review the in-hand and monthly breakdown",
      "Switch regimes to compare take-home pay",
    ],
    processingType: "browser",
    seoTitle: "Salary Calculator India – Free Online In-Hand Salary Calculator | ToolPilot",
    seoDescription: "Calculate in-hand salary from CTC online. Income tax, PF, PT deductions. Supports old and new tax regime.",
    keywords: ["salary calculator", "in-hand salary calculator", "ctc to salary", "take home salary"],
    icon: "Calculator",
    popular: true,
    faqs: [
      { question: "What is CTC?", answer: "CTC (Cost to Company) is the total amount a company spends on an employee, including salary, benefits, and contributions." },
      { question: "What is the difference between old and new tax regime?", answer: "The new tax regime offers lower rates but fewer deductions. The old regime allows more deductions like 80C, HRA, etc." },
      { question: "Does this include PF and Professional Tax?", answer: "Yes. Employee Provident Fund (12% of basic) and state Professional Tax are deducted to arrive at your in-hand salary." },
      { question: "Why is my offered CTC different from in-hand salary?", answer: "CTC includes employer contributions and benefits, so the amount deposited monthly is always lower after tax and provident fund deductions." },
    ],
    relatedTools: ["income-tax-calculator", "gst-calculator", "emi-calculator"],
  },
  {
    name: "Income Tax Calculator",
    slug: "income-tax-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate income tax under old and new regime",
    longDescription: "Calculate your annual income tax under both the old and new tax regimes in seconds, and see instantly which one saves you more for FY 2025-26. Enter your income, add deductions like Section 80C, 80D, and HRA, and get a clear breakdown of taxable income and total tax. Updated for current Indian tax slabs, this tool is perfect for salaried employees comparing regimes before the new financial year, freelancers estimating tax, and anyone planning investments to reduce tax legally.",
    instructions: [
      "Enter your annual income",
      "Add applicable deductions (80C, 80D, HRA, etc.)",
      "Select the old or new tax regime",
      "View your tax liability and effective rate",
      "Compare both regimes to pick the cheaper option",
    ],
    processingType: "browser",
    seoTitle: "Income Tax Calculator India – Free Online Tax Calculator | ToolPilot",
    seoDescription: "Calculate income tax online for free. Compare old and new tax regime. All deductions supported. FY 2025-26.",
    keywords: ["income tax calculator", "tax calculator india", "old vs new tax regime", "section 80c"],
    icon: "Calculator",
    popular: true,
    faqs: [
      { question: "Which regime is better?", answer: "It depends on your income and deductions. Use our calculator to compare both regimes." },
      { question: "Do you include the standard deduction?", answer: "Yes, the standard deduction is built into the calculation automatically for both regimes." },
      { question: "What is the new tax regime?", answer: "The new regime uses lower slab rates and a higher exemption limit but allows far fewer deductions, so you can no longer claim most like 80C and HRA." },
      { question: "Is this calculator updated for FY 2025-26?", answer: "Yes, it uses the current Indian tax slabs and rules for FY 2025-26 (Assessment Year 2026-27)." },
    ],
    relatedTools: ["salary-calculator", "gst-calculator", "sip-calculator"],
  },
  {
    name: "SIP Calculator",
    slug: "sip-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate SIP returns and maturity amount",
    longDescription: "Calculate returns on your Systematic Investment Plan (SIP). See how your monthly investments can grow over time with the power of compounding.",
    instructions: ["Enter monthly investment amount", "Enter expected return rate", "Enter investment duration", "View projected returns"],
    processingType: "browser",
    seoTitle: "SIP Calculator – Free Online Mutual Fund SIP Calculator | ToolPilot",
    seoDescription: "Calculate SIP returns online for free. See how your mutual fund investments grow. Projected returns and maturity amount.",
    keywords: ["sip calculator", "mutual fund calculator", "investment calculator", "sip return calculator"],
    icon: "Calculator",
    faqs: [
      { question: "What is SIP?", answer: "SIP (Systematic Investment Plan) is a method of investing in mutual funds where you invest a fixed amount regularly." },
    ],
    relatedTools: ["compound-interest-calculator", "emi-calculator", "salary-calculator"],
  },
  {
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate percentages, percentage change, and more",
    longDescription: "Calculate what percent one number is of another, find percentage increase/decrease, and calculate percentage differences.",
    instructions: ["Select calculation type", "Enter values", "Get instant results"],
    processingType: "browser",
    seoTitle: "Percentage Calculator – Free Online Percentage Calculator | ToolPilot",
    seoDescription: "Calculate percentages online for free. Percentage of, percentage change, percentage difference. Fast and accurate.",
    keywords: ["percentage calculator", "percentage formula", "percentage increase", "percentage decrease"],
    icon: "Calculator",
    faqs: [
      { question: "How do I calculate what percent A is of B?", answer: "Formula: (A / B) x 100 = Percentage" },
    ],
    relatedTools: ["discount-calculator", "compound-interest-calculator", "simple-interest-calculator"],
  },
  {
    name: "Age Calculator",
    slug: "age-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate exact age in years, months, and days",
    longDescription: "Find your exact age in years, months, and days. Also calculate the number of days between two dates.",
    instructions: ["Enter your date of birth", "Select reference date", "View exact age breakdown"],
    processingType: "browser",
    seoTitle: "Age Calculator – Free Online Exact Age Calculator | ToolPilot",
    seoDescription: "Calculate your exact age in years, months, and days. Free online age calculator. Fast and accurate.",
    keywords: ["age calculator", "calculate age", "exact age", "birthday calculator"],
    icon: "Calculator",
    faqs: [
      { question: "Can I calculate age between two dates?", answer: "Yes, you can enter any two dates to find the exact duration between them." },
    ],
    relatedTools: ["date-calculator", "time-calculator", "percentage-calculator"],
  },
  {
    name: "Discount Calculator",
    slug: "discount-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate discounted price and savings",
    longDescription: "Quickly calculate the final price after discount and see how much you save. Supports single and multiple discounts.",
    instructions: ["Enter original price", "Enter discount percentage", "View final price and savings"],
    processingType: "browser",
    seoTitle: "Discount Calculator – Free Online Sale Price Calculator | ToolPilot",
    seoDescription: "Calculate discount price online for free. Find final price and savings. Supports multiple discounts.",
    keywords: ["discount calculator", "sale price calculator", "price after discount", "savings calculator"],
    icon: "Calculator",
    faqs: [
      { question: "Can I calculate multiple discounts?", answer: "Yes, you can apply multiple sequential discounts (e.g., 20% + 10% off)." },
    ],
    relatedTools: ["percentage-calculator", "gst-calculator", "roi-calculator"],
  },
  {
    name: "Compound Interest Calculator",
    slug: "compound-interest-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate compound interest with yearly breakdown",
    longDescription: "Calculate compound interest on savings and investments. See year-by-year growth breakdown with charts.",
    instructions: ["Enter principal amount", "Enter interest rate", "Enter compounding frequency", "Enter duration", "View results"],
    processingType: "browser",
    seoTitle: "Compound Interest Calculator – Free Online CI Calculator | ToolPilot",
    seoDescription: "Calculate compound interest online for free. Yearly breakdown. Charts and graphs. Plan your investments.",
    keywords: ["compound interest calculator", "ci calculator", "interest calculator", "investment growth"],
    icon: "Calculator",
    faqs: [
      { question: "What is the compound interest formula?", answer: "A = P(1 + r/n)^(nt), where A = amount, P = principal, r = annual rate, n = compounding frequency, t = years." },
    ],
    relatedTools: ["simple-interest-calculator", "sip-calculator", "emi-calculator"],
  },
  {
    name: "Simple Interest Calculator",
    slug: "simple-interest-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate simple interest on loans and deposits",
    longDescription: "Calculate simple interest on any principal amount. See total interest earned and maturity amount.",
    instructions: ["Enter principal amount", "Enter interest rate", "Enter time period", "View simple interest"],
    processingType: "browser",
    seoTitle: "Simple Interest Calculator – Free Online SI Calculator | ToolPilot",
    seoDescription: "Calculate simple interest online for free. Quick and accurate. Supports all time periods.",
    keywords: ["simple interest calculator", "si calculator", "interest calculator"],
    icon: "Calculator",
    faqs: [
      { question: "What is the simple interest formula?", answer: "SI = P x r x t / 100, where P = principal, r = annual rate, t = time in years." },
    ],
    relatedTools: ["compound-interest-calculator", "emi-calculator", "sip-calculator"],
  },
  {
    name: "BMI Calculator",
    slug: "bmi-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate Body Mass Index with category classification",
    longDescription: "Calculate your BMI using weight and height. Supports metric and imperial units. Shows BMI category and health recommendations.",
    instructions: ["Enter your weight", "Enter your height", "Select unit system", "View BMI score and category"],
    processingType: "browser",
    seoTitle: "BMI Calculator – Free Online Body Mass Index Calculator | ToolPilot",
    seoDescription: "Calculate BMI online for free. Body mass index calculator with category classification. Metric and imperial units.",
    keywords: ["bmi calculator", "body mass index", "bmi chart", "health calculator"],
    icon: "Calculator",
    faqs: [
      { question: "What are the BMI categories?", answer: "Underweight (below 18.5), Normal (18.5-24.9), Overweight (25-29.9), Obese (30 and above)." },
    ],
    relatedTools: ["age-calculator", "unit-converter", "percentage-calculator"],
  },
  {
    name: "Unit Converter",
    slug: "unit-converter",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Convert between units of length, weight, temperature, and more",
    longDescription: "Convert between different units of measurement. Supports length, weight, temperature, area, volume, and speed conversions.",
    instructions: ["Select measurement category", "Choose from and to units", "Enter value", "Get converted result"],
    processingType: "browser",
    seoTitle: "Unit Converter – Free Online Unit Conversion Tool | ToolPilot",
    seoDescription: "Convert units online for free. Length, weight, temperature, area, volume converter. Fast and accurate.",
    keywords: ["unit converter", "measurement converter", "temperature converter", "weight converter"],
    icon: "Calculator",
    faqs: [
      { question: "What units are supported?", answer: "We support length (m, km, ft, in), weight (kg, lb, oz), temperature (C, F, K), area, volume, and speed." },
    ],
    relatedTools: ["bmi-calculator", "time-calculator", "date-calculator"],
  },
  {
    name: "Time Calculator",
    slug: "time-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Add, subtract, and calculate time durations",
    longDescription: "Add or subtract hours, minutes, and seconds. Calculate total duration between two times. Convert between time zones.",
    instructions: ["Enter time values", "Select operation (add/subtract)", "Get result"],
    processingType: "browser",
    seoTitle: "Time Calculator – Free Online Time Addition Subtraction | ToolPilot",
    seoDescription: "Calculate time online for free. Add, subtract hours and minutes. Duration calculator. Fast and accurate.",
    keywords: ["time calculator", "time addition", "time subtraction", "duration calculator"],
    icon: "Calculator",
    faqs: [
      { question: "Can I calculate duration between two times?", answer: "Yes, enter start and end time to find the exact duration." },
    ],
    relatedTools: ["date-calculator", "age-calculator", "unit-converter"],
  },
  {
    name: "Date Calculator",
    slug: "date-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate days between dates or add days to a date",
    longDescription: "Find the number of days between two dates or calculate a future/past date by adding or subtracting days.",
    instructions: ["Select calculation type", "Enter date(s)", "View results"],
    processingType: "browser",
    seoTitle: "Date Calculator – Free Online Days Between Dates | ToolPilot",
    seoDescription: "Calculate days between dates online for free. Add or subtract days from any date. Fast and accurate.",
    keywords: ["date calculator", "days between dates", "add days to date", "date difference"],
    icon: "Calculator",
    faqs: [
      { question: "Can I include or exclude weekends?", answer: "Yes, you can choose to count only business days by excluding weekends." },
    ],
    relatedTools: ["age-calculator", "time-calculator", "unit-converter"],
  },
];
