import { ToolConfig } from "@/types/tool";

export const businessTools: ToolConfig[] = [
  {
    name: "Invoice Generator",
    slug: "invoice-generator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Generate professional invoices online for free",
    longDescription: "Create professional invoices with company details, line items, taxes, and discounts. Export as PDF.",
    instructions: ["Enter company and client details", "Add line items with quantities and rates", "Download invoice as PDF"],
    processingType: "browser",
    seoTitle: "Invoice Generator – Free Online Create Invoices | ToolPilot",
    seoDescription: "Generate professional invoices online for free. Add company details, items, taxes. Download as PDF.",
    keywords: ["invoice generator", "create invoice", "free invoice", "invoice template"],
    icon: "Building2",
    featured: true,
    popular: true,
    faqs: [
      { question: "Can I add my company logo?", answer: "Yes, you can upload your company logo to include on the invoice." },
      { question: "What format can I download?", answer: "You can download invoices as PDF files ready for printing or emailing." },
    ],
    relatedTools: ["quotation-generator", "gst-invoice-generator", "profit-margin-calculator"],
  },
  {
    name: "Quotation Generator",
    slug: "quotation-generator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Generate professional quotations and estimates",
    longDescription: "Create detailed quotations with itemized pricing, terms, and conditions. Export as PDF for clients.",
    instructions: ["Enter your business details", "Add client information and line items", "Download quotation as PDF"],
    processingType: "browser",
    seoTitle: "Quotation Generator – Free Online Quote Maker | ToolPilot",
    seoDescription: "Generate professional quotations online for free. Itemized pricing, terms. Download as PDF.",
    keywords: ["quotation generator", "quote maker", "estimate generator", "price quote"],
    icon: "Building2",
    faqs: [
      { question: "Can I add terms and conditions?", answer: "Yes, you can add custom terms and conditions to each quotation." },
    ],
    relatedTools: ["invoice-generator", "gst-invoice-generator", "profit-margin-calculator"],
  },
  {
    name: "GST Invoice Generator",
    slug: "gst-invoice-generator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Generate GST-compliant invoices with tax breakup",
    longDescription: "Create GST-compliant invoices with CGST, SGST, or IGST breakup. Includes GSTIN, HSN/SAC codes, and all required fields.",
    instructions: ["Enter GSTIN and business details", "Add items with HSN/SAC and GST rates", "Download GST invoice as PDF"],
    processingType: "browser",
    seoTitle: "GST Invoice Generator – Free Online GST Invoice Tool | ToolPilot",
    seoDescription: "Generate GST invoices online for free. CGST/SGST/IGST breakup. GSTIN, HSN/SAC codes. Download as PDF.",
    keywords: ["gst invoice generator", "gst invoice", "tax invoice", "gst bill"],
    icon: "Building2",
    faqs: [
      { question: "What fields are included?", answer: "GSTIN, HSN/SAC codes, CGST/SGST/IGST breakup, supplier and recipient details, itemized list, and totals." },
    ],
    relatedTools: ["invoice-generator", "gst-calculator", "quotation-generator"],
  },
  {
    name: "Profit Margin Calculator",
    slug: "profit-margin-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate profit margin and markup percentage",
    longDescription: "Calculate gross profit margin, net profit margin, and markup percentage. See revenue, cost, and profit breakdown.",
    instructions: ["Enter selling price and cost price", "View profit margin and markup percentage"],
    processingType: "browser",
    seoTitle: "Profit Margin Calculator – Free Online Margin Calculator | ToolPilot",
    seoDescription: "Calculate profit margin online for free. Gross and net margin, markup percentage. Instant results.",
    keywords: ["profit margin calculator", "margin calculator", "markup calculator", "profit percentage"],
    icon: "Building2",
    faqs: [
      { question: "What is the difference between margin and markup?", answer: "Margin is profit as a percentage of selling price. Markup is profit as a percentage of cost price." },
    ],
    relatedTools: ["markup-calculator", "break-even-calculator", "roi-calculator"],
  },
  {
    name: "Markup Calculator",
    slug: "markup-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate markup percentage on cost price",
    longDescription: "Determine the selling price based on your desired markup percentage over cost. Plan your pricing strategy.",
    instructions: ["Enter cost price", "Enter desired markup percentage", "View selling price and profit"],
    processingType: "browser",
    seoTitle: "Markup Calculator – Free Online Calculate Markup | ToolPilot",
    seoDescription: "Calculate markup percentage online for free. Determine selling price from cost. Instant results.",
    keywords: ["markup calculator", "cost markup", "pricing calculator", "selling price calculator"],
    icon: "Building2",
    faqs: [
      { question: "How do I calculate markup?", answer: "Selling Price = Cost x (1 + Markup/100). For example, 50% markup on $100 cost = $150 selling price." },
    ],
    relatedTools: ["profit-margin-calculator", "break-even-calculator", "discount-calculator"],
  },
  {
    name: "Break-Even Calculator",
    slug: "break-even-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate break-even point for your business",
    longDescription: "Find the break-even point where total revenue equals total costs. Know exactly how many units you need to sell.",
    instructions: ["Enter fixed costs", "Enter variable cost per unit", "Enter selling price per unit", "View break-even point"],
    processingType: "browser",
    seoTitle: "Break-Even Calculator – Free Online Break-Even Analysis | ToolPilot",
    seoDescription: "Calculate break-even point online for free. Find how many units to sell to break even.",
    keywords: ["break even calculator", "break even analysis", "break even point", "business calculator"],
    icon: "Building2",
    faqs: [
      { question: "What is break-even?", answer: "Break-even is the point where total revenue equals total costs, meaning zero profit and zero loss." },
    ],
    relatedTools: ["profit-margin-calculator", "project-cost-calculator", "roi-calculator"],
  },
  {
    name: "Project Cost Calculator",
    slug: "project-cost-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Estimate total project costs with breakdown",
    longDescription: "Calculate total project cost by adding labor, materials, equipment, and overhead costs. Get a detailed breakdown.",
    instructions: ["Add labor costs", "Add materials and equipment costs", "Add overhead and contingency", "View total project cost"],
    processingType: "browser",
    seoTitle: "Project Cost Calculator – Free Online Estimate Project Costs | ToolPilot",
    seoDescription: "Estimate project costs online for free. Labor, materials, equipment breakdown. Budget planner.",
    keywords: ["project cost calculator", "project estimate", "project budget", "cost estimator"],
    icon: "Building2",
    faqs: [
      { question: "Can I add contingency costs?", answer: "Yes, you can add a contingency percentage to account for unexpected expenses." },
    ],
    relatedTools: ["construction-cost-calculator", "boq-calculator", "break-even-calculator"],
  },
  {
    name: "Construction Cost Calculator",
    slug: "construction-cost-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Estimate construction costs per square foot",
    longDescription: "Estimate construction costs based on area, material type, and construction quality. Get cost per square foot and total estimate.",
    instructions: ["Enter construction area (sq ft)", "Select material and quality type", "View estimated cost breakdown"],
    processingType: "browser",
    seoTitle: "Construction Cost Calculator – Free Online Building Cost Estimator | ToolPilot",
    seoDescription: "Estimate construction costs online for free. Per square foot calculation. Material and quality options.",
    keywords: ["construction cost calculator", "building cost estimator", "house construction cost", "sq ft cost"],
    icon: "Building2",
    faqs: [
      { question: "What factors affect construction cost?", answer: "Area, material quality, location, labor rates, design complexity, and finishing level all affect the total cost." },
    ],
    relatedTools: ["project-cost-calculator", "boq-calculator", "roi-calculator"],
  },
  {
    name: "BOQ Calculator",
    slug: "boq-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Create and calculate Bill of Quantities",
    longDescription: "Create a detailed Bill of Quantities (BOQ) with itemized materials, quantities, rates, and total costs.",
    instructions: ["Add line items with description", "Enter quantities and unit rates", "View itemized and total costs"],
    processingType: "browser",
    seoTitle: "BOQ Calculator – Free Online Bill of Quantities Tool | ToolPilot",
    seoDescription: "Create BOQ online for free. Itemized materials, quantities, rates. Total cost calculation.",
    keywords: ["boq calculator", "bill of quantities", "boq format", "construction boq"],
    icon: "Building2",
    faqs: [
      { question: "What is a BOQ?", answer: "A Bill of Quantities (BOQ) is a document listing all materials, labor, and costs required for a construction project." },
    ],
    relatedTools: ["construction-cost-calculator", "project-cost-calculator", "invoice-generator"],
  },
  {
    name: "ROI Calculator",
    slug: "roi-calculator",
    category: "Business Tools",
    categorySlug: "business",
    description: "Calculate Return on Investment",
    longDescription: "Calculate ROI percentage on any investment. See profit/loss and return rate. Supports both simple and annualized ROI.",
    instructions: ["Enter investment amount", "Enter return amount", "View ROI percentage and profit"],
    processingType: "browser",
    seoTitle: "ROI Calculator – Free Online Return on Investment Calculator | ToolPilot",
    seoDescription: "Calculate ROI online for free. Return on investment percentage and profit. Simple and annualized.",
    keywords: ["roi calculator", "return on investment", "investment return", "roi formula"],
    icon: "Building2",
    faqs: [
      { question: "What is the ROI formula?", answer: "ROI = ((Return - Investment) / Investment) x 100. For annualized ROI, divide by the number of years." },
    ],
    relatedTools: ["profit-margin-calculator", "break-even-calculator", "compound-interest-calculator"],
  },
];
