import { ToolConfig } from "@/types/tool";

export const calculatorTools: ToolConfig[] = [
  {
    name: "GST Calculator",
    slug: "gst-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate GST (CGST, SGST, IGST) instantly",
    longDescription: "Calculate Goods and Services Tax (GST) instantly with the correct CGST, SGST, and IGST split. Our free GST calculator supports every Indian GST rate — 0%, 5%, 12%, 18%, and 28% — and works both ways: add GST to a base amount (forward calculation) or remove GST from a bill total (reverse calculation). Perfect for shopkeepers, freelancers, and small businesses that create invoices, as well as students learning how GST works. All calculation happens instantly in your browser with a simple, clean interface.",
    instructions: [
      "Enter the amount (before or after GST)",
      "Select the applicable GST rate (0%, 5%, 12%, 18%, or 28%)",
      "Choose CGST+SGST for within-state or IGST for inter-state",
      "Review the GST amount and the total with tax",
      "Copy the result for your invoice or record",
    ],
    processingType: "browser",
    seoTitle: "GST Calculator – Free Online GST Calculation Tool | ToolPilot",
    seoDescription: "Calculate GST online for free. Quick GST calculator for CGST, SGST, IGST with forward and reverse calculation.",
    keywords: ["gst calculator", "cgst sgst calculator", "gst rate calculator", "reverse gst"],
    icon: "Calculator",
    featured: true,
    popular: true,
    faqs: [
      { question: "What is GST?", answer: "Goods and Services Tax (GST) is an indirect tax levied on the supply of goods and services in India, replacing older taxes like VAT and service tax." },
      { question: "What are the GST rates?", answer: "India has 4 main GST rates: 5%, 12%, 18%, and 28%. Some items are exempt (0%)." },
      { question: "What is the difference between CGST+SGST and IGST?", answer: "CGST+SGST applies to intra-state transactions, while IGST applies to inter-state transactions." },
      { question: "What is reverse GST calculation?", answer: "Reverse calculation finds the GST already included in a final bill amount, so you know the actual pre-tax price and the tax component." },
      { question: "Is the GST calculator free?", answer: "Yes, it is 100% free with no signup. Enter an amount, pick a rate, and get the tax in a second." },
    ],
    relatedTools: ["salary-calculator", "income-tax-calculator", "emi-calculator"],
  },
  {
    name: "EMI Calculator",
    slug: "emi-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate loan EMI with amortization schedule",
    longDescription: "Calculate your monthly EMI for home loans, car loans, personal loans, and education loans in seconds. Enter the loan amount, interest rate, and tenure, and instantly see your Equated Monthly Installment plus a detailed amortization schedule that breaks down every payment into principal and interest. Use it before applying for a loan to know what you can afford, or to compare different lenders and tenures side by side. No signup, no limits — just a fast and accurate tool.",
    instructions: [
      "Enter the loan amount",
      "Enter the annual interest rate",
      "Enter the loan tenure in years (or months)",
      "Press Calculate to see your EMI",
      "Review the principal vs interest and amortization breakdown",
    ],
    processingType: "browser",
    seoTitle: "EMI Calculator – Free Online Loan EMI Calculator | ToolPilot",
    seoDescription: "Calculate loan EMI online for free. Home loan, car loan, personal loan EMI calculator with amortization schedule.",
    keywords: ["emi calculator", "loan emi calculator", "home loan emi", "car loan emi"],
    icon: "Calculator",
    featured: true,
    popular: true,
    faqs: [
      { question: "What is EMI?", answer: "EMI stands for Equated Monthly Installment. It is a fixed monthly payment made to repay a loan over a specified tenure." },
      { question: "How is EMI calculated?", answer: "EMI = P x r x (1 + r)^n / ((1 + r)^n - 1), where P is principal, r is monthly interest rate, and n is tenure in months." },
      { question: "What is an amortization schedule?", answer: "It is a monthly breakdown showing how much of each EMI goes toward principal and how much toward interest over the full loan tenure." },
      { question: "Does a longer tenure mean lower EMI?", answer: "Yes, extending tenure lowers the EMI but increases the total interest paid. Use the calculator to compare both." },
      { question: "Can I compare different interest rates?", answer: "Yes, change the rate or tenure anytime to compare options and choose the cheapest loan." },
    ],
    relatedTools: ["compound-interest-calculator", "salary-calculator", "gst-calculator"],
  },
  {
    name: "Salary Calculator",
    slug: "salary-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate in-hand salary from CTC with tax deductions",
    longDescription: "Find out exactly how much money lands in your bank account every month. Enter your CTC (Cost to Company) and this free salary calculator works out your take-home (in-hand) salary after deducting Employee Provident Fund, Professional Tax, and income tax under both the old and new tax regimes — so you can see which regime leaves you with more. Ideal for job offers, salary negotiations, and monthly budgeting. All calculations run instantly in your browser with a clear monthly breakdown.",
    instructions: [
      "Enter your yearly CTC",
      "Add your basic salary and deductions like PF if known",
      "Select the old or new tax regime",
      "Review the in-hand and monthly breakdown",
      "Switch regimes to compare take-home pay",
    ],
    processingType: "browser",
    seoTitle: "Salary Calculator India – Free Online In-Hand Salary Calculator | ToolPilot",
    seoDescription: "Calculate in-hand salary from CTC online. Income tax, PF, PT deductions. Supports old and new tax regime.",
    keywords: ["salary calculator", "in-hand salary calculator", "ctc to salary", "take home salary"],
    icon: "Calculator",
    popular: true,
    faqs: [
      { question: "What is CTC?", answer: "CTC (Cost to Company) is the total amount a company spends on an employee, including salary, benefits, and contributions." },
      { question: "What is the difference between old and new tax regime?", answer: "The new tax regime offers lower rates but fewer deductions. The old regime allows more deductions like 80C, HRA, etc." },
      { question: "Does this include PF and Professional Tax?", answer: "Yes. Employee Provident Fund (12% of basic) and state Professional Tax are deducted to arrive at your in-hand salary." },
      { question: "Why is my offered CTC different from in-hand salary?", answer: "CTC includes employer contributions and benefits, so the amount deposited monthly is always lower after tax and provident fund deductions." },
    ],
    relatedTools: ["income-tax-calculator", "gst-calculator", "emi-calculator"],
  },
  {
    name: "Income Tax Calculator",
    slug: "income-tax-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate income tax under old and new regime",
    longDescription: "Calculate your annual income tax under both the old and new tax regimes in seconds, and see instantly which one saves you more for FY 2025-26. Enter your income, add deductions like Section 80C, 80D, and HRA, and get a clear breakdown of taxable income and total tax. Updated for current Indian tax slabs, this tool is perfect for salaried employees comparing regimes before the new financial year, freelancers estimating tax, and anyone planning investments to reduce tax legally.",
    instructions: [
      "Enter your annual income",
      "Add applicable deductions (80C, 80D, HRA, etc.)",
      "Select the old or new tax regime",
      "View your tax liability and effective rate",
      "Compare both regimes to pick the cheaper option",
    ],
    processingType: "browser",
    seoTitle: "Income Tax Calculator India – Free Online Tax Calculator | ToolPilot",
    seoDescription: "Calculate income tax online for free. Compare old and new tax regime. All deductions supported. FY 2025-26.",
    keywords: ["income tax calculator", "tax calculator india", "old vs new tax regime", "section 80c"],
    icon: "Calculator",
    popular: true,
    faqs: [
      { question: "Which regime is better?", answer: "It depends on your income and deductions. Use our calculator to compare both regimes." },
      { question: "Do you include the standard deduction?", answer: "Yes, the standard deduction is built into the calculation automatically for both regimes." },
      { question: "What is the new tax regime?", answer: "The new regime uses lower slab rates and a higher exemption limit but allows far fewer deductions, so you can no longer claim most like 80C and HRA." },
      { question: "Is this calculator updated for FY 2025-26?", answer: "Yes, it uses the current Indian tax slabs and rules for FY 2025-26 (Assessment Year 2026-27)." },
    ],
    relatedTools: ["salary-calculator", "gst-calculator", "sip-calculator"],
  },
  {
    name: "SIP Calculator",
    slug: "sip-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate SIP returns and maturity amount",
    longDescription: "Calculate the projected returns on your Systematic Investment Plan (SIP) and see how a fixed monthly investment can grow over time through the power of compounding. Enter your monthly amount, expected annual return rate, and investment duration to instantly see your total invested amount, estimated returns, and final maturity value. Ideal for mutual fund investors planning long-term goals like retirement, children's education, or a house down payment, and for beginners comparing different monthly amounts before starting a SIP.",
    instructions: [
      "Enter your monthly investment amount",
      "Enter the expected annual return rate",
      "Enter the investment duration in years",
      "Press Calculate to see your projected returns",
      "Review the total invested, estimated returns, and maturity value",
    ],
    processingType: "browser",
    seoTitle: "SIP Calculator – Free Online Mutual Fund SIP Calculator | ToolPilot",
    seoDescription: "Calculate SIP returns online for free. See how your mutual fund investments grow. Projected returns and maturity amount.",
    keywords: ["sip calculator", "mutual fund calculator", "investment calculator", "sip return calculator"],
    icon: "Calculator",
    faqs: [
      { question: "What is SIP?", answer: "SIP (Systematic Investment Plan) is a method of investing in mutual funds where you invest a fixed amount regularly, usually monthly, instead of a large one-time amount." },
      { question: "How does compounding benefit a SIP?", answer: "With compounding, the returns you earn are reinvested and also start earning returns. Over long periods, this means the growth accelerates, so starting early and investing consistently makes a big difference." },
      { question: "What return rate should I enter?", answer: "Enter the expected annual return you are aiming for based on the fund type. Equities have historically delivered higher long-term returns, while debt funds are more conservative, but past performance does not guarantee future returns." },
      { question: "Can I change my investment amount later?", answer: "Yes, most mutual funds let you increase, decrease, or pause your SIP amount. Use the calculator to see how changing the monthly amount affects your final corpus." },
    ],
    relatedTools: ["compound-interest-calculator", "emi-calculator", "salary-calculator"],
  },
  {
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate percentages, percentage change, and more",
    longDescription: "Calculate what percent one number is of another, find percentage increase or decrease, and work out percentage differences between two values, all in seconds. Just pick the type of percentage calculation you need, enter your numbers, and get an instant, accurate answer. Handy for everyday situations like working out discounts on shopping, calculating marks and exam scores, analysing salary or price changes at work, and checking growth in business reports.",
    instructions: [
      "Select the type of percentage calculation you need",
      "Enter the two values for your calculation",
      "Press Calculate to get the result",
      "Review the answer with the percentage sign",
      "Repeat for any other values you need to check",
    ],
    processingType: "browser",
    seoTitle: "Percentage Calculator – Free Online Percentage Calculator | ToolPilot",
    seoDescription: "Calculate percentages online for free. Percentage of, percentage change, percentage difference. Fast and accurate.",
    keywords: ["percentage calculator", "percentage formula", "percentage increase", "percentage decrease"],
    icon: "Calculator",
    faqs: [
      { question: "How do I calculate what percent A is of B?", answer: "Formula: (A / B) x 100 = Percentage. For example, 25 out of 50 is (25 / 50) x 100 = 50%." },
      { question: "How do I find a percentage of a number?", answer: "Multiply the number by the percentage divided by 100. For example, 20% of 1500 is 1500 x 0.20 = 300." },
      { question: "What is percentage increase or decrease?", answer: "Percentage change is calculated as (new value - old value) / old value x 100. A positive result is an increase and a negative result is a decrease." },
      { question: "Can I compare more than two values?", answer: "The calculator handles one calculation at a time, but you can run it multiple times to compare different pairs of values or changes." },
    ],
    relatedTools: ["discount-calculator", "compound-interest-calculator", "simple-interest-calculator"],
  },
  {
    name: "Age Calculator",
    slug: "age-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate exact age in years, months, and days",
    longDescription: "Find your exact age in years, months, and days by entering your date of birth, using today's date or any reference date you choose. The calculator also works out the precise number of days between any two dates automatically. Useful for filling in official forms and applications that need an exact age, planning birthdays and milestones, verifying age for eligibility checks, and quickly counting the days between important events.",
    instructions: [
      "Enter your date of birth",
      "Choose today's date or a custom reference date",
      "Press Calculate to see your exact age",
      "Review the breakdown in years, months, and days",
      "Check the total days between the two dates",
    ],
    processingType: "browser",
    seoTitle: "Age Calculator – Free Online Exact Age Calculator | ToolPilot",
    seoDescription: "Calculate your exact age in years, months, and days. Free online age calculator. Fast and accurate.",
    keywords: ["age calculator", "calculate age", "exact age", "birthday calculator"],
    icon: "Calculator",
    faqs: [
      { question: "Can I calculate age between two dates?", answer: "Yes, you can enter any two dates to find the exact age or duration between them in years, months, and days, not just from your date of birth." },
      { question: "Is the calculator accurate for leap years?", answer: "Yes, the calculator accounts for leap years, so durations and ages remain accurate even when the period crosses a February 29th." },
      { question: "What is my age in months or days?", answer: "Along with the full year-month-day breakdown, the calculator shows the total number of days and months between the two dates for quick reference." },
      { question: "Which date should I use as the reference date?", answer: "By default it uses today's date, but you can pick any custom date, for example to check an age or milestone as of a specific day in the past or future." },
    ],
    relatedTools: ["date-calculator", "time-calculator", "percentage-calculator"],
  },
  {
    name: "Discount Calculator",
    slug: "discount-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate discounted price and savings",
    longDescription: "Quickly calculate the final price after a discount and see exactly how much you save, whether it is a single percentage off or multiple sequential discounts stacked together. Enter the original price and the discount percentages to instantly get the discounted price and total savings. Perfect for checking sale prices during shopping, comparing offers across different stores and brands, and working out the real cost before buying a product, plan, or service.",
    instructions: [
      "Enter the original price of the item",
      "Enter the discount percentage being offered",
      "Add an additional discount if there is a second offer",
      "Press Calculate to see the final price",
      "Review your total savings on the purchase",
    ],
    processingType: "browser",
    seoTitle: "Discount Calculator – Free Online Sale Price Calculator | ToolPilot",
    seoDescription: "Calculate discount price online for free. Find final price and savings. Supports multiple discounts.",
    keywords: ["discount calculator", "sale price calculator", "price after discount", "savings calculator"],
    icon: "Calculator",
    faqs: [
      { question: "Can I calculate multiple discounts?", answer: "Yes, you can apply multiple sequential discounts, such as a 20% sale discount followed by a 10% extra offer, and the calculator applies them one after the other correctly." },
      { question: "How do I find the final price after a discount?", answer: "Subtract the discount amount from the original price. For a percentage discount, the amount saved is (original price x discount percentage) / 100." },
      { question: "What is the difference between single and multiple discounts?", answer: "A single discount is applied once to the original price. Multiple discounts are applied one after another to the already reduced price, so their combined effect is slightly less than simply adding the percentages." },
      { question: "Can I see how much I am saving?", answer: "Yes, the calculator shows both the final discounted price and the total amount you save compared with the original price." },
    ],
    relatedTools: ["percentage-calculator", "gst-calculator", "roi-calculator"],
  },
  {
    name: "Compound Interest Calculator",
    slug: "compound-interest-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate compound interest with yearly breakdown",
    longDescription: "Calculate compound interest on your savings, deposits, and investments and see exactly how your money can grow over time. Enter the principal, annual interest rate, compounding frequency, and duration to instantly get the total amount and the interest earned, with a clear year-by-year growth breakdown. Ideal for planning long-term investments like fixed deposits, comparing how different compounding intervals affect returns, and understanding the real long-term power of compound growth for goals such as retirement and children's education.",
    instructions: [
      "Enter the principal amount you are investing",
      "Enter the annual interest rate",
      "Choose how often interest compounds (monthly, quarterly, yearly)",
      "Enter the investment duration in years",
      "Press Calculate and review the total, interest, and yearly breakdown",
    ],
    processingType: "browser",
    seoTitle: "Compound Interest Calculator – Free Online CI Calculator | ToolPilot",
    seoDescription: "Calculate compound interest online for free. Yearly breakdown. Charts and graphs. Plan your investments.",
    keywords: ["compound interest calculator", "ci calculator", "interest calculator", "investment growth"],
    icon: "Calculator",
    faqs: [
      { question: "What is the compound interest formula?", answer: "A = P(1 + r/n)^(nt), where A is the final amount, P is the principal, r is the annual interest rate, n is the number of times interest compounds per year, and t is time in years." },
      { question: "What is the difference between simple and compound interest?", answer: "Simple interest is earned only on the original principal, while compound interest is earned on the principal plus the interest already accumulated, so it grows faster over time." },
      { question: "Does compounding frequency affect my returns?", answer: "Yes. The more frequently interest is compounded, the more interest is earned. For example, compounding monthly generally yields slightly more than compounding yearly at the same rate." },
      { question: "Is compound interest different from simple interest?", answer: "Yes, compound interest reinvests earned interest so it starts earning more interest, while simple interest stays flat on the original amount. Compound growth becomes significant over longer periods." },
    ],
    relatedTools: ["simple-interest-calculator", "sip-calculator", "emi-calculator"],
  },
  {
    name: "Simple Interest Calculator",
    slug: "simple-interest-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate simple interest on loans and deposits",
    longDescription: "Calculate simple interest on any principal amount for loans, deposits, and small investments, and see both the total interest and the final maturity amount. Enter the principal, annual interest rate, and time period to get an instantly accurate result. Useful for planning short-term fixed deposits and savings, understanding the interest cost on personal loans or borrowings, and checking how much interest a lump-sum amount will earn over a set period.",
    instructions: [
      "Enter the principal amount",
      "Enter the annual interest rate",
      "Enter the time period in years",
      "Press Calculate to see the simple interest",
      "Review the total interest and final maturity amount",
    ],
    processingType: "browser",
    seoTitle: "Simple Interest Calculator – Free Online SI Calculator | ToolPilot",
    seoDescription: "Calculate simple interest online for free. Quick and accurate. Supports all time periods.",
    keywords: ["simple interest calculator", "si calculator", "interest calculator"],
    icon: "Calculator",
    faqs: [
      { question: "What is the simple interest formula?", answer: "SI = P x r x t / 100, where P is the principal, r is the annual interest rate, and t is the time in years." },
      { question: "What is the difference between simple and compound interest?", answer: "Simple interest is calculated only on the original principal, while compound interest is also earned on previously accumulated interest, so compound interest grows faster over time." },
      { question: "Can simple interest be negative?", answer: "No, simple interest is always positive or zero as long as the principal, rate, and time are positive. A zero rate or zero time gives zero interest." },
      { question: "What does the maturity amount include?", answer: "The maturity amount is the total you receive at the end, which is the original principal plus the simple interest earned over the chosen period." },
    ],
    relatedTools: ["compound-interest-calculator", "emi-calculator", "sip-calculator"],
  },
  {
    name: "BMI Calculator",
    slug: "bmi-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate Body Mass Index with category classification",
    longDescription: "Calculate your Body Mass Index (BMI) using your weight and height, and see instantly which category you fall into, from underweight to obese. The calculator supports both metric and imperial units and shows general health guidance based on your score. Useful for anyone tracking their fitness and weight-loss progress, checking their weight range before a health check-up or insurance application, and understanding the standard categories used by health professionals.",
    instructions: [
      "Select your unit system (metric or imperial)",
      "Enter your weight",
      "Enter your height",
      "Press Calculate to see your BMI score",
      "Review your BMI category and general guidance",
    ],
    processingType: "browser",
    seoTitle: "BMI Calculator – Free Online Body Mass Index Calculator | ToolPilot",
    seoDescription: "Calculate BMI online for free. Body mass index calculator with category classification. Metric and imperial units.",
    keywords: ["bmi calculator", "body mass index", "bmi chart", "health calculator"],
    icon: "Calculator",
    faqs: [
      { question: "What are the BMI categories?", answer: "Underweight (below 18.5), Normal or healthy weight (18.5 to 24.9), Overweight (25 to 29.9), and Obese (30 and above) for adults." },
      { question: "How is BMI calculated?", answer: "BMI is your weight in kilograms divided by your height in metres squared. In imperial units it uses pounds and inches with a standard conversion factor." },
      { question: "Is BMI accurate for everyone?", answer: "BMI is a useful general screening tool but does not account for muscle mass, age, or body composition, so very muscular people may show a higher BMI without excess body fat." },
      { question: "Does this calculator give medical advice?", answer: "No, it only calculates your BMI and shows standard category ranges. For personalised health advice, always consult a qualified doctor or health professional." },
    ],
    relatedTools: ["age-calculator", "unit-converter", "percentage-calculator"],
  },
  {
    name: "Unit Converter",
    slug: "unit-converter",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Convert between units of length, weight, temperature, and more",
    longDescription: "Convert between different units of measurement across length, weight, temperature, area, volume, and speed in a single tool. Choose a category, pick the unit you have and the unit you want, enter a value, and get an instant, accurate converted result. Handy for everyday tasks like shopping and cooking, travel and weather, school and college work, construction and DIY projects, and comparing measurements given in different systems.",
    instructions: [
      "Select the measurement category (length, weight, etc.)",
      "Choose the unit you are converting from",
      "Choose the unit you are converting to",
      "Enter the value to convert",
      "View the instantly converted result",
    ],
    processingType: "browser",
    seoTitle: "Unit Converter – Free Online Unit Conversion Tool | ToolPilot",
    seoDescription: "Convert units online for free. Length, weight, temperature, area, volume converter. Fast and accurate.",
    keywords: ["unit converter", "measurement converter", "temperature converter", "weight converter"],
    icon: "Calculator",
    faqs: [
      { question: "What units are supported?", answer: "The converter supports length (m, km, ft, in), weight (kg, lb, oz), temperature (C, F, K), area, volume, and speed across commonly used units." },
      { question: "Is the conversion accurate?", answer: "Yes, conversions use standard, well-defined conversion factors, so results for supported units are precise and reliable." },
      { question: "Can I convert between metric and imperial units?", answer: "Yes, the tool supports both metric and imperial units, so you can easily convert between systems, such as kilograms to pounds or kilometres to miles." },
      { question: "Can I convert more than one unit at a time?", answer: "The calculator handles one conversion at a time, but you can switch the from and to units or enter a new value anytime for the next conversion." },
    ],
    relatedTools: ["bmi-calculator", "time-calculator", "date-calculator"],
  },
  {
    name: "Time Calculator",
    slug: "time-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Add, subtract, and calculate time durations",
    longDescription: "Add, subtract, and calculate durations using hours, minutes, and seconds, so you can work with time values quickly and accurately. Enter time values and choose an operation to get an instant result, or calculate the total duration between two times. Useful for tallying work hours and timesheets, planning schedules and travel time, timing tasks and workouts, and solving time calculations for studies or everyday planning.",
    instructions: [
      "Enter the first time value",
      "Enter the second time value if needed",
      "Select the operation (add or subtract)",
      "Press Calculate to get the result",
      "Review the result in hours, minutes, and seconds",
    ],
    processingType: "browser",
    seoTitle: "Time Calculator – Free Online Time Addition Subtraction | ToolPilot",
    seoDescription: "Calculate time online for free. Add, subtract hours and minutes. Duration calculator. Fast and accurate.",
    keywords: ["time calculator", "time addition", "time subtraction", "duration calculator"],
    icon: "Calculator",
    faqs: [
      { question: "Can I calculate duration between two times?", answer: "Yes, enter a start time and an end time to find the exact duration between them in hours, minutes, and seconds." },
      { question: "Can I add or subtract time values?", answer: "Yes, you can add two or more time values together or subtract one time from another, and the result is shown in hours, minutes, and seconds." },
      { question: "What happens if minutes or seconds exceed 60?", answer: "The calculator automatically carries over values, so 90 minutes becomes 1 hour and 30 minutes in the result." },
      { question: "Does this work across midnight?", answer: "For the duration between two times, you can specify whether the end time falls on a later day so the calculation remains correct across midnight." },
    ],
    relatedTools: ["date-calculator", "age-calculator", "unit-converter"],
  },
  {
    name: "Date Calculator",
    slug: "date-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate days between dates or add days to a date",
    longDescription: "Find the exact number of days between two dates, or calculate a future or past date by adding or subtracting days, weeks, or months from any starting date. Enter the dates and calculation type to get an instant, accurate result. Useful for planning project deadlines and deliveries, tracking billing and payment due dates, counting days until an event, and working out dates for travel, schedules, or personal milestones.",
    instructions: [
      "Select the type of date calculation you need",
      "Enter the start date (and end date if needed)",
      "Choose whether to add or subtract days",
      "Press Calculate to get the result",
      "Review the number of days or the resulting date",
    ],
    processingType: "browser",
    seoTitle: "Date Calculator – Free Online Days Between Dates | ToolPilot",
    seoDescription: "Calculate days between dates online for free. Add or subtract days from any date. Fast and accurate.",
    keywords: ["date calculator", "days between dates", "add days to date", "date difference"],
    icon: "Calculator",
    faqs: [
      { question: "Can I include or exclude weekends?", answer: "Yes, you can choose to count only business days by excluding weekends, which is useful for work deadlines and project scheduling." },
      { question: "How do I find the days between two dates?", answer: "Select the days-between option, enter the start and end dates, and the calculator returns the total number of days separating them." },
      { question: "Can I add days to get a future date?", answer: "Yes, enter a starting date and add a number of days, weeks, or months to instantly see the resulting future date." },
      { question: "Does the calculator handle leap years?", answer: "Yes, it correctly accounts for leap years, so date differences and added dates remain accurate even across February 29th." },
    ],
    relatedTools: ["age-calculator", "time-calculator", "unit-converter"],
  },
  {
    name: "Gratuity Calculator",
    slug: "gratuity-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Calculate your gratuity amount based on salary and years of service",
    longDescription: "Find out how much gratuity you are entitled to when leaving a job after completing at least five years of continuous service. Enter your last drawn basic salary, dearness allowance, and total years of service to get your gratuity amount under the Payment of Gratuity Act, plus the tax-exempt portion under Section 10(10). Useful while negotiating a resignation or retirement settlement and checking whether the figure your employer quotes is correct.",
    instructions: [
      "Enter your last drawn basic salary per month",
      "Add any dearness allowance (DA) you receive",
      "Enter total years of service after five years",
      "Press Calculate to see your gratuity and tax exemption",
    ],
    processingType: "browser",
    seoTitle: "Gratuity Calculator 2026 - Free Online Gratuity Calculation India | ToolPilot",
    seoDescription: "Calculate your gratuity amount online for free. Last drawn salary, years of service, and tax exemption under Section 10(10).",
    keywords: ["gratuity calculator", "gratuity calculation", "gratuity formula", "gratuity on resignation", "gratuity tax exemption"],
    icon: "Calculator",
    faqs: [
      { question: "How is gratuity calculated?", answer: "Gratuity = (Last drawn salary × 15 × Completed years of service) / 26. The last drawn salary includes basic pay and dearness allowance." },
      { question: "Am I eligible for gratuity?", answer: "You become eligible after completing five continuous years of full-time service with the same employer, though it may be paid on death or disability without this condition." },
      { question: "How much gratuity is tax-free?", answer: "The lower of the actual gratuity or the statutory limit (currently ₹20 lakh under Section 10(10)) is exempt from tax." },
      { question: "What is the 26 in the formula?", answer: "The Payment of Gratuity Act treats 15 days' pay per year of service, based on 26 working days per month, hence the divisor 26." },
    ],
    relatedTools: ["salary-calculator", "gratuity-calculator", "epf-interest-calculator", "income-tax-calculator"],
  },
  {
    name: "EPF Interest Calculator",
    slug: "epf-interest-calculator",
    category: "Calculators",
    categorySlug: "calculators",
    description: "Estimate your EPF corpus and interest at retirement",
    longDescription: "Estimate how your Provident Fund corpus will grow until retirement. Enter your basic salary, contribution rate, interest rate, current age, and retirement age to see your monthly contribution, total deposits, interest earned, and projected balance. The tool also shows a year-by-year breakdown of interest and balance growth. Ideal for planning long-term savings and understanding the power of compounding in your EPF account.",
    instructions: [
      "Enter your basic salary and DA per month",
      "Set the EPF contribution rate (default 12%)",
      "Enter the current EPF interest rate and your ages",
      "Press Calculate to see your projected corpus and yearly growth",
    ],
    processingType: "browser",
    seoTitle: "EPF Interest Calculator 2026 - Free Provident Fund Calculator India | ToolPilot",
    seoDescription: "Estimate your EPF corpus at retirement online for free. Monthly contribution, interest earned, and projected balance with yearly breakdown.",
    keywords: ["epf calculator", "epf interest calculator", "provident fund calculator", "epf balance at retirement", "epf interest rate"],
    icon: "Calculator",
    faqs: [
      { question: "How does EPF interest work?", answer: "EPF interest is credited annually and compounds over time. The interest is calculated on the monthly running balance within the financial year." },
      { question: "What is the EPF contribution rate?", answer: "Both employee and employer contribute 12% of the basic salary and DA. A part of the employer's 12% (8.33% up to ₹15,000 basic) goes to the pension scheme, and the rest to EPF." },
      { question: "What is the current EPF interest rate?", answer: "The EPF interest rate is set by the EPFO each financial year and has recently been around 8.25%. Use the current rate in the calculator for an accurate estimate." },
      { question: "Is the calculator an exact estimate?", answer: "This gives a close estimate based on the inputs and yearly compounding. Actual corpus depends on the official rate declared each year and salary changes over time." },
    ],
    relatedTools: ["sip-calculator", "compound-interest-calculator", "gratuity-calculator", "simple-interest-calculator"],
  },
];
