import { ToolConfig } from "@/types/tool";

export const careerTools: ToolConfig[] = [
  {
    name: "Resume Builder",
    slug: "resume-builder",
    category: "Career Tools",
    categorySlug: "career",
    description: "Build a professional resume with our free builder",
    longDescription: "Create a professional, ATS-friendly resume in minutes. Choose from multiple templates, add your details, and download as PDF.",
    instructions: ["Choose a template", "Fill in your details", "Preview and download as PDF"],
    processingType: "browser",
    seoTitle: "Resume Builder – Free Online Professional Resume Maker | ToolPilot",
    seoDescription: "Build a professional resume online for free. ATS-friendly templates. Download as PDF. No signup required.",
    keywords: ["resume builder", "free resume maker", "cv builder", "resume template"],
    icon: "Briefcase",
    featured: true,
    popular: true,
    faqs: [
      { question: "Are the resumes ATS-friendly?", answer: "Yes, our templates are designed to pass Applicant Tracking Systems (ATS) used by employers." },
      { question: "Can I download as PDF?", answer: "Yes, you can download your completed resume as a high-quality PDF file." },
    ],
    relatedTools: ["resume-ats-checker", "resume-jd-matcher", "cover-letter-generator"],
  },
  {
    name: "Resume ATS Checker",
    slug: "resume-ats-checker",
    category: "Career Tools",
    categorySlug: "career",
    description: "Check if your resume passes ATS screening",
    longDescription: "Analyze your resume against ATS (Applicant Tracking System) requirements. Get scores and suggestions to improve your resume's chances.",
    instructions: ["Upload your resume", "Enter job description (optional)", "View ATS score and recommendations"],
    processingType: "ai",
    seoTitle: "Resume ATS Checker – Free Online ATS Score Checker | ToolPilot",
    seoDescription: "Check your resume ATS score online for free. See if your resume passes Applicant Tracking Systems.",
    keywords: ["ats checker", "resume ats score", "ats resume check", "resume scanner"],
    icon: "Briefcase",
    popular: true,
    faqs: [
      { question: "What is ATS?", answer: "ATS (Applicant Tracking System) is software used by employers to filter and rank job applications." },
      { question: "How accurate is the ATS score?", answer: "This is an AI-based estimate, not an actual employer ATS score. It provides useful guidance for optimization." },
    ],
    relatedTools: ["resume-builder", "resume-jd-matcher", "cover-letter-generator"],
  },
  {
    name: "Resume-JD Matcher",
    slug: "resume-jd-matcher",
    category: "Career Tools",
    categorySlug: "career",
    description: "Match your resume against a job description",
    longDescription: "Compare your resume with a job description to find skill gaps, missing keywords, and get a compatibility score. AI-based estimate for guidance.",
    instructions: ["Upload your resume", "Paste the job description", "View match score and recommendations"],
    processingType: "ai",
    seoTitle: "Resume-JD Matcher – Free Online Resume Job Match Tool | ToolPilot",
    seoDescription: "Match your resume against job descriptions online. Find skill gaps and missing keywords. AI-powered analysis.",
    keywords: ["resume matcher", "job description matcher", "resume job match", "skill gap analyzer"],
    icon: "Briefcase",
    faqs: [
      { question: "Is this the same as an employer's ATS score?", answer: "No, this is an AI-based compatibility estimate designed to help you improve your resume. It is not an actual employer ATS score." },
      { question: "What does it analyze?", answer: "Overall match, skills match, experience, education, domain relevance, missing keywords, strengths, weaknesses, and recommendations." },
    ],
    relatedTools: ["resume-ats-checker", "resume-builder", "cover-letter-generator"],
  },
  {
    name: "Cover Letter Generator",
    slug: "cover-letter-generator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Generate a professional cover letter with AI",
    longDescription: "Create a tailored cover letter for any job application. AI generates personalized content based on your resume and job description.",
    instructions: ["Upload your resume", "Paste the job description", "Generate and download cover letter"],
    processingType: "ai",
    seoTitle: "Cover Letter Generator – Free AI Cover Letter Maker | ToolPilot",
    seoDescription: "Generate professional cover letters online for free. AI-powered, personalized for each job application.",
    keywords: ["cover letter generator", "cover letter maker", "ai cover letter", "cover letter template"],
    icon: "Briefcase",
    popular: true,
    faqs: [
      { question: "Is the cover letter unique?", answer: "Yes, each cover letter is generated uniquely based on your resume and the specific job description." },
    ],
    relatedTools: ["resume-builder", "resume-ats-checker", "resume-jd-matcher"],
  },
  {
    name: "Salary Calculator",
    slug: "salary-calculator-career",
    category: "Career Tools",
    categorySlug: "career",
    description: "Estimate your market salary based on experience and skills",
    longDescription: "Get an estimated market salary based on your role, experience, skills, and location. Plan your career and salary negotiations.",
    instructions: ["Enter your role and experience", "Add skills and location", "View estimated salary range"],
    processingType: "browser",
    seoTitle: "Salary Calculator – Free Online Salary Estimator | ToolPilot",
    seoDescription: "Estimate your market salary online for free. Based on role, experience, skills, and location.",
    keywords: ["salary calculator", "salary estimator", "market salary", "salary range"],
    icon: "Briefcase",
    faqs: [
      { question: "How accurate is the estimate?", answer: "This is an approximate estimate based on market data. Actual salaries may vary based on company, negotiation, and other factors." },
    ],
    relatedTools: ["resume-builder", "notice-period-calculator", "experience-calculator"],
  },
  {
    name: "Notice Period Calculator",
    slug: "notice-period-calculator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Calculate your notice period end date",
    longDescription: "Calculate the exact end date of your notice period based on your start date and notice period duration. Plan your job transition.",
    instructions: ["Enter notice start date", "Enter notice period duration", "View end date and working days"],
    processingType: "browser",
    seoTitle: "Notice Period Calculator – Free Online Calculate Notice Period | ToolPilot",
    seoDescription: "Calculate your notice period end date online for free. Include or exclude weekends.",
    keywords: ["notice period calculator", "notice period end date", "last working day calculator"],
    icon: "Briefcase",
    faqs: [
      { question: "Does it exclude weekends?", answer: "Yes, you can choose to exclude weekends and public holidays from the notice period calculation." },
    ],
    relatedTools: ["experience-calculator", "date-calculator", "salary-calculator-career"],
  },
  {
    name: "Experience Calculator",
    slug: "experience-calculator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Calculate total work experience in years and months",
    longDescription: "Calculate your total professional work experience from multiple job tenures. Get total years, months, and days.",
    instructions: ["Add each job tenure (start and end dates)", "View total experience breakdown"],
    processingType: "browser",
    seoTitle: "Experience Calculator – Free Online Work Experience Calculator | ToolPilot",
    seoDescription: "Calculate total work experience online for free. Add multiple tenures. Get years, months, and days.",
    keywords: ["experience calculator", "work experience calculator", "total experience", "career calculator"],
    icon: "Briefcase",
    faqs: [
      { question: "Can I add multiple jobs?", answer: "Yes, you can add unlimited job tenures to calculate your total combined experience." },
    ],
    relatedTools: ["notice-period-calculator", "resume-builder", "salary-calculator-career"],
  },
  {
    name: "Interview Question Generator",
    slug: "interview-question-generator",
    category: "Career Tools",
    categorySlug: "career",
    description: "Generate interview questions for any role",
    longDescription: "Generate relevant interview questions for any job role or industry. Practice with common and technical questions.",
    instructions: ["Select job role and industry", "Choose question type", "View generated questions"],
    processingType: "ai",
    seoTitle: "Interview Question Generator – Free Online Interview Prep | ToolPilot",
    seoDescription: "Generate interview questions online for free. Practice for any role or industry. AI-powered.",
    keywords: ["interview questions", "interview prep", "mock interview", "interview practice"],
    icon: "Briefcase",
    faqs: [
      { question: "What types of questions are generated?", answer: "Behavioral, technical, situational, and role-specific questions tailored to your selected job role." },
    ],
    relatedTools: ["resume-builder", "resume-ats-checker", "cover-letter-generator"],
  },
  {
    name: "Job Description Analyzer",
    slug: "job-description-analyzer",
    category: "Career Tools",
    categorySlug: "career",
    description: "Analyze job descriptions for key requirements",
    longDescription: "Parse and analyze job descriptions to extract key skills, requirements, qualifications, and keywords. Optimize your application.",
    instructions: ["Paste the job description", "Click Analyze", "View extracted requirements and keywords"],
    processingType: "ai",
    seoTitle: "Job Description Analyzer – Free Online JD Analyzer | ToolPilot",
    seoDescription: "Analyze job descriptions online for free. Extract key skills, requirements, and keywords. AI-powered.",
    keywords: ["job description analyzer", "jd analyzer", "job requirements", "keyword extractor"],
    icon: "Briefcase",
    faqs: [
      { question: "What does it extract?", answer: "Key skills, required qualifications, experience level, responsibilities, and important keywords." },
    ],
    relatedTools: ["resume-jd-matcher", "resume-ats-checker", "interview-question-generator"],
  },
];
