import { ToolConfig } from "@/types/tool";

export const developerTools: ToolConfig[] = [
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Format and beautify JSON data instantly",
    longDescription: "Format, beautify, and validate your raw or minified JSON data with proper indentation and syntax highlighting so it is easy to read and debug. Whether you are reading a messy API response, checking a config file, or preparing clean JSON to share with teammates, this tool gives you readable output instantly, all in your browser with no signup and no data uploaded.",
    instructions: [
      "Paste your JSON data into the input box",
      "Click the Format button",
      "Review the indented output with syntax highlighting",
      "Copy the formatted JSON to your clipboard",
      "Paste it into your code or file",
    ],
    processingType: "browser",
    seoTitle: "JSON Formatter – Free Online JSON Beautifier | ToolPilot",
    seoDescription: "Format JSON online for free. Beautify and validate JSON data with syntax highlighting. Instant results.",
    keywords: ["json formatter", "json beautifier", "format json", "json validator"],
    icon: "Code2",
    featured: true,
    popular: true,
    faqs: [
      { question: "What is JSON used for?", answer: "JSON (JavaScript Object Notation) is a lightweight text format used to store and exchange data between servers, apps, and APIs. It uses key-value pairs and arrays that are easy for machines to parse and for humans to understand." },
      { question: "Is my JSON data sent to a server?", answer: "No, all formatting and validation happens locally in your browser. Your data never leaves your device, so it is safe to use with sensitive content." },
      { question: "Will formatting change my data?", answer: "No, formatting only adds indentation and spacing to make the JSON readable. The keys, values, and structure of your data stay exactly the same." },
      { question: "Can the formatter fix invalid JSON?", answer: "No, formatting requires valid JSON and will not repair broken data. Use the related JSON Validator tool to locate the exact syntax error first." },
      { question: "Can I format very large JSON?", answer: "Large files work fine because everything is processed in your browser. Very big documents may take a moment longer to beautify." },
    ],
    relatedTools: ["json-validator", "json-minifier", "base64-encoder"],
  },
  {
    name: "JSON Validator",
    slug: "json-validator",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Validate JSON data and find errors",
    longDescription: "Validate your JSON data instantly and see exactly where syntax errors such as missing commas, unclosed brackets, or trailing commas occur. Whether you are a developer debugging an API response or a beginner checking a config file before submission, a clear pass-or-fail result with the exact error location saves you from frustrating guesswork, and everything runs free in your browser.",
    instructions: [
      "Paste your JSON data into the input box",
      "Click the Validate button",
      "Check the result for a valid or invalid status",
      "Review the highlighted error location if validation fails",
      "Fix the issue and validate again",
    ],
    processingType: "browser",
    seoTitle: "JSON Validator – Free Online Validate JSON | ToolPilot",
    seoDescription: "Validate JSON data online for free. Find syntax errors instantly. Developer-friendly tool.",
    keywords: ["json validator", "validate json", "json checker", "json lint"],
    icon: "Code2",
    faqs: [
      { question: "What errors can this tool find?", answer: "It finds common JSON syntax problems such as missing commas, unclosed or mismatched brackets, trailing commas, and incorrect quotes. The error location is highlighted so you know exactly where to look." },
      { question: "What does valid JSON mean?", answer: "Valid JSON follows the strict rules of the format, including double-quoted keys, correct commas and brackets, and no trailing characters. Only valid JSON can be parsed correctly by browsers and APIs." },
      { question: "Is my data sent to a server?", answer: "No, validation happens entirely in your browser. Your JSON never leaves your device, which makes the tool safe for sensitive configuration data." },
      { question: "Will it accept JSON with comments?", answer: "Standard JSON does not allow comments, so JavaScript-style comments will be reported as a syntax error. Remove or convert comments before validating." },
    ],
    relatedTools: ["json-formatter", "json-minifier", "regex-tester"],
  },
  {
    name: "JSON Minifier",
    slug: "json-minifier",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Minify JSON to reduce file size",
    longDescription: "Remove every space, line break, and unnecessary character from your JSON so the file becomes much smaller and travels faster over the network. Use it when you want to embed JSON in a URL, shrink application configs, or trim down API payloads before shipping code, and everything runs quickly in your browser with no signup required.",
    instructions: [
      "Paste your JSON data into the input box",
      "Click the Minify button",
      "Review the compact single-line output",
      "Copy the minified JSON string",
      "Use it in your URL, config, or API request",
    ],
    processingType: "browser",
    seoTitle: "JSON Minifier – Free Online Minify JSON | ToolPilot",
    seoDescription: "Minify JSON online for free. Remove whitespace and reduce file size. Instant results.",
    keywords: ["json minifier", "minify json", "compress json", "json optimizer"],
    icon: "Code2",
    faqs: [
      { question: "Does minification change my data?", answer: "No, minification removes only whitespace, line breaks, and indentation that parsers ignore anyway. The keys, values, and structure of your JSON stay exactly the same." },
      { question: "When should I minify JSON?", answer: "Minify when you need to save bandwidth, embed data in a URL, or move files between services quickly. For reading and debugging, the formatted version is usually clearer." },
      { question: "How much smaller will the file get?", answer: "The reduction depends on how much whitespace the original JSON contained. Heavily indented files with many line breaks shrink the most." },
      { question: "Can I get the readable version back?", answer: "Yes, run the minified output through the JSON Formatter tool to beautify it again. Formatting is only presentation; the underlying data never changes." },
    ],
    relatedTools: ["json-formatter", "json-validator", "url-encoder"],
  },
  {
    name: "Base64 Encoder",
    slug: "base64-encoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Encode text or files to Base64",
    longDescription: "Turn any text, number, or file content into a Base64 string made only of safe ASCII characters, which is the go-to trick for embedding small images directly in HTML or CSS, passing complex parameters inside URLs, or sending binary data over text-only channels like email and JSON APIs. Everything is encoded instantly in your browser, free and without signup, so you can copy the result straight into your code.",
    instructions: [
      "Enter your text or upload a small file",
      "Click the Encode button",
      "Review the generated Base64 string",
      "Copy the encoded output",
      "Paste it into your HTML, CSS, or API payload",
    ],
    processingType: "browser",
    seoTitle: "Base64 Encoder – Free Online Encode to Base64 | ToolPilot",
    seoDescription: "Encode text to Base64 online for free. Fast Base64 encoding for text and files.",
    keywords: ["base64 encoder", "encode base64", "base64 encode text", "base64 convert"],
    icon: "Code2",
    popular: true,
    faqs: [
      { question: "What is Base64 used for?", answer: "Base64 represents binary data as plain ASCII text so it can pass through systems that only handle text, such as emails, URLs, and JSON. Common uses include embedding small images in HTML and sending files through APIs." },
      { question: "Is Base64 encryption?", answer: "No, Base64 is an encoding, not encryption, so anyone who sees the string can decode it. Do not use it to hide sensitive data; use proper encryption for that." },
      { question: "Can I encode a file?", answer: "Yes, you can upload a file and get its Base64 representation. To keep things fast in the browser, smaller files work best." },
      { question: "Why does the encoded output look longer?", answer: "Base64 uses only 64 characters to describe data, so the result is always larger than the original. This size increase is normal and expected." },
    ],
    relatedTools: ["base64-decoder", "url-encoder", "uuid-generator"],
  },
  {
    name: "Base64 Decoder",
    slug: "base64-decoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Decode Base64 encoded strings back to text",
    longDescription: "Convert any Base64 string back into its original text, image, or file so you can finally read what the encoding was hiding. It is especially handy when you receive encoded blobs through emails, API responses, JWT payloads, or configuration files and need the plain readable content, and decoding works instantly in your browser, free and without an account.",
    instructions: [
      "Paste the Base64 string into the input box",
      "Click the Decode button",
      "Review the decoded text or file preview",
      "Copy the decoded output",
      "Save the file if the input contained one",
    ],
    processingType: "browser",
    seoTitle: "Base64 Decoder – Free Online Decode Base64 | ToolPilot",
    seoDescription: "Decode Base64 strings online for free. Convert Base64 back to text instantly.",
    keywords: ["base64 decoder", "decode base64", "base64 to text", "base64 decode"],
    icon: "Code2",
    popular: true,
    faqs: [
      { question: "What if my input is not valid Base64?", answer: "The tool shows a clear error when the string contains characters outside the Base64 alphabet or is incomplete. Double-check that you copied the entire string before decoding." },
      { question: "Can it decode images and files?", answer: "Yes, if the Base64 string represents a file such as an image, the tool offers the decoded file for download. Plain text strings are shown directly as readable output." },
      { question: "Is decoding the same as decrypting?", answer: "No, decoding simply restores the original representation and provides no security. Base64 is meant to be reversible, so anyone with the string can decode it too." },
      { question: "Where does my data go?", answer: "All decoding happens locally in your browser. Your input never leaves your device and is not stored on any server." },
    ],
    relatedTools: ["base64-encoder", "url-decoder", "json-formatter"],
  },
  {
    name: "URL Encoder",
    slug: "url-encoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Encode URLs and query parameters",
    longDescription: "Escape special characters in URLs and query strings by converting them into the percent-encoded form that browsers, servers, and APIs expect. Whether you are building links that contain spaces and symbols, sending text in a query parameter, or passing structured data through a URL, this free browser tool makes every address safe to share, email, and click.",
    instructions: [
      "Enter the URL or text you want to encode",
      "Click the Encode button",
      "Review the percent-encoded output",
      "Copy the encoded URL",
      "Paste the safe link into your code, email, or browser",
    ],
    processingType: "browser",
    seoTitle: "URL Encoder – Free Online Encode URLs | ToolPilot",
    seoDescription: "Encode URLs online for free. URL encode special characters and query parameters instantly.",
    keywords: ["url encoder", "percent encoding", "encode url", "url encode"],
    icon: "Code2",
    faqs: [
      { question: "When do I need URL encoding?", answer: "You need it whenever a URL contains characters that are not safe in web addresses, such as spaces, ampersands, question marks, or non-English text. Encoding keeps the link working in browsers, emails, and requests." },
      { question: "What characters get encoded?", answer: "Spaces become %20, and reserved symbols like &, ?, =, and # become their percent codes. Safe letters and digits generally stay unchanged." },
      { question: "Does encoding change the meaning of the URL?", answer: "No, encoding is reversible and simply lets the browser and server read special characters inside an address. The receiver decodes the value back to the original form." },
      { question: "Is my input safe?", answer: "Encoding runs entirely in your browser and nothing is uploaded. You can safely encode sensitive query values without sending them anywhere." },
    ],
    relatedTools: ["url-decoder", "base64-encoder", "json-formatter"],
  },
  {
    name: "URL Decoder",
    slug: "url-decoder",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Decode URL-encoded strings",
    longDescription: "Turn percent-encoded URLs and query strings back into the plain, readable form they came from, so spaces, symbols, and non-English text display normally again. This helps when you receive a long trackable link or an encoded parameter from a service and want to see exactly what data the address carries, and decoding happens instantly in your browser for free.",
    instructions: [
      "Paste the encoded URL into the input box",
      "Click the Decode button",
      "Review the readable output",
      "Copy the decoded URL",
      "Use the plain link or value as needed",
    ],
    processingType: "browser",
    seoTitle: "URL Decoder – Free Online Decode URLs | ToolPilot",
    seoDescription: "Decode URL-encoded strings online for free. Convert percent-encoded text instantly.",
    keywords: ["url decoder", "decode url", "percent decode", "url decode"],
    icon: "Code2",
    faqs: [
      { question: "What is percent encoding?", answer: "Percent encoding replaces characters that are unsafe in a URL with a percent sign followed by two hex digits, such as %20 for a space. It is the standard way URLs carry spaces, symbols, and non-English text." },
      { question: "Why would a link need decoding?", answer: "Many modern links deliberately encode their query parameters to keep data intact while sharing. Decoding helps you read what a link actually contains, which is useful when debugging or before sending a link onward." },
      { question: "Does decoding change the underlying data?", answer: "No, decoding only restores how special characters were represented. The value is the same, just presented in a readable form." },
      { question: "Is decoding done privately?", answer: "Yes, decoding runs entirely in your browser and your link is never uploaded or stored. You can safely decode any address on any device." },
    ],
    relatedTools: ["url-encoder", "base64-decoder", "json-formatter"],
  },
  {
    name: "UUID Generator",
    slug: "uuid-generator",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Generate UUIDs (Universally Unique Identifiers)",
    longDescription: "Generate random UUID v4 identifiers in a single click for use in databases, APIs, applications, and distributed systems. Whether you need primary keys for a database table, unique order IDs for an online store, or test fixtures while building an app, this tool produces collision-free v4 identifiers instantly, in batches when you need them, all free in your browser.",
    instructions: [
      "Select the number of UUIDs you need",
      "Choose the output format and case options",
      "Click the Generate button",
      "Review the generated identifiers",
      "Copy the UUIDs for use in your code or database",
    ],
    processingType: "browser",
    seoTitle: "UUID Generator – Free Online Generate UUIDs | ToolPilot",
    seoDescription: "Generate UUIDs online for free. Create v4 UUIDs for databases and APIs. Batch generation supported.",
    keywords: ["uuid generator", "generate uuid", "unique identifier", "guid generator"],
    icon: "Code2",
    faqs: [
      { question: "What is a UUID?", answer: "A UUID (Universally Unique Identifier) is a 128-bit number used to identify things like database records, transactions, and user sessions. It is designed to be unique across systems without a central authority." },
      { question: "Which UUID version does this tool generate?", answer: "The tool generates version 4 UUIDs, which are built from random numbers rather than from hardware details or the current time. This makes them unpredictable and suitable for most everyday uses." },
      { question: "How many UUIDs can I generate at once?", answer: "You can generate a batch at once in various formats, which is handy for seeding test data. For larger jobs you can simply run a new batch." },
      { question: "Can I use UUIDs as database primary keys?", answer: "Yes, UUIDs are a popular primary key choice in distributed systems because they can be generated anywhere without a central server. They are longer than auto-increment numbers but guarantee uniqueness across machines." },
    ],
    relatedTools: ["timestamp-converter", "json-formatter", "base64-encoder"],
  },
  {
    name: "Timestamp Converter",
    slug: "timestamp-converter",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Convert Unix timestamps to dates and back",
    longDescription: "Convert Unix timestamps in seconds or milliseconds to human-readable dates, and ordinary dates back to timestamps, all in one place. Debug scheduling issues in your logs, verify when a value in your API response really occurred, or translate a timestamp someone sent you, with every conversion done instantly in your browser, free and without signup.",
    instructions: [
      "Enter a Unix timestamp or a date and time",
      "Click the Convert button",
      "Review the result in the available formats",
      "Copy the converted value",
      "Paste it into your logs, code, or spreadsheet",
    ],
    processingType: "browser",
    seoTitle: "Timestamp Converter – Free Online Unix Timestamp Tool | ToolPilot",
    seoDescription: "Convert Unix timestamps to dates online for free. Multiple formats supported. Instant conversion.",
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "date to timestamp"],
    icon: "Code2",
    faqs: [
      { question: "What is a Unix timestamp?", answer: "A Unix timestamp is the number of seconds, or sometimes milliseconds, that have passed since January 1, 1970 at UTC. It is the standard way computers store and communicate points in time." },
      { question: "Does the tool handle milliseconds?", answer: "Yes, it accepts both seconds and milliseconds and detects the unit from the length of the number. This avoids using a milliseconds value as seconds, which would give the wrong date." },
      { question: "Why does the converted date look off?", answer: "Timestamps are stored in UTC, so the date and time you see depend on the time zone used for display. Check against the time zone of the system that produced the timestamp." },
      { question: "Is my input private?", answer: "Yes, conversion happens entirely in your browser and your input is never uploaded. You can safely convert timestamps from logs or API responses." },
    ],
    relatedTools: ["uuid-generator", "json-formatter", "date-calculator"],
  },
  {
    name: "Regex Tester",
    slug: "regex-tester",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Test and debug regular expressions",
    longDescription: "Test, debug, and learn regular expressions against real sample text with instant matching and live highlights for every match and capture group. Whether you are validating inputs in a form, extracting phone numbers from a text file, or building a search pattern for a project, seeing results update as you type makes it fast to iterate until the pattern behaves exactly as you want.",
    instructions: [
      "Enter your regular expression pattern",
      "Paste or type a sample test string",
      "Add flags like g, i, or m if your pattern needs them",
      "Review the live matches and highlighted groups",
      "Refine your pattern and test again until it works",
    ],
    processingType: "browser",
    seoTitle: "Regex Tester – Free Online Regular Expression Tester | ToolPilot",
    seoDescription: "Test regular expressions online for free. Real-time matching, groups, and highlights. Developer-friendly.",
    keywords: ["regex tester", "regular expression tester", "regex test", "regex validator"],
    icon: "Code2",
    faqs: [
      { question: "Which regex flavor is supported?", answer: "The tester uses JavaScript regex syntax, including common flags such as g for global, i for case-insensitive, and m for multiline. Patterns that work here will also work in browsers and Node.js." },
      { question: "What do the capture groups show?", answer: "Parts of the pattern wrapped in parentheses appear as separate captured groups for each match. This makes it easy to see exactly which chunk of text each part of your expression extracts." },
      { question: "Can I use lookaheads and named groups?", answer: "Yes, the tool supports modern JavaScript features including lookaheads and named groups. Test them against your sample text to confirm the behaviour before using the pattern in code." },
      { question: "Is my test data safe?", answer: "Everything runs locally in your browser, so your pattern and sample text never leave your device. This makes it safe to test against real data such as email addresses or phone numbers." },
    ],
    relatedTools: ["json-formatter", "word-counter", "json-validator"],
  },
  {
    name: "Word Counter",
    slug: "word-counter",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Count words, characters, and sentences",
    longDescription: "Count words, characters with and without spaces, sentences, paragraphs, and lines in any text the moment you paste it. Whether you are staying inside a word limit for an essay or assignment, keeping a post within a social media character cap, or analysing the length of an article, the live counts update as you type so you always know where you stand.",
    instructions: [
      "Paste your text into the input box",
      "View the instant live word count",
      "Check character counts with and without spaces",
      "Review sentence, paragraph, and reading time estimates",
      "Edit your text and watch the counts update",
    ],
    processingType: "browser",
    seoTitle: "Word Counter – Free Online Word and Character Count | ToolPilot",
    seoDescription: "Count words and characters online for free. Instant word count, character count, sentence count. No signup.",
    keywords: ["word counter", "character counter", "word count", "text counter"],
    icon: "Code2",
    popular: true,
    faqs: [
      { question: "What counts does this tool show?", answer: "It shows words, characters with and without spaces, sentences, paragraphs, and an estimated reading time. All counts update live as you type or paste your text." },
      { question: "Can I keep posts within social media limits?", answer: "Yes, the character count with and without spaces helps you stay within caps for posts, tweets, and captions. Keep an eye on the live number and trim your text as needed." },
      { question: "How are words and sentences counted?", answer: "Words follow standard counting rules where each group of characters separated by spaces counts as one word. Full stops, question marks, and exclamation marks are treated as sentence endings." },
      { question: "Is my text uploaded anywhere?", answer: "No, all counting happens in your browser and your text never leaves your device. It is safe to paste essays, articles, or unpublished drafts." },
    ],
    relatedTools: ["lorem-ipsum-generator", "regex-tester", "json-formatter"],
  },
  {
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    category: "Developer Tools",
    categorySlug: "developer",
    description: "Generate placeholder text for designs and layouts",
    longDescription: "Generate classic Lorem Ipsum filler text for mockups, web designs, and layout previews where neutral placeholder copy is needed. Choose the number of paragraphs and the word limit per paragraph so the filler matches the space you are filling, then copy it straight into your design tool or prototype and keep moving.",
    instructions: [
      "Select the number of paragraphs you need",
      "Set the word limit for each paragraph",
      "Click the Generate button",
      "Review the placeholder text",
      "Copy the text into your design, mockup, or wireframe",
    ],
    processingType: "browser",
    seoTitle: "Lorem Ipsum Generator – Free Online Placeholder Text | ToolPilot",
    seoDescription: "Generate Lorem Ipsum placeholder text online for free. Customizable paragraphs and word count.",
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "lorem ipsum"],
    icon: "Code2",
    faqs: [
      { question: "What is Lorem Ipsum used for?", answer: "Lorem Ipsum is neutral placeholder text that designers use to preview layouts without distracting real content. The scrambled Latin keeps the focus on spacing, fonts, and overall structure." },
      { question: "Can I control how much text is created?", answer: "Yes, you choose the number of paragraphs and the word limit per paragraph. This lets you generate short snippets or long passages that fit a specific space." },
      { question: "Is Lorem Ipsum real Latin?", answer: "No, it is deliberately scrambled and altered Latin that reads like prose but has no meaningful content. That neutrality is exactly why it stays the industry standard placeholder." },
      { question: "Should I use it on a live website?", answer: "It is best for mockups, wireframes, and prototypes during the design phase. Replace it with your real copy before publishing a live page." },
    ],
    relatedTools: ["word-counter", "json-formatter", "regex-tester"],
  },
];