import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | ToolPilot",
  description: "Important disclaimers about ToolPilot's calculators, AI tools, and other online tools. Results are estimates — consult professionals for decisions.",
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8 prose dark:prose-invert">
      <h1>Disclaimer</h1>
      <p><em>Last updated: January 2025</em></p>
      <h2>General Information</h2>
      <p>
        The information provided by ToolPilot is for general informational purposes only. All tools
        and calculators provide estimates and should not be relied upon as professional advice.
      </p>
      <h2>Financial Calculators</h2>
      <p>
        Financial calculators on this website are for educational and planning purposes only. Results
        are estimates and may not reflect actual values. Consult a financial advisor for important
        financial decisions.
      </p>
      <h2>Tax Calculators</h2>
      <p>
        Tax calculators provide approximate calculations. Tax laws change frequently. Always consult
        a qualified tax professional for accurate tax advice.
      </p>
      <h2>AI-Generated Content</h2>
      <p>
        Content generated by AI tools may contain inaccuracies. AI-generated resumes, cover letters,
        and other documents should be reviewed and edited by the user before use.
      </p>
      <h2>No Professional Advice</h2>
      <p>
        ToolPilot does not provide legal, financial, medical, or professional advice. Use our tools
        as supplementary resources only.
      </p>
    </div>
  );
}
